# <b>🏏 IPL Cricket Analytics Platform</b>

## <b>Module 2: Exploratory Data Analysis (EDA)</b>

### <b>⬇️ Import the Libraries</b>

In [1]:
from pathlib import Path
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import networkx as nx

### <b>📂 Load Processed Datasets</b>

The previous module generated three processed datasets:

- **matches.csv** → Match-level information
- **deliveries.csv** → Ball-by-ball data
- **players.csv** → Player participation records

These datasets will be used throughout the remaining project.

In [2]:
processed_path = Path("../data/processed")

matches_df = pd.read_csv(
    processed_path / "matches.csv",
    parse_dates=["match_date"]
)

deliveries_df = pd.read_csv(
    processed_path / "deliveries.csv",
    parse_dates=["match_date"]
)

players_df = pd.read_csv(
    processed_path / "players.csv"
)

### <b>Section 1: Data Quality Assessment</b>

---

#### <b>🎯 Objective</b>

Before performing any statistical analysis or building machine learning models, it is essential to evaluate the quality of the processed datasets.

This notebook focuses on understanding:

- Dataset dimensions
- Data types
- Missing values
- Duplicate records
- Data consistency
- Memory usage

A thorough Data Quality Assessment ensures that the datasets are reliable and suitable for further analysis.

#### <b>📊 Dataset Dimensions</b>

Understanding the number of rows and columns provides a quick overview of the scale of each dataset.

This helps answer questions such as:

- How many IPL matches are available?
- How many ball-by-ball records exist?
- How many player participation records have been extracted?

In [3]:
print("Matches :", matches_df.shape)
print("Deliveries :", deliveries_df.shape)
print("Players :", players_df.shape)

Matches : (1243, 24)
Deliveries : (295732, 34)
Players : (27909, 6)

#### <b>👀 Dataset Preview</b>

Before starting the analysis, it is always a good practice to inspect a few sample records.

This allows us to verify:

- Column names
- Data formatting
- Missing values
- Unexpected observations

In [4]:
matches_df.head()

,match_id,season,match_date,city,venue,match_type,gender,team_type,team_1,team_2,...,win_by_wickets,result,method,eliminator,player_of_match,event_name,event_match_number,overs,balls_per_over,source_file
0,1082591,2017,05-04-2017,Hyderabad,"Rajiv Gandhi International Stadium, Uppal, Hyd...",T20,male,club,Sunrisers Hyderabad,Royal Challengers Bangalore,...,0,NaN,NaN,NaN,Yuvraj Singh,Indian Premier League,1.0,20,6,1082591.json
1,1082592,2017,06-04-2017,Pune,"Maharashtra Cricket Association Stadium, Pune",T20,male,club,Rising Pune Supergiants,Mumbai Indians,...,7,NaN,NaN,NaN,SPD Smith,Indian Premier League,2.0,20,6,1082592.json
2,1082593,2017,07-04-2017,Rajkot,Saurashtra Cricket Association Stadium,T20,male,club,Gujarat Lions,Kolkata Knight Riders,...,10,NaN,NaN,NaN,CA Lynn,Indian Premier League,3.0,20,6,1082593.json
3,1082594,2017,08-04-2017,Indore,Holkar Cricket Stadium,T20,male,club,Kings XI Punjab,Rising Pune Supergiants,...,6,NaN,NaN,NaN,GJ Maxwell,Indian Premier League,4.0,20,6,1082594.json
4,1082595,2017,08-04-2017,Bengaluru,"M Chinnaswamy Stadium, Bengaluru",T20,male,club,Royal Challengers Bangalore,Delhi Daredevils,...,0,NaN,NaN,NaN,KM Jadhav,Indian Premier League,5.0,20,6,1082595.json

In [5]:
deliveries_df.head()

,match_id,season,match_date,innings,batting_team,bowling_team,target_runs,target_overs,over,delivery_number,...,is_four,is_six,is_boundary,is_wicket,is_bowler_wicket,wickets_on_delivery,player_dismissed,dismissal_kind,fielder,source_file
0,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,1,...,0,0,0,0,0,0,NaN,NaN,NaN,1082591.json
1,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,2,...,0,0,0,0,0,0,NaN,NaN,NaN,1082591.json
2,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,3,...,1,0,1,0,0,0,NaN,NaN,NaN,1082591.json
3,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,4,...,0,0,0,0,0,0,NaN,NaN,NaN,1082591.json
4,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,5,...,0,0,0,0,0,0,NaN,NaN,NaN,1082591.json

In [6]:
players_df.head()

,match_id,season,team,player_name,player_registry_id,source_file
0,1082591,2017,Royal Challengers Bangalore,CH Gayle,db584dad,1082591.json
1,1082591,2017,Royal Challengers Bangalore,Mandeep Singh,c3a96caf,1082591.json
2,1082591,2017,Royal Challengers Bangalore,TM Head,12b610c2,1082591.json
3,1082591,2017,Royal Challengers Bangalore,KM Jadhav,99d63244,1082591.json
4,1082591,2017,Royal Challengers Bangalore,SR Watson,4329fbb5,1082591.json

#### <b>📋 Dataset Information</b>

The `.info()` method provides valuable metadata about the dataset.

It includes:

- Number of rows
- Number of columns
- Data types
- Non-null values
- Memory consumption

This is usually the first function executed by Data Scientists after loading data.

In [7]:
matches_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            1243 non-null   int64
 1   season              1243 non-null   int64
 2   match_date          1243 non-null   str
 3   city                1243 non-null   str
 4   venue               1243 non-null   str
 5   match_type          1243 non-null   str
 6   gender              1243 non-null   str
 7   team_type           1243 non-null   str
 8   team_1              1243 non-null   str
 9   team_2              1243 non-null   str
 10  toss_winner         1243 non-null   str
 11  toss_decision       1243 non-null   str
 12  winner              1218 non-null   str
 13  win_by_runs         1243 non-null   int64
 14  win_by_wickets      1243 non-null   int64
 15  result              25 non-null     str
 16  method              23 non-null     str
 17  eliminator          16 non-null     str
 18  player_of_match     1234 non-null   str
 19  event_name          1243 non-null   str
 20  event_match_number  1169 non-null   float64
 21  overs               1243 non-null   int64
 22  balls_per_over      1243 non-null   int64
 23  source_file         1243 non-null   str
dtypes: float64(1), int64(6), str(17)
memory usage: 233.2 KB

In [8]:
deliveries_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 295732 entries, 0 to 295731
Data columns (total 34 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   match_id             295732 non-null  int64
 1   season               295732 non-null  int64
 2   match_date           295732 non-null  str
 3   innings              295732 non-null  int64
 4   batting_team         295732 non-null  str
 5   bowling_team         295732 non-null  str
 6   target_runs          142303 non-null  float64
 7   target_overs         142303 non-null  float64
 8   over                 295732 non-null  int64
 9   delivery_number      295732 non-null  int64
 10  ball                 295732 non-null  float64
 11  batter               295732 non-null  str
 12  non_striker          295732 non-null  str
 13  bowler               295732 non-null  str
 14  batter_runs          295732 non-null  int64
 15  extra_runs           295732 non-null  int64
 16  total_runs           295732 non-null  int64
 17  wide_runs            295732 non-null  int64
 18  no_ball_runs         295732 non-null  int64
 19  bye_runs             295732 non-null  int64
 20  leg_bye_runs         295732 non-null  int64
 21  penalty_runs         295732 non-null  int64
 22  is_legal_delivery    295732 non-null  int64
 23  is_dot_ball          295732 non-null  int64
 24  is_four              295732 non-null  int64
 25  is_six               295732 non-null  int64
 26  is_boundary          295732 non-null  int64
 27  is_wicket            295732 non-null  int64
 28  is_bowler_wicket     295732 non-null  int64
 29  wickets_on_delivery  295732 non-null  int64
 30  player_dismissed     14705 non-null   str
 31  dismissal_kind       14705 non-null   str
 32  fielder              10721 non-null   str
 33  source_file          295732 non-null  str
dtypes: float64(3), int64(21), str(10)
memory usage: 76.7 MB

In [9]:
players_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27909 entries, 0 to 27908
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   match_id            27909 non-null  int64
 1   season              27909 non-null  int64
 2   team                27909 non-null  str
 3   player_name         27909 non-null  str
 4   player_registry_id  27909 non-null  str
 5   source_file         27909 non-null  str
dtypes: int64(2), str(4)
memory usage: 1.3 MB

##### <b>💡 Business Insight</b>

The data types should align with business expectations.

Examples:

- Match dates should be stored as datetime objects.
- Numerical statistics should use numeric data types.
- Team and player names should be stored as text.

Incorrect data types may lead to inaccurate calculations or inefficient memory usage.

#### <b>📈 Descriptive Statistics</b>

Descriptive statistics summarize the numerical characteristics of the datasets.

Key metrics include:

- Minimum
- Maximum
- Mean
- Standard Deviation
- Quartiles

These statistics help identify unusual values or potential data quality issues.

In [10]:
matches_df.describe(include="all")

,match_id,season,match_date,city,venue,match_type,gender,team_type,team_1,team_2,...,win_by_wickets,result,method,eliminator,player_of_match,event_name,event_match_number,overs,balls_per_over,source_file
count,1.243000e+03,1243.000000,1243,1243,1243,1243,1243,1243,1243,1243,...,1243.000000,25,23,16,1234,1243,1169.000000,1243.0,1243.0,1243
unique,NaN,NaN,947,35,38,1,1,1,17,17,...,NaN,2,1,7,321,1,NaN,NaN,NaN,1243
top,NaN,NaN,08-04-2017,Mumbai,"Wankhede Stadium, Mumbai",T20,male,club,Royal Challengers Bangalore,Mumbai Indians,...,NaN,tie,D/L,Delhi Capitals,AB de Villiers,Indian Premier League,NaN,NaN,NaN,1082591.json
freq,NaN,NaN,2,187,132,1243,1243,1243,159,152,...,NaN,16,23,4,25,1243,NaN,NaN,NaN,1
mean,9.758619e+05,2017.242156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.276750,NaN,NaN,NaN,NaN,NaN,31.921300,20.0,6.0,NaN
std,3.956922e+05,5.550682,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.358216,NaN,NaN,NaN,NaN,NaN,18.626023,0.0,0.0,NaN
min,3.359820e+05,2008.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,1.000000,20.0,6.0,NaN
25%,5.483705e+05,2012.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.000000,NaN,NaN,NaN,NaN,NaN,16.000000,20.0,6.0,NaN
50%,1.082636e+06,2017.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.000000,NaN,NaN,NaN,NaN,NaN,32.000000,20.0,6.0,NaN
75%,1.304102e+06,2022.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6.000000,NaN,NaN,NaN,NaN,NaN,47.000000,20.0,6.0,NaN
max,1.535465e+06,2026.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.000000,NaN,NaN,NaN,NaN,NaN,72.000000,20.0,6.0,NaN

In [11]:
deliveries_df.describe()

,match_id,season,innings,target_runs,target_overs,over,delivery_number,ball,batter_runs,extra_runs,...,leg_bye_runs,penalty_runs,is_legal_delivery,is_dot_ball,is_four,is_six,is_boundary,is_wicket,is_bowler_wicket,wickets_on_delivery
count,2.957320e+05,295732.000000,295732.000000,142303.000000,142303.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,...,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000,295732.000000
mean,9.770551e+05,2017.260753,1.482728,171.548400,19.887212,9.190331,3.629195,9.553099,1.290117,0.068336,...,0.019457,0.000034,0.962459,0.342303,0.116480,0.053356,0.169836,0.049724,0.045589,0.049724
std,3.953255e+05,5.543147,0.502436,33.079009,1.002723,5.679690,1.819312,5.682519,1.664418,0.342939,...,0.189288,0.013003,0.190083,0.474481,0.320801,0.224742,0.375489,0.217375,0.208591,0.217375
min,3.359820e+05,2008.000000,1.000000,43.000000,5.000000,0.000000,1.000000,0.100000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.483720e+05,2012.000000,1.000000,151.000000,20.000000,4.000000,2.000000,4.500000,0.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.082639e+06,2017.000000,1.000000,170.000000,20.000000,9.000000,4.000000,9.400000,1.000000,0.000000,...,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.304103e+06,2022.000000,2.000000,192.000000,20.000000,14.000000,5.000000,14.400000,1.000000,0.000000,...,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.535465e+06,2026.000000,6.000000,288.000000,20.000000,19.000000,11.000000,19.900000,6.000000,7.000000,...,5.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [12]:
players_df.describe(include="all")

,match_id,season,team,player_name,player_registry_id,source_file
count,2.790900e+04,27909.000000,27909,27909,27909,27909
unique,NaN,NaN,17,811,809,1243
top,NaN,NaN,Mumbai Indians,V Kohli,ba607b88,1370352.json
freq,NaN,NaN,3260,282,282,25
mean,9.853825e+05,2017.388871,NaN,NaN,NaN,NaN
std,3.972121e+05,5.588944,NaN,NaN,NaN,NaN
min,3.359820e+05,2008.000000,NaN,NaN,NaN,NaN
25%,5.483770e+05,2012.000000,NaN,NaN,NaN,NaN
50%,1.082649e+06,2017.000000,NaN,NaN,NaN,NaN
75%,1.359476e+06,2023.000000,NaN,NaN,NaN,NaN
max,1.535465e+06,2026.000000,NaN,NaN,NaN,NaN

#### <b>❓ Missing Value Analysis</b>

Missing values are common in real-world datasets.

However, not every missing value represents poor data quality.

For example:

- A delivery without a wicket will naturally have no dismissed player.
- Some matches may not have a recorded city.
- Player of the Match may not exist for certain abandoned matches.

Understanding *why* values are missing is more important than simply counting them.

In [13]:
matches_df.isnull().sum().sort_values(ascending=False)

eliminator            1227
method                1220
result                1218
event_match_number      74
winner                  25
player_of_match          9
match_id                 0
season                   0
team_type                0
gender                   0
match_type               0
venue                    0
city                     0
match_date               0
team_1                   0
team_2                   0
win_by_wickets           0
win_by_runs              0
toss_winner              0
toss_decision            0
event_name               0
overs                    0
balls_per_over           0
source_file              0
dtype: int64

In [14]:
deliveries_df.isnull().sum().sort_values(ascending=False)

fielder                285011
player_dismissed       281027
dismissal_kind         281027
target_overs           153429
target_runs            153429
match_id                    0
season                      0
bowling_team                0
match_date                  0
innings                     0
ball                        0
batter                      0
non_striker                 0
bowler                      0
batter_runs                 0
batting_team                0
over                        0
delivery_number             0
wide_runs                   0
total_runs                  0
extra_runs                  0
no_ball_runs                0
is_legal_delivery           0
bye_runs                    0
leg_bye_runs                0
penalty_runs                0
is_six                      0
is_four                     0
is_dot_ball                 0
is_boundary                 0
wickets_on_delivery         0
is_bowler_wicket            0
is_wicket                   0
source_file                 0
dtype: int64

In [15]:
players_df.isnull().sum().sort_values(ascending=False)

match_id              0
season                0
team                  0
player_name           0
player_registry_id    0
source_file           0
dtype: int64

##### <b>💡 Business Insight</b>

Missing values should always be investigated before applying any imputation or deletion strategy.

Domain knowledge plays a critical role in determining whether missing values indicate:

- Expected business scenarios
- Data collection issues
- Processing errors

Blindly removing rows with missing values can result in the loss of valuable information.

#### <b>📊 Missing Value Percentage</b>

Absolute counts can be misleading.

For example:

- 10 missing values out of 10 million records are insignificant.
- 10 missing values out of 20 records are highly concerning.

Therefore, percentages provide better context.

In [16]:
def missing_percentage(df):

    missing = (
        df.isnull().sum() / len(df)
    ) * 100

    return (
        missing[missing > 0]
        .sort_values(ascending=False)
        .round(2)
    )

In [17]:
missing_percentage(matches_df)

eliminator            98.71
method                98.15
result                97.99
event_match_number     5.95
winner                 2.01
player_of_match        0.72
dtype: float64

In [18]:
missing_percentage(deliveries_df)

fielder             96.37
dismissal_kind      95.03
player_dismissed    95.03
target_runs         51.88
target_overs        51.88
dtype: float64

In [19]:
missing_percentage(players_df)

Series([], dtype: float64)

#### <b>🔍 Duplicate Record Analysis</b>

Duplicate records can negatively impact analytical results.

In this section, we identify duplicate records across all processed datasets.

Match-level duplicates are particularly important because each match should appear only once.

In [20]:
print(matches_df.duplicated().sum())
print(deliveries_df.duplicated().sum())
print(players_df.duplicated().sum())

0
0
0

#### <b>✅ Business Rule Validation</b>

One important validation rule in cricket analytics is:

**Total Runs = Batter Runs + Extra Runs**

If this relationship is violated, the dataset may contain processing errors.

Business rule validation helps ensure data integrity before advanced analysis.

In [21]:
invalid_rows = deliveries_df[
    deliveries_df["total_runs"] !=
    (
        deliveries_df["batter_runs"] +
        deliveries_df["extra_runs"]
    )
]

print("Invalid rows:", len(invalid_rows))

Invalid rows: 0

#### <b>💾 Memory Usage</b>

Understanding memory consumption becomes increasingly important when working with large datasets.

Efficient memory usage enables:

- Faster computations
- Better scalability
- Lower infrastructure costs

In [22]:
print(matches_df.memory_usage(deep=True).sum() / 1024**2)
print(deliveries_df.memory_usage(deep=True).sum() / 1024**2)
print(players_df.memory_usage(deep=True).sum() / 1024**2)

1.2073860168457031
203.2333745956421
6.896803855895996

#### <b>📌 Summary</b>

The Data Quality Assessment confirms that the processed IPL datasets are suitable for exploratory analysis.

##### <b>Key Findings</b>

- Successfully loaded all processed datasets.
- Verified dataset dimensions.
- Confirmed appropriate data types.
- Evaluated descriptive statistics.
- Identified expected missing values.
- Checked duplicate records.
- Validated cricket-specific business rules.
- Measured memory usage.

The datasets are now ready for detailed cricket analytics and visualization.

### <B>Section 2 - Match-Level Analysis</b>

---

#### <b>🎯 Objective</b>

The objective of this session is to perform exploratory analysis on the match-level dataset.

This analysis focuses on understanding tournament trends, venue statistics, toss decisions, match outcomes, and player achievements.

The insights generated in this notebook can be useful for:

- IPL franchises
- Cricket analysts
- Sports broadcasters
- Fans
- Data Scientists

#### <b>📅 IPL Matches Across Seasons</b>

##### Business Question

How has the number of IPL matches changed across different seasons?

Understanding tournament growth helps identify:

- Expansion years
- Shortened tournaments
- Growth of the league

In [23]:
matches_per_season = (
    matches_df["season"]
    .value_counts()
    .sort_index()
    .reset_index()
)

matches_per_season.columns = [
    "Season",
    "Matches"
]

print(matches_per_season)

    Season  Matches
0     2008       58
1     2009       57
2     2010       60
3     2011       73
4     2012       74
5     2013       76
6     2014       60
7     2015       59
8     2016       60
9     2017       59
10    2018       60
11    2019       60
12    2020       60
13    2021       60
14    2022       74
15    2023       74
16    2024       71
17    2025       74
18    2026       74

In [24]:
fig = px.bar(
    matches_per_season,
    x="Season",
    y="Matches",
    text="Matches",
    title="IPL Matches by Season"
)

fig.update_layout(
    xaxis_title="Season",
    yaxis_title="Number of Matches"
)

fig.show()

##### <b>💡 Business Insight</b>

The number of matches has generally increased over time due to:

- Expansion of teams
- Format changes
- Increase in tournament popularity

Seasons with fewer matches should be investigated further, as they may correspond to special events such as shortened tournaments.

#### <b>🏟️ Matches by Venue</b>

##### Business Question

Which stadiums have hosted the highest number of IPL matches?

Venue analysis helps franchises evaluate:

- Home-ground advantage
- Popular venues
- Historic stadiums

In [25]:
venue_matches = (
    matches_df["venue"]
    .value_counts()
    .reset_index()
)

venue_matches.columns = [
    "Venue",
    "Matches"
]

# venue_matches.head(15)
venue_matches

                                                Venue  Matches
0                            Wankhede Stadium, Mumbai      132
1                               Eden Gardens, Kolkata      107
2                    M Chinnaswamy Stadium, Bengaluru      104
3                         Arun Jaitley Stadium, Delhi      104
4            MA Chidambaram Stadium, Chepauk, Chennai       98
5   Rajiv Gandhi International Stadium, Uppal, Hyd...       90
6                      Sawai Mansingh Stadium, Jaipur       68
7   Punjab Cricket Association IS Bindra Stadium, ...       61
8                    Narendra Modi Stadium, Ahmedabad       53
9                 Dubai International Cricket Stadium       46
10                 Dr DY Patil Sports Academy, Mumbai       37
11      Maharashtra Cricket Association Stadium, Pune       35
12                               Sheikh Zayed Stadium       29
13  Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...       29
14                            Sharjah Cricket Stadium       28
15                          Brabourne Stadium, Mumbai       27
16  Himachal Pradesh Cricket Association Stadium, ...       19
17  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...       17
18  Maharaja Yadavindra Singh International Cricke...       17
19                         Subrata Roy Sahara Stadium       16
20                                          Kingsmead       15
21                                    SuperSport Park       12
22             Saurashtra Cricket Association Stadium       10
23                             Holkar Cricket Stadium        9
24                   Zayed Cricket Stadium, Abu Dhabi        8
25                Barsapara Cricket Stadium, Guwahati        8
26  Shaheed Veer Narayan Singh International Stadi...        8
27                              New Wanderers Stadium        8
28                                           Newlands        7
29                                   St George's Park        7
30                                   Barabati Stadium        7
31                 JSCA International Stadium Complex        7
32                                      Nehru Stadium        5
33                                         Green Park        4
34                                       Buffalo Park        3
35                              De Beers Diamond Oval        3
36       Vidarbha Cricket Association Stadium, Jamtha        3
37                                    OUTsurance Oval        2

In [26]:
fig = px.bar(
    venue_matches.head(15),
    x="Matches",
    y="Venue",
    orientation="h",
    text="Matches",
    title="Top 15 IPL Venues"
)

fig.show()

##### <b>💡 Business Insight</b>

Some stadiums consistently host a larger number of IPL matches.

These venues often serve as:

- Home grounds
- Playoff venues
- Neutral venues for relocated seasons

#### <b>🌍 Matches by City</b>

##### Business Question

Which cities have hosted the most IPL matches?

Understanding city distribution provides insight into regional popularity and tournament logistics.

In [27]:
city_matches = (
    matches_df["city"]
    .fillna("Unknown")
    .value_counts()
    .reset_index()
)

city_matches.columns = [
    "City",
    "Matches"
]

In [28]:
fig = px.bar(
    city_matches.head(15),
    x="City",
    y="Matches",
    color="Matches",
    title="Top IPL Host Cities"
)

fig.show()

##### <b>💡 Business Insight</b>

A few metropolitan cities dominate IPL hosting.

These cities generally have:

- Larger stadiums
- Strong cricket fan bases
- Better infrastructure

#### <b>🪙 Toss Decision Analysis</b>

##### Business Question

Do IPL captains prefer batting first or bowling first after winning the toss?

In [29]:
toss_decisions = (
    matches_df["toss_decision"]
    .value_counts()
    .reset_index()
)

toss_decisions.columns = [
    "Decision",
    "Matches"
]

In [30]:
fig = px.pie(
    toss_decisions,
    names="Decision",
    values="Matches",
    hole=.45,
    title="Toss Decisions"
)

fig.show()

##### <b>💡 Business Insight</b>

Captains often adapt their toss strategy based on:

- Pitch conditions
- Dew factor
- Venue history
- Target chasing trends

#### <b>⭐ Player of the Match Analysis</b>

##### Business Question

Which players have won the most Player of the Match awards?

This metric identifies players who consistently deliver match-winning performances.

In [31]:
pom = (
    matches_df["player_of_match"]
    .value_counts()
    .head(15)
    .reset_index()
)

pom.columns = [
    "Player",
    "Awards"
]

In [32]:
fig = px.bar(
    pom,
    x="Awards",
    y="Player",
    orientation="h",
    text="Awards",
    title="Top Player of the Match Winners"
)

fig.show()

##### <b>💡 Business Insight</b>

Repeated Player of the Match awards indicate players who consistently influence match outcomes under different conditions.

#### <b>🏆 Winning Margins</b>

##### Business Question

How are IPL matches generally won?

Winning margins provide insight into match competitiveness.

In [33]:
matches_df["win_by_runs"].describe()

count    1243.000000
mean       13.932422
std        23.861556
min         0.000000
25%         0.000000
50%         0.000000
75%        20.000000
max       146.000000
Name: win_by_runs, dtype: float64

In [34]:
matches_df["win_by_wickets"].describe()

count    1243.000000
mean        3.276750
std         3.358216
min         0.000000
25%         0.000000
50%         3.000000
75%         6.000000
max        10.000000
Name: win_by_wickets, dtype: float64

In [35]:
fig = px.histogram(
    matches_df,
    x="win_by_runs",
    nbins=30,
    title="Distribution of Winning Margins (Runs)"
)

fig.show()

In [36]:
fig = px.histogram(
    matches_df,
    x="win_by_wickets",
    nbins=10,
    title="Distribution of Winning Margins (Wickets)"
)

fig.show()

#### <b>📌 Section Summary</b>

This section analyzed IPL matches from a tournament perspective.

##### <b>Questions Answered</b>

- Matches played each season
- Most frequently used venues
- Cities hosting IPL matches
- Toss decision trends
- Player of the Match leaders
- Winning margin distribution

These insights establish a strong understanding of the tournament before diving into team and player performance analysis.

### <b>Section 3 - Team-Level Analysis</b>

---

#### <b>🎯 Objective</b>

This notebook analyzes IPL team performance across all seasons.

The analysis aims to answer questions such as:

- Which team has played the most matches?
- Which team has won the most matches?
- Which team has the highest winning percentage?
- How has team performance evolved over different seasons?

These insights can help franchises evaluate historical performance and identify long-term trends.

#### <b>🏏 Matches Played by Each Team</b>

##### Business Question

Which IPL teams have played the highest number of matches?

Understanding participation helps compare teams fairly before evaluating their success.

In [37]:
team1 = matches_df[["team_1"]].rename(
    columns={"team_1": "Team"}
)

team2 = matches_df[["team_2"]].rename(
    columns={"team_2": "Team"}
)

all_teams = pd.concat(
    [team1, team2],
    ignore_index=True
)

matches_played = (
    all_teams["Team"]
    .value_counts()
    .reset_index()
)

matches_played.columns = [
    "Team",
    "Matches Played"
]

matches_played

                           Team  Matches Played
0                Mumbai Indians             291
1   Royal Challengers Bangalore             286
2         Kolkata Knight Riders             278
3           Chennai Super Kings             266
4              Rajasthan Royals             251
5           Sunrisers Hyderabad             211
6               Kings XI Punjab             190
7              Delhi Daredevils             161
8                Delhi Capitals             120
9                  Punjab Kings              88
10               Gujarat Titans              77
11              Deccan Chargers              75
12         Lucknow Super Giants              72
13                Pune Warriors              46
14      Rising Pune Supergiants              30
15                Gujarat Lions              30
16         Kochi Tuskers Kerala              14

In [38]:
fig = px.bar(
    matches_played,
    x="Team",
    y="Matches Played",
    color="Matches Played",
    text="Matches Played",
    title="Total Matches Played by Each IPL Team"
)

fig.update_layout(
    xaxis_title="Team",
    yaxis_title="Matches Played"
)

fig.show()

##### <b>💡 Business Insight</b>

Teams that joined the IPL in later seasons naturally have fewer matches.

Therefore, comparing only total wins may be misleading. Win percentage provides a fairer comparison.

#### <b>🏆 Total Wins by Team</b>

##### Business Question

Which IPL teams have won the highest number of matches?

In [39]:
team_wins = (
    matches_df["winner"]
    .dropna()
    .value_counts()
    .reset_index()
)

team_wins.columns = [
    "Team",
    "Wins"
]

team_wins

                           Team  Wins
0                Mumbai Indians   155
1           Chennai Super Kings   148
2   Royal Challengers Bangalore   143
3         Kolkata Knight Riders   140
4              Rajasthan Royals   123
5           Sunrisers Hyderabad   102
6               Kings XI Punjab    85
7              Delhi Daredevils    67
8                Delhi Capitals    58
9                Gujarat Titans    47
10                 Punjab Kings    41
11         Lucknow Super Giants    34
12              Deccan Chargers    29
13      Rising Pune Supergiants    15
14                Gujarat Lions    13
15                Pune Warriors    12
16         Kochi Tuskers Kerala     6

In [40]:
fig = px.bar(
    team_wins,
    x="Wins",
    y="Team",
    orientation="h",
    color="Wins",
    text="Wins",
    title="Total IPL Wins by Team"
)

fig.show()

##### <b>💡 Business Insight</b>

Teams with consistently high win counts have generally maintained stronger squads, effective leadership, and stable management over multiple seasons.

#### <b>📈 Team Winning Percentage</b>

##### Business Question

Which team has been the most successful based on win percentage?

Win percentage is a more balanced metric because it considers the number of matches played.

In [41]:
team_summary = (
    matches_played
    .merge(team_wins, on="Team", how="left")
)

team_summary["Wins"] = (
    team_summary["Wins"]
    .fillna(0)
)

team_summary["Win Percentage"] = (
    team_summary["Wins"]
    /
    team_summary["Matches Played"]
    * 100
).round(2)

team_summary.sort_values(
    "Win Percentage",
    ascending=False,
    inplace=True
)

team_summary

                           Team  Matches Played  Wins  Win Percentage
10               Gujarat Titans              77    47           61.04
3           Chennai Super Kings             266   148           55.64
0                Mumbai Indians             291   155           53.26
2         Kolkata Knight Riders             278   140           50.36
1   Royal Challengers Bangalore             286   143           50.00
14      Rising Pune Supergiants              30    15           50.00
4              Rajasthan Royals             251   123           49.00
5           Sunrisers Hyderabad             211   102           48.34
8                Delhi Capitals             120    58           48.33
12         Lucknow Super Giants              72    34           47.22
9                  Punjab Kings              88    41           46.59
6               Kings XI Punjab             190    85           44.74
15                Gujarat Lions              30    13           43.33
16         Kochi Tuskers Kerala              14     6           42.86
7              Delhi Daredevils             161    67           41.61
11              Deccan Chargers              75    29           38.67
13                Pune Warriors              46    12           26.09

In [42]:
fig = px.bar(
    team_summary,
    x="Team",
    y="Win Percentage",
    color="Win Percentage",
    text="Win Percentage",
    title="IPL Team Winning Percentage"
)

fig.show()

##### <b>💡 Business Insight</b>

Win percentage provides a normalized measure of team performance and allows fair comparison between teams that have played different numbers of matches.

#### <b>📅 Team Wins by Season</b>

##### Business Question

How has each team's performance changed across IPL seasons?

This analysis helps identify periods of dominance, decline, or consistent performance.

In [43]:
season_team_wins = (
    matches_df
    .dropna(subset=["winner"])
    .groupby(
        ["season", "winner"]
    )
    .size()
    .reset_index(name="Wins")
)

season_team_wins.head()

   season                 winner  Wins
0    2008    Chennai Super Kings     9
1    2008        Deccan Chargers     2
2    2008       Delhi Daredevils     7
3    2008        Kings XI Punjab    10
4    2008  Kolkata Knight Riders     6

In [44]:
fig = px.line(
    season_team_wins,
    x="season",
    y="Wins",
    color="winner",
    markers=True,
    title="Season-wise Wins by Team"
)

fig.update_layout(
    xaxis_title="Season",
    yaxis_title="Wins"
)

fig.show()

##### <b>💡 Business Insight</b>

Season-wise performance highlights long-term trends.

Teams may experience:

- Consistent dominance
- Temporary decline
- Strong comeback seasons
- Performance fluctuations after squad changes

#### <b>🪙 Toss Winner vs Match Winner</b>

##### Business Question

Does winning the toss increase the probability of winning the match?

This analysis evaluates whether toss advantage translates into match victories.

In [45]:
matches_df["Toss Won Match"] = (
    matches_df["toss_winner"]
    ==
    matches_df["winner"]
)

toss_impact = (
    matches_df["Toss Won Match"]
    .value_counts()
    .reset_index()
)

toss_impact.columns = [
    "Won Toss & Match",
    "Matches"
]

toss_impact

   Won Toss & Match  Matches
0              True      628
1             False      615

In [46]:
fig = px.pie(
    toss_impact,
    names="Won Toss & Match",
    values="Matches",
    hole=0.45,
    title="Impact of Winning the Toss"
)

fig.show()

##### <b>💡 Business Insight</b>

If a large proportion of toss winners also win the match, it suggests that external factors such as pitch conditions or dew may significantly influence match outcomes.

However, if the proportions are similar, team performance may have a greater impact than the toss itself.

#### <b>📌 Section Summary</b>

In this section, we analyzed IPL teams from multiple perspectives.

##### <b>Questions Answered</b>

- Which teams have played the most matches?
- Which teams have won the most matches?
- Which teams have the highest winning percentage?
- How has team performance changed over different seasons?
- Does winning the toss improve the chances of winning the match?

These insights provide a strong foundation for understanding team performance before moving to player-level analysis.

### <b>Section 4 – Batter Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook analyzes batting performance using ball-by-ball IPL data.

The analysis focuses on answering questions such as:

- Who has scored the most runs?
- Which players score at the fastest rate?
- Who hits the most boundaries?
- Which batters rotate the strike efficiently?
- Who are the most consistent performers?

The insights generated in this notebook can support franchise strategy, player scouting, and performance analysis.

#### <b>🏏 Most Runs Scored</b>

##### Business Question

Which batters have scored the highest number of runs in IPL history?

Total runs provide a basic measure of batting productivity and longevity.

In [47]:
batter_runs = (
    deliveries_df
    .groupby("batter", as_index=False)["batter_runs"]
    .sum()
    .sort_values("batter_runs", ascending=False)
)

batter_runs.rename(
    columns={"batter_runs": "Runs"},
    inplace=True
)

batter_runs.head(10)

             batter  Runs
693         V Kohli  9346
526       RG Sharma  7331
563        S Dhawan  6769
159       DA Warner  6567
311        KL Rahul  5828
597        SK Raina  5536
409        MS Dhoni  5439
52        AM Rahane  5367
31   AB de Villiers  5181
627       SV Samson  5181

In [48]:
fig = px.bar(
    batter_runs.head(10),
    x="Runs",
    y="batter",
    orientation="h",
    text="Runs",
    color="Runs",
    title="Top 10 Run Scorers in IPL"
)

fig.update_layout(
    xaxis_title="Runs",
    yaxis_title="Batter"
)

fig.show()

##### <b>💡 Business Insight</b>

Batters with high run totals generally demonstrate:

- Longevity
- Consistency
- Regular team selection
- Ability to perform across multiple seasons

However, total runs alone do not indicate batting efficiency. Strike rate and average should also be considered.

#### <b>🔴 Balls Faced</b>

##### Business Question

How many legal deliveries has each batter faced?

Balls faced is a fundamental metric used to calculate strike rate and understand batting workload.

In [49]:
balls_faced = (
    deliveries_df[
        deliveries_df["is_legal_delivery"] == True
    ]
    .groupby("batter", as_index=False)
    .size()
)

balls_faced.rename(
    columns={"size": "Balls Faced"},
    inplace=True
)

balls_faced.head()

           batter  Balls Faced
0  A Ashish Reddy          193
1        A Badoni          834
2      A Chandila            7
3        A Chopra           71
4     A Choudhary           20

#### <b>⚡ Strike Rate</b>

##### Business Question

Which batters score runs most quickly?

Strike Rate measures the number of runs scored per 100 legal deliveries.

In [50]:
strike_rate = batter_runs.merge(
    balls_faced,
    on="batter"
)

strike_rate["Strike Rate"] = (
    strike_rate["Runs"]
    /
    strike_rate["Balls Faced"]
    * 100
).round(2)

strike_rate.sort_values(
    "Strike Rate",
    ascending=False,
    inplace=True
)

strike_rate.head(10)

              batter  Runs  Balls Faced  Strike Rate
559       Auqib Nabi    14            3       466.67
606       KT Maphaka     8            2       400.00
598           L Wood     9            3       300.00
642       B Stanlake     5            2       250.00
108    V Suryavanshi  1028          447       229.98
193         FH Allen   349          163       214.11
432         Umar Gul    39           19       205.26
248      Urvil Patel   197           96       205.21
182  J Fraser-McGurk   385          191       201.57
654         SR Dubey     4            2       200.00

> **Important:** Batters with very few balls faced can have extremely high strike rates that are not representative of sustained performance. In professional analysis, a minimum balls-faced threshold (e.g., 200 or 500 balls) is often applied before comparing strike rates.

In [51]:
qualified_sr = strike_rate[
    strike_rate["Balls Faced"] >= 500
]

qualified_sr.head(10)

              batter  Runs  Balls Faced  Strike Rate
99          TH David  1151          642       179.28
39        AD Russell  2655         1508       176.06
92           PD Salt  1258          715       175.94
48   Abhishek Sharma  2379         1383       172.02
80           TM Head  1556          907       171.55
56         H Klaasen  2104         1253       167.92
68         SP Narine  1820         1099       165.61
77        RM Patidar  1612          978       164.83
42          N Pooran  2527         1538       164.30
120   Shashank Singh   905          560       161.61

In [52]:
fig = px.bar(
    qualified_sr.head(10),
    x="Strike Rate",
    y="batter",
    orientation="h",
    color="Strike Rate",
    text="Strike Rate",
    title="Top Strike Rates (Minimum 500 Balls Faced)"
)

fig.show()

##### <b>💡 Business Insight</b>

A high strike rate indicates a batter's ability to score quickly, making such players particularly valuable during powerplays and death overs. Applying a minimum balls-faced criterion ensures that comparisons are statistically meaningful.

#### <b>4️⃣ Most Fours</b>

##### Business Question

Which batters rely most on ground strokes to accumulate runs?

In [53]:
most_fours = (
    deliveries_df[
        deliveries_df["is_four"] == True
    ]
    .groupby("batter", as_index=False)
    .size()
)

most_fours.rename(
    columns={"size": "Fours"},
    inplace=True
)

most_fours.sort_values(
    "Fours",
    ascending=False,
    inplace=True
)

most_fours.head(10)

         batter  Fours
555     V Kohli    847
454    S Dhawan    768
128   DA Warner    663
424   RG Sharma    661
45    AM Rahane    540
253    KL Rahul    509
479    SK Raina    506
169   G Gambhir    492
467    SA Yadav    482
442  RV Uthappa    481

In [54]:
fig = px.bar(
    most_fours.head(10),
    x="Fours",
    y="batter",
    orientation="h",
    color="Fours",
    text="Fours",
    title="Top Boundary Hitters (Fours)"
)

fig.show()

##### <b>💡 Business Insight</b>

Batters with a high number of fours typically excel at timing and placement rather than relying solely on power hitting.

#### <b>6️⃣Most Sixes</b>

##### Business Question

Which batters are the biggest power hitters in IPL history?

In [55]:
most_sixes = (
    deliveries_df[
        deliveries_df["is_six"] == True
    ]
    .groupby("batter", as_index=False)
    .size()
)

most_sixes.rename(
    columns={"size": "Sixes"},
    inplace=True
)

most_sixes.sort_values(
    "Sixes",
    ascending=False,
    inplace=True
)

most_sixes.head(10)

             batter  Sixes
93         CH Gayle    359
353       RG Sharma    324
466         V Kohli    317
275        MS Dhoni    264
16   AB de Villiers    253
420       SV Samson    243
209        KL Rahul    239
108       DA Warner    236
200      KA Pollard    224
25       AD Russell    223

In [56]:
fig = px.bar(
    most_sixes.head(10),
    x="Sixes",
    y="batter",
    orientation="h",
    color="Sixes",
    text="Sixes",
    title="Top Six Hitters in IPL"
)

fig.show()

##### <b>💡 Business Insight</b>

Power hitters capable of clearing the boundary consistently are especially valuable during the final overs of an innings, where maximizing scoring opportunities is crucial.

#### <b>0️⃣ Dot Ball Percentage</b>

##### Business Question

Which batters consume the highest percentage of dot balls?

Dot Ball Percentage measures how often a batter fails to score from a legal delivery.

A lower dot ball percentage generally indicates better strike rotation and pressure management.

In [57]:
legal_deliveries = deliveries_df[
    deliveries_df["is_legal_delivery"] == True
]

In [58]:
dot_balls = (
    legal_deliveries[
        legal_deliveries["batter_runs"] == 0
    ]
    .groupby("batter")
    .size()
    .reset_index(name="Dot Balls")
)

dot_balls.head()

           batter  Dot Balls
0  A Ashish Reddy         58
1        A Badoni        265
2      A Chandila          3
3        A Chopra         41
4     A Choudhary          4

In [59]:
dot_ball_percentage = (
    balls_faced
    .merge(dot_balls, on="batter", how="left")
)

dot_ball_percentage["Dot Balls"] = (
    dot_ball_percentage["Dot Balls"]
    .fillna(0)
)

In [60]:
dot_ball_percentage["Dot Ball %"] = (
    dot_ball_percentage["Dot Balls"]
    /
    dot_ball_percentage["Balls Faced"]
    *100
).round(2)

dot_ball_percentage.head()

           batter  Balls Faced  Dot Balls  Dot Ball %
0  A Ashish Reddy          193       58.0       30.05
1        A Badoni          834      265.0       31.77
2      A Chandila            7        3.0       42.86
3        A Chopra           71       41.0       57.75
4     A Choudhary           20        4.0       20.00

In [61]:
qualified_dot = dot_ball_percentage[
    dot_ball_percentage["Balls Faced"] >= 500
]

qualified_dot = qualified_dot.sort_values(
    "Dot Ball %",
    ascending=True
)

fig = px.bar(
    qualified_dot.head(10),
    x="Dot Ball %",
    y="batter",
    orientation="h",
    color="Dot Ball %",
    text="Dot Ball %",
    title="Lowest Dot Ball Percentage (Minimum 500 Balls)"
)

fig.show()

##### <b>💡 Business Insight</b>

Batters with lower dot-ball percentages are generally better at rotating the strike.

These players:

- Keep the scoreboard moving
- Reduce pressure
- Build partnerships
- Force bowlers to change their plans

#### <b>💥 Boundary Percentage</b>

##### Business Question

Which batters score the highest proportion of their runs through boundaries?

Boundary Percentage indicates how aggressively a batter scores.

In [62]:
boundaries = (
    legal_deliveries[
        legal_deliveries["is_boundary"] == True
    ]
    .groupby("batter")
    .size()
    .reset_index(name="Boundary Balls")
)

boundaries.head()

           batter  Boundary Balls
0  A Ashish Reddy              31
1        A Badoni             143
2        A Chopra               7
3     A Choudhary               2
4      A Flintoff               7

In [63]:
boundary_percentage = (
    balls_faced
    .merge(boundaries, on="batter", how="left")
)

boundary_percentage["Boundary Balls"] = (
    boundary_percentage["Boundary Balls"]
    .fillna(0)
)

In [64]:
boundary_percentage["Boundary %"] = (
    boundary_percentage["Boundary Balls"]
    /
    boundary_percentage["Balls Faced"]
    *100
).round(2)

boundary_percentage.head()

           batter  Balls Faced  Boundary Balls  Boundary %
0  A Ashish Reddy          193            31.0       16.06
1        A Badoni          834           143.0       17.15
2      A Chandila            7             0.0        0.00
3        A Chopra           71             7.0        9.86
4     A Choudhary           20             2.0       10.00

In [65]:
qualified_boundary = boundary_percentage[
    boundary_percentage["Balls Faced"] >= 500
]

qualified_boundary = qualified_boundary.sort_values(
    "Boundary %",
    ascending=False
)

fig = px.bar(
    qualified_boundary.head(10),
    x="Boundary %",
    y="batter",
    orientation="h",
    color="Boundary %",
    text="Boundary %",
    title="Highest Boundary Percentage"
)

fig.show()

##### <b>💡 Business Insight</b>

A high boundary percentage suggests an aggressive batting style.

However, aggression should be interpreted alongside consistency and strike rotation to assess overall batting quality.

#### <b>🏃 Run Distribution</b>

##### Business Question

How does each batter accumulate runs?

Do they rely on:

- Singles?
- Doubles?
- Triples?
- Boundaries?

In [66]:
run_distribution = (
    legal_deliveries
    .groupby(
        ["batter", "batter_runs"]
    )
    .size()
    .unstack(fill_value=0)
)

run_distribution.head()

batter_runs       0    1   2  3   4  5   6
batter
A Ashish Reddy   58   83  20  1  16  0  15
A Badoni        265  346  75  5  96  0  47
A Chandila        3    4   0  0   0  0   0
A Chopra         41   21   2  0   7  0   0
A Choudhary       4   13   1  0   1  0   1

In [67]:
run_distribution.columns = [
    f"{col}_Run" for col in run_distribution.columns
]

run_distribution.reset_index(inplace=True)

run_distribution.head()

           batter  0_Run  1_Run  2_Run  3_Run  4_Run  5_Run  6_Run
0  A Ashish Reddy     58     83     20      1     16      0     15
1        A Badoni    265    346     75      5     96      0     47
2      A Chandila      3      4      0      0      0      0      0
3        A Chopra     41     21      2      0      7      0      0
4     A Choudhary      4     13      1      0      1      0      1

In [68]:
# player = "MS Dhoni"
player = input("Enter the player name: ")


player_name = (
    legal_deliveries[
        legal_deliveries["batter"] == player
    ]["batter_runs"]
    .value_counts()
    .sort_index()
    .reset_index()
)

player_name.columns = [
    "Runs",
    "Count"
]

fig = px.bar(
    player_name,
    x="Runs",
    y="Count",
    color="Runs",
    title=f"Run Distribution - {player}"
)

fig.show()

##### <b>💡 Business Insight</b>

Run distribution highlights a batter's scoring style.

Some batters rely on:

- Continuous strike rotation
- Frequent boundaries
- Power hitting

This helps franchises identify players suited to different batting roles.

#### <b>📈 Batting Average</b>

##### Business Question

Which batters score the most runs before getting dismissed?

Batting Average is calculated as:

Average = Total Runs ÷ Number of Times Out

Not-out innings are excluded from the denominator.

In [69]:
dismissals = (
    legal_deliveries[
        legal_deliveries["player_dismissed"] ==
        legal_deliveries["batter"]
    ]
    .groupby("batter")
    .size()
    .reset_index(name="Dismissals")
)

dismissals.head()

           batter  Dismissals
0  A Ashish Reddy          15
1        A Badoni          45
2        A Chopra           5
3     A Choudhary           1
4      A Flintoff           2

In [70]:
batting_average = (
    batter_runs
    .merge(dismissals, on="batter", how="left")
)

batting_average["Dismissals"] = (
    batting_average["Dismissals"]
    .fillna(0)
)

In [71]:
batting_average = batting_average[
    batting_average["Dismissals"] > 0
]

In [72]:
batting_average["Average"] = (
    batting_average["Runs"]
    /
    batting_average["Dismissals"]
).round(2)

batting_average.sort_values(
    "Average",
    ascending=False,
    inplace=True
)

batting_average.head(10)

              batter  Runs  Dismissals  Average
349    Iqbal Abdulla    88         1.0    88.00
378   Vivrant Sharma    69         1.0    69.00
273       MN van Wyk   167         3.0    55.67
244   PD Collingwood   203         4.0    50.75
43   B Sai Sudharsan  2515        51.0    49.31
113         T Stubbs   986        21.0    46.95
4           KL Rahul  5828       125.0    46.62
261         AC Voges   181         4.0    45.25
347          PR Veer    90         2.0    45.00
104        DP Conway  1080        24.0    45.00

> **Important:** Similar to strike rate, batting averages can be misleading for players with very few dismissals. In professional analysis, analysts often apply a minimum qualification (e.g., 500 balls faced or 20 innings) before ranking players.

In [73]:
qualified_average = batting_average.merge(
    balls_faced,
    on="batter"
)

qualified_average = qualified_average[
    qualified_average["Balls Faced"] >= 500
]

qualified_average = qualified_average.sort_values(
    "Average",
    ascending=False
)

fig = px.bar(
    qualified_average.head(10),
    x="Average",
    y="batter",
    orientation="h",
    color="Average",
    text="Average",
    title="Highest Batting Average (Minimum 500 Balls)"
)

fig.show()

##### 💡 Business Insight

Batting average reflects a player's ability to remain at the crease while scoring runs.

Players with consistently high averages often play anchor roles and contribute to building stable innings.

#### <b>🎯 30+, 50+, and 100+ Scores</b>

##### Business Question

How frequently does a batter convert starts into significant scores?

This analysis measures batting consistency by counting:

- 30+ scores
- Half-centuries (50+)
- Centuries (100+)

Players who consistently convert starts into big innings are valuable assets for any franchise.

In [74]:
match_runs = (
    deliveries_df
    .groupby(["match_id", "batter"], as_index=False)["batter_runs"]
    .sum()
)

match_runs.rename(
    columns={"batter_runs": "Runs"},
    inplace=True
)

match_runs.head()

   match_id       batter  Runs
0    335982    AA Noffke     9
1    335982      B Akhil     0
2    335982  BB McCullum   158
3    335982     CL White     6
4    335982    DJ Hussey    12

In [75]:
score_summary = (
    match_runs
    .groupby("batter")
    .agg(
        Matches=("match_id", "count"),
        ThirtyPlus=("Runs", lambda x: (x >= 30).sum()),
        FiftyPlus=("Runs", lambda x: (x >= 50).sum()),
        Hundreds=("Runs", lambda x: (x >= 100).sum())
    )
    .reset_index()
)

score_summary.head()

           batter  Matches  ThirtyPlus  FiftyPlus  Hundreds
0  A Ashish Reddy       23           2          0         0
1        A Badoni       56          16          7         0
2      A Chandila        2           0          0         0
3        A Chopra        6           0          0         0
4     A Choudhary        3           0          0         0

In [76]:
fig = px.bar(
    score_summary.sort_values("FiftyPlus", ascending=False).head(10),
    x="FiftyPlus",
    y="batter",
    orientation="h",
    color="FiftyPlus",
    text="FiftyPlus",
    title="Top Batters by Half-Centuries"
)

fig.show()

In [77]:
fig = px.bar(
    score_summary.sort_values("Hundreds", ascending=False).head(10),
    x="Hundreds",
    y="batter",
    orientation="h",
    color="Hundreds",
    text="Hundreds",
    title="Top Batters by Centuries"
)

fig.show()

##### <b>💡 Business Insight</b>

Scoring consistency is often more valuable than occasional explosive innings.

Batters who regularly score 30+ and 50+ runs provide greater stability to the batting lineup.

#### <b>🧢  Orange Cap Analysis</b>

##### Business Question

Who scored the most runs in each IPL season?

This identifies the Orange Cap winner (highest run scorer) for every season.

In [78]:
season_runs = (
    deliveries_df
    .groupby(["season", "batter"], as_index=False)["batter_runs"]
    .sum()
)

season_runs.rename(
    columns={"batter_runs": "Runs"},
    inplace=True
)

season_runs.head()

   season    batter  Runs
0    2008  A Chopra    42
1    2008  A Kumble    13
2    2008  A Mishra    37
3    2008  A Mukund     0
4    2008   A Nehra     3

In [79]:
orange_cap = (
    season_runs
    .sort_values(
        ["season", "Runs"],
        ascending=[True, False]
    )
    .groupby("season")
    .head(1)
)

orange_cap

      season           batter  Runs
115     2008         SE Marsh   616
229     2009        ML Hayden   572
446     2010     SR Tendulkar   618
502     2011         CH Gayle   608
684     2012         CH Gayle   733
910     2013       MEK Hussey   733
1088    2014       RV Uthappa   660
1148    2015        DA Warner   562
1383    2016          V Kohli   973
1422    2017        DA Warner   641
1594    2018    KS Williamson   735
1694    2019        DA Warner   692
1866    2020         KL Rahul   676
2051    2021       RD Gaikwad   635
2144    2022       JC Buttler   863
2423    2023     Shubman Gill   890
2606    2024          V Kohli   741
2640    2025  B Sai Sudharsan   759
2950    2026    V Suryavanshi   776

In [80]:
fig = px.bar(
    orange_cap,
    x="season",
    y="Runs",
    color="batter",
    text="Runs",
    title="Orange Cap Winners by Season"
)

fig.show()

##### <b>💡 Business Insight</b>

Orange Cap winners often become the backbone of their teams, consistently contributing high run totals throughout the tournament.

#### <b>📅 Season-wise Performance</b>

##### Business Question

How has a batter's performance changed over the years?

Tracking season-wise runs helps identify:

- Career growth
- Peak seasons
- Performance decline
- Consistency

In [81]:
# player = input("Enter the player name: ")
player = "V Kohli"
player_season = (
    deliveries_df[
        deliveries_df["batter"] == player
    ]
    .groupby("season", as_index=False)["batter_runs"]
    .sum()
)

player_season.rename(
    columns={"batter_runs": "Runs"},
    inplace=True
)

player_season

    season  Runs
0     2008   165
1     2009   246
2     2010   307
3     2011   557
4     2012   364
5     2013   639
6     2014   359
7     2015   505
8     2016   973
9     2017   308
10    2018   530
11    2019   464
12    2020   471
13    2021   405
14    2022   341
15    2023   639
16    2024   741
17    2025   657
18    2026   675

In [82]:
fig = px.line(
    player_season,
    x="season",
    y="Runs",
    markers=True,
    title=f"{player} - Season-wise Runs"
)

fig.show()

##### <b>💡 Business Insight</b>

Season-wise trends reveal whether a batter has maintained consistent performance or experienced fluctuations due to form, injuries, or role changes.

#### <b>⚔️ Batter Comparison</b>

##### Business Question

How do two batters compare across key performance metrics?

This comparison supports:

- Team selection
- Auction strategy
- Performance evaluation

In [83]:
batter_dashboard = (
    batter_runs
    .merge(balls_faced, on="batter")
    .merge(
        batting_average[["batter", "Average"]],
        on="batter",
        how="left"
    )
)

batter_dashboard["Strike Rate"] = (
    batter_dashboard["Runs"]
    /
    batter_dashboard["Balls Faced"]
    *100
).round(2)

batter_dashboard.head()

      batter  Runs  Balls Faced  Average  Strike Rate
0    V Kohli  9346         6911    40.81       135.23
1  RG Sharma  7331         5496    30.17       133.39
2   S Dhawan  6769         5304    36.39       127.62
3  DA Warner  6567         4680    41.56       140.32
4   KL Rahul  5828         4175    46.62       139.59

In [84]:
# player1 = input("Enter the first player name: ")
# player2 = input("Enter the second player name: ")
player1 = "V Kohli"
player2 = "DA Warner"

In [85]:
comparison = batter_dashboard[
    batter_dashboard["batter"].isin(
        [player1, player2]
    )
]

comparison

      batter  Runs  Balls Faced  Average  Strike Rate
0    V Kohli  9346         6911    40.81       135.23
3  DA Warner  6567         4680    41.56       140.32

In [86]:
metrics = ["Runs", "Average", "Strike Rate"]

comparison_long = comparison.melt(
    id_vars="batter",
    value_vars=metrics
)

fig = px.bar(
    comparison_long,
    x="variable",
    y="value",
    color="batter",
    barmode="group",
    title=f"{player1} vs {player2}"
)

fig.show()

##### <b>💡 Business Insight</b>

Comparing multiple metrics together provides a balanced evaluation.

For example:

- High Runs + High Average → Reliable anchor
- High Strike Rate + High Boundary % → Aggressive finisher
- Moderate Average + Low Dot Ball % → Excellent strike rotator

#### <b>⭐ Consistency Index</b>

##### Business Question

Which batters consistently contribute meaningful scores?

Consistency Index is calculated as:

Consistency Index = (30+ Scores ÷ Matches Played) × 100

This measures how often a batter makes a valuable contribution.

In [87]:
consistency = (
    score_summary[["batter", "Matches", "ThirtyPlus"]]
    .copy()
)

consistency["Consistency Index"] = (
    consistency["ThirtyPlus"]
    /
    consistency["Matches"]
    *100
).round(2)

consistency.sort_values(
    "Consistency Index",
    ascending=False,
    inplace=True
)

consistency.head(10)

              batter  Matches  ThirtyPlus  Consistency Index
712   Vivrant Sharma        1           1             100.00
633      Salil Arora        1           1             100.00
698    V Suryavanshi       23          16              69.57
10          A Mhatre       13           9              69.23
103  B Sai Sudharsan       57          38              66.67
402       MN van Wyk        5           3              60.00
347      LMP Simmons       29          17              58.62
182        DP Conway       28          16              57.14
284        JP Inglis       16           9              56.25
225        H Klaasen       60          33              55.00

In [88]:
fig = px.bar(
    consistency.head(10),
    x="Consistency Index",
    y="batter",
    orientation="h",
    color="Consistency Index",
    text="Consistency Index",
    title="Top 10 Most Consistent Batters"
)

fig.show()

##### <b>💡 Business Insight</b>

Consistency is one of the most important qualities in T20 cricket.

Players who regularly score 30+ runs reduce pressure on the middle order and improve a team's chances of posting or chasing competitive totals.

#### <b>📌 Batter Analytics Summary</b>

This notebook evaluated IPL batters using both traditional and advanced performance metrics.

##### Metrics Covered

##### Career Performance
- Total Runs
- Balls Faced
- Strike Rate
- Batting Average

##### Scoring Style
- Dot Ball Percentage
- Boundary Percentage
- Run Distribution
- Fours
- Sixes

##### Consistency
- 30+ Scores
- 50+ Scores
- 100+ Scores
- Consistency Index

##### Seasonal Analysis
- Orange Cap Winners
- Season-wise Runs
- Batter Comparison Dashboard

These analyses provide a comprehensive evaluation of batting performance and demonstrate how multiple metrics together offer a richer understanding than any single statistic alone.

### <b>Section 5 – Bowling Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook evaluates bowling performance using ball-by-ball IPL data.

The analysis focuses on:

- Wicket-taking ability
- Economy
- Bowling Strike Rate
- Bowling Average
- Dot Ball Percentage
- Phase-wise bowling
- Purple Cap race
- Bowling consistency

These metrics help franchises identify high-impact bowlers and optimize bowling strategies.

#### <b>🎯 Most Wickets</b>

##### Business Question

Which bowlers have taken the highest number of wickets in IPL history?

While wicket count is a key performance indicator, not all dismissals are credited to the bowler. For example, run-outs are excluded from a bowler's wicket tally.

In [89]:
bowler_wickets = (
    deliveries_df[
        deliveries_df["is_bowler_wicket"] == True
    ]
    .groupby("bowler", as_index=False)
    .size()
)

bowler_wickets.rename(
    columns={"size": "Wickets"},
    inplace=True
)

bowler_wickets.sort_values(
    "Wickets",
    ascending=False,
    inplace=True
)

bowler_wickets.head(10)

          bowler  Wickets
483    YS Chahal      233
65       B Kumar      226
409    SP Narine      209
321    PP Chawla      192
186    JJ Bumrah      190
331     R Ashwin      187
113     DJ Bravo      183
347    RA Jadeja      180
367  Rashid Khan      179
7       A Mishra      174

In [90]:
fig = px.bar(
    bowler_wickets.head(10),
    x="Wickets",
    y="bowler",
    orientation="h",
    color="Wickets",
    text="Wickets",
    title="Top 10 Wicket Takers in IPL History"
)

fig.update_layout(
    xaxis_title="Wickets",
    yaxis_title="Bowler"
)

fig.show()

##### <b>💡 Business Insight</b>

Bowlers with high wicket counts consistently break partnerships and create pressure on the opposition.

However, wickets alone do not measure overall effectiveness. Economy rate and strike rate must also be considered.

#### <b>💰 Runs Conceded</b>

##### Business Question

How many runs has each bowler conceded?

Runs conceded form the basis for calculating economy rate and bowling average.

In [91]:
bowler_runs = (
    deliveries_df
    .groupby("bowler", as_index=False)["total_runs"]
    .sum()
)

bowler_runs.rename(
    columns={"total_runs": "Runs Conceded"},
    inplace=True
)

bowler_runs.head()

           bowler  Runs Conceded
0  A Ashish Reddy            400
1        A Badoni             64
2      A Chandila            245
3     A Choudhary            144
4     A Dananjaya             47

#### <b>⚽ Balls Bowled</b>

##### Business Question

How many legal deliveries has each bowler bowled?

Only legal deliveries are considered when calculating overs, economy rate, and bowling strike rate.

In [92]:
balls_bowled = (
    deliveries_df[
        deliveries_df["is_legal_delivery"] == True
    ]
    .groupby("bowler", as_index=False)
    .size()
)

balls_bowled.rename(
    columns={"size": "Balls Bowled"},
    inplace=True
)

balls_bowled.head()

           bowler  Balls Bowled
0  A Ashish Reddy           262
1        A Badoni            41
2      A Chandila           234
3     A Choudhary           101
4     A Dananjaya            24

#### <b>🏏 Overs Bowled</b>

Overs bowled are calculated from legal deliveries.

Formula:

Overs = Balls Bowled ÷ 6

In [93]:
balls_bowled["Overs"] = (
    balls_bowled["Balls Bowled"] / 6
).round(1)

balls_bowled.head()

           bowler  Balls Bowled  Overs
0  A Ashish Reddy           262   43.7
1        A Badoni            41    6.8
2      A Chandila           234   39.0
3     A Choudhary           101   16.8
4     A Dananjaya            24    4.0

#### <b>📉 Economy Rate</b>

##### Business Question

Which bowlers concede the fewest runs per over?

Economy Rate = Runs Conceded ÷ Overs Bowled

This metric is particularly important in T20 cricket, where restricting runs is often as valuable as taking wickets.

In [94]:
economy = (
    bowler_runs
    .merge(
        balls_bowled[
            ["bowler", "Balls Bowled", "Overs"]
        ],
        on="bowler"
    )
)

economy["Economy"] = (
    economy["Runs Conceded"]
    /
    economy["Overs"]
).round(2)

economy.head()

           bowler  Runs Conceded  Balls Bowled  Overs  Economy
0  A Ashish Reddy            400           262   43.7     9.15
1        A Badoni             64            41    6.8     9.41
2      A Chandila            245           234   39.0     6.28
3     A Choudhary            144           101   16.8     8.57
4     A Dananjaya             47            24    4.0    11.75

> **Important:** Economy rate should only be compared among bowlers who have bowled a meaningful number of overs. Analysts often set a minimum qualification, such as 300 legal deliveries or 50 overs, to avoid misleading comparisons from small sample sizes.

In [95]:
qualified_economy = economy[
    economy["Balls Bowled"] >= 300
]

qualified_economy = qualified_economy.sort_values(
    "Economy"
)

qualified_economy.head(10)

               bowler  Runs Conceded  Balls Bowled  Overs  Economy
7            A Kumble           1089           965  160.8     6.77
161        GD McGrath            366           324   54.0     6.78
200           J Yadav            447           390   65.0     6.88
142        DL Vettori            894           777  129.5     6.90
285    M Muralitharan           1765          1528  254.7     6.93
480         SP Narine           5379          4660  776.7     6.93
409  RE van der Merwe            515           443   73.8     6.98
194           J Botha            818           694  115.7     7.07
151          DW Steyn           2583          2182  363.7     7.10
399          R Sharma           1100           928  154.7     7.11

In [96]:
fig = px.bar(
    qualified_economy.head(10),
    x="Economy",
    y="bowler",
    orientation="h",
    color="Economy",
    text="Economy",
    title="Best Economy Rate (Minimum 300 Balls Bowled)"
)

fig.show()

##### <b>💡 Business Insight</b>

Economical bowlers are invaluable in T20 cricket because they consistently apply pressure by limiting scoring opportunities. Even without taking many wickets, they can influence match outcomes by forcing batters into risky shots.

#### <b>📊 Bowling Average</b>

##### Business Question

Which bowlers concede the fewest runs for every wicket they take?

Bowling Average measures the number of runs conceded per wicket.

Formula:

Bowling Average = Runs Conceded ÷ Wickets

A lower bowling average generally indicates a more effective wicket-taking bowler.

In [97]:
bowling_average = (
    economy.merge(
        bowler_wickets,
        on="bowler",
        how="left"
    )
)

bowling_average["Wickets"] = (
    bowling_average["Wickets"]
    .fillna(0)
)

bowling_average = bowling_average[
    bowling_average["Wickets"] > 0
]

bowling_average["Bowling Average"] = (
    bowling_average["Runs Conceded"]
    /
    bowling_average["Wickets"]
).round(2)

bowling_average.head()

,bowler,Runs Conceded,Balls Bowled,Overs,Economy,Wickets,Bowling Average
0,A Ashish Reddy,400,262,43.7,9.15,18.0,22.22
1,A Badoni,64,41,6.8,9.41,4.0,16.00
2,A Chandila,245,234,39.0,6.28,11.0,22.27
3,A Choudhary,144,101,16.8,8.57,5.0,28.80
5,A Flintoff,106,66,11.0,9.64,2.0,53.00

In [98]:
qualified_average = bowling_average[
    bowling_average["Balls Bowled"] >= 300
].sort_values("Bowling Average")

In [99]:
fig = px.bar(
    qualified_average.head(10),
    x="Bowling Average",
    y="bowler",
    orientation="h",
    color="Bowling Average",
    text="Bowling Average",
    title="Best Bowling Average (Minimum 300 Balls)"
)

fig.show()

##### <b>💡 Business Insight</b>

Bowling average reflects how efficiently a bowler converts runs conceded into wickets.

Lower averages indicate bowlers who regularly dismiss batters without leaking excessive runs.

#### <b>⚡ Bowling Strike Rate</b>

##### Business Question

How frequently does a bowler take wickets?

Formula:

Strike Rate = Balls Bowled ÷ Wickets

Lower values indicate bowlers who take wickets more frequently.

In [100]:
bowling_sr = (
    bowling_average.copy()
)

bowling_sr["Bowling Strike Rate"] = (
    bowling_sr["Balls Bowled"]
    /
    bowling_sr["Wickets"]
).round(2)

bowling_sr.head()

,bowler,Runs Conceded,Balls Bowled,Overs,Economy,Wickets,Bowling Average,Bowling Strike Rate
0,A Ashish Reddy,400,262,43.7,9.15,18.0,22.22,14.56
1,A Badoni,64,41,6.8,9.41,4.0,16.00,10.25
2,A Chandila,245,234,39.0,6.28,11.0,22.27,21.27
3,A Choudhary,144,101,16.8,8.57,5.0,28.80,20.20
5,A Flintoff,106,66,11.0,9.64,2.0,53.00,33.00

In [101]:
qualified_sr = bowling_sr[
    bowling_sr["Balls Bowled"] >= 300
].sort_values("Bowling Strike Rate")

fig = px.bar(
    qualified_sr.head(10),
    x="Bowling Strike Rate",
    y="bowler",
    orientation="h",
    color="Bowling Strike Rate",
    text="Bowling Strike Rate",
    title="Best Bowling Strike Rate"
)

fig.show()

##### <b>💡 Business Insight</b>

Strike Rate measures wicket-taking frequency.

Bowlers with lower strike rates regularly break partnerships and prevent batters from settling.

#### <b>🎯 Dot Ball Percentage</b>

##### Business Question

Which bowlers create the most pressure by bowling dot balls?

Dot balls force batters into taking risks, increasing wicket opportunities.

In [102]:
dot_balls = (
    deliveries_df[
        (deliveries_df["is_legal_delivery"] == True)
        &
        (deliveries_df["total_runs"] == 0)
    ]
    .groupby("bowler")
    .size()
    .reset_index(name="Dot Balls")
)

dot_balls.head()

           bowler  Dot Balls
0  A Ashish Reddy         79
1        A Badoni          8
2      A Chandila        103
3     A Choudhary         42
4     A Dananjaya          6

In [103]:
bowling_dot = (
    balls_bowled.merge(
        dot_balls,
        on="bowler",
        how="left"
    )
)

bowling_dot["Dot Balls"] = (
    bowling_dot["Dot Balls"]
    .fillna(0)
)

bowling_dot["Dot Ball %"] = (
    bowling_dot["Dot Balls"]
    /
    bowling_dot["Balls Bowled"]
    *100
).round(2)

bowling_dot.head()

           bowler  Balls Bowled  Overs  Dot Balls  Dot Ball %
0  A Ashish Reddy           262   43.7       79.0       30.15
1        A Badoni            41    6.8        8.0       19.51
2      A Chandila           234   39.0      103.0       44.02
3     A Choudhary           101   16.8       42.0       41.58
4     A Dananjaya            24    4.0        6.0       25.00

In [104]:
qualified_dot = bowling_dot[
    bowling_dot["Balls Bowled"] >= 300
].sort_values("Dot Ball %", ascending=False)

fig = px.bar(
    qualified_dot.head(10),
    x="Dot Ball %",
    y="bowler",
    orientation="h",
    color="Dot Ball %",
    text="Dot Ball %",
    title="Highest Dot Ball Percentage"
)

fig.show()

##### <b>💡 Business Insight</b>

Dot-ball specialists build scoreboard pressure.

Even without taking wickets, they force batters into mistakes and support wicket-taking opportunities at the other end.

#### <b>💥 Boundary Concession Percentage</b>

##### Business Question

Which bowlers concede boundaries least frequently?

Boundary Percentage = Boundary Balls ÷ Balls Bowled × 100

Lower values indicate better control.

In [105]:
boundary_conceded = (
    deliveries_df[
        deliveries_df["is_boundary"] == True
    ]
    .groupby("bowler")
    .size()
    .reset_index(name="Boundary Balls")
)

boundary_conceded.head()

           bowler  Boundary Balls
0  A Ashish Reddy              46
1        A Badoni               6
2      A Chandila              27
3     A Choudhary              19
4     A Dananjaya               6

In [106]:
boundary_analysis = (
    balls_bowled.merge(
        boundary_conceded,
        on="bowler",
        how="left"
    )
)

boundary_analysis["Boundary Balls"] = (
    boundary_analysis["Boundary Balls"]
    .fillna(0)
)

boundary_analysis["Boundary %"] = (
    boundary_analysis["Boundary Balls"]
    /
    boundary_analysis["Balls Bowled"]
    *100
).round(2)

boundary_analysis.head()

           bowler  Balls Bowled  Overs  Boundary Balls  Boundary %
0  A Ashish Reddy           262   43.7            46.0       17.56
1        A Badoni            41    6.8             6.0       14.63
2      A Chandila           234   39.0            27.0       11.54
3     A Choudhary           101   16.8            19.0       18.81
4     A Dananjaya            24    4.0             6.0       25.00

In [107]:
qualified_boundary = boundary_analysis[
    boundary_analysis["Balls Bowled"] >= 300
].sort_values("Boundary %")

fig = px.bar(
    qualified_boundary.head(10),
    x="Boundary %",
    y="bowler",
    orientation="h",
    color="Boundary %",
    text="Boundary %",
    title="Lowest Boundary Percentage"
)

fig.show()

##### <b>💡 Business Insight</b>

Limiting boundaries is one of the strongest indicators of bowling control.

Bowlers with low boundary percentages consistently maintain pressure throughout their spells.

#### <b>🟣 Purple Cap Analysis</b>

##### Business Question

Which bowlers took the most wickets in each IPL season?

This identifies the Purple Cap winner for every season.

In [108]:
season_wickets = (
    deliveries_df[
        deliveries_df["is_bowler_wicket"] == True
    ]
    .groupby(
        ["season", "bowler"],
        as_index=False
    )
    .size()
)

season_wickets.rename(
    columns={"size": "Wickets"},
    inplace=True
)

season_wickets.head()

   season     bowler  Wickets
0    2008   A Kumble        7
1    2008   A Mishra       11
2    2008    A Nehra       12
3    2008      A Nel        1
4    2008  AA Noffke        1

In [109]:
purple_cap = (
    season_wickets
    .sort_values(
        ["season", "Wickets"],
        ascending=[True, False]
    )
    .groupby("season")
    .head(1)
)

purple_cap

      season             bowler  Wickets
75      2008      Sohail Tanvir       22
152     2009           RP Singh       23
241     2010            PP Ojha       21
367     2011         SL Malinga       28
437     2012           M Morkel       25
509     2013           DJ Bravo       32
638     2014          MM Sharma       23
694     2015           DJ Bravo       26
773     2016            B Kumar       23
860     2017            B Kumar       26
942     2018             AJ Tye       24
1048    2019        Imran Tahir       26
1141    2020           K Rabada       32
1211    2021           HV Patel       32
1378    2022          YS Chahal       27
1447    2023     Mohammed Shami       28
1515    2024           HV Patel       24
1646    2025  M Prasidh Krishna       25
1746    2026           K Rabada       29

In [110]:
fig = px.bar(
    purple_cap,
    x="season",
    y="Wickets",
    color="bowler",
    text="Wickets",
    title="Purple Cap Winners by Season"
)

fig.show()

##### <b>💡 Business Insight</b>

Purple Cap winners consistently deliver breakthroughs across an entire season.

They are often key contributors to their team's success and are valuable assets in player retention and auctions.

#### <b>🏏 Maiden Overs</b>

##### Business Question

Which bowlers have bowled the most maiden overs in IPL history?

A maiden over is an over in which no runs are conceded.

Although maiden overs are rare in T20 cricket, they significantly increase pressure on the batting team.

In [111]:
legal_deliveries = deliveries_df[
    deliveries_df["is_legal_delivery"] == True
].copy()

In [112]:
over_runs = (
    legal_deliveries
    .groupby(
        ["match_id", "innings", "over", "bowler"],
        as_index=False
    )["total_runs"]
    .sum()
)

over_runs.head()

   match_id  innings  over     bowler  total_runs
0    335982        1     0    P Kumar           2
1    335982        1     1     Z Khan          18
2    335982        1     2    P Kumar           6
3    335982        1     3  AA Noffke          18
4    335982        1     4    P Kumar          10

In [113]:
maidens = (
    over_runs[
        over_runs["total_runs"] == 0
    ]
    .groupby("bowler", as_index=False)
    .size()
)

maidens.rename(
    columns={"size": "Maiden Overs"},
    inplace=True
)

maidens.sort_values(
    "Maiden Overs",
    ascending=False,
    inplace=True
)

maidens.head(10)

          bowler  Maiden Overs
22       B Kumar            17
109      P Kumar            14
39      DW Steyn            10
165     TA Boult            10
148   SL Malinga             9
51     IK Pathan             9
38   DS Kulkarni             9
36     DL Chahar             8
56     JC Archer             7
168     UT Yadav             7

In [114]:
fig = px.bar(
    maidens.head(10),
    x="Maiden Overs",
    y="bowler",
    orientation="h",
    color="Maiden Overs",
    text="Maiden Overs",
    title="Most Maiden Overs in IPL"
)

fig.show()

##### <b>💡 Business Insight</b>

Maiden overs are extremely valuable in T20 cricket because they create scoreboard pressure and often lead to wickets in subsequent overs.

#### <b>⏱️ Bowling Performance Across Match Phases</b>

##### Business Question

How do bowlers perform during different phases of the innings?

Phases:

- Powerplay (Overs 1–6)
- Middle Overs (Overs 7–15)
- Death Overs (Overs 16–20)

Different phases demand different bowling skills and strategies.

In [115]:
phase_df = legal_deliveries.copy()

In [116]:
phase_df["Phase"] = np.select(
    [
        phase_df["over"] <= 6,
        phase_df["over"].between(7, 15),
        phase_df["over"] >= 16
    ],
    [
        "Powerplay",
        "Middle Overs",
        "Death Overs"
    ],
    default="Other"
)

In [117]:
phase_summary = (
    phase_df
    .groupby(["Phase", "bowler"])
    .agg(
        Balls=("ball", "count"),
        Runs=("total_runs", "sum"),
        Wickets=("is_bowler_wicket", "sum")
    )
    .reset_index()
)

phase_summary.head()

         Phase          bowler  Balls  Runs  Wickets
0  Death Overs  A Ashish Reddy     71   118        8
1  Death Overs        A Badoni     10    13        2
2  Death Overs      A Chandila      6     6        0
3  Death Overs     A Choudhary     24    37        1
4  Death Overs      A Flintoff     18    52        1

In [118]:
phase_summary["Overs"] = (
    phase_summary["Balls"] / 6
).round(2)

phase_summary["Economy"] = (
    phase_summary["Runs"]
    /
    phase_summary["Overs"]
).round(2)

phase_summary["Strike Rate"] = (
    phase_summary["Balls"]
    /
    phase_summary["Wickets"]
).replace(np.inf, np.nan).round(2)

phase_summary.head()

,Phase,bowler,Balls,Runs,Wickets,Overs,Economy,Strike Rate
0,Death Overs,A Ashish Reddy,71,118,8,11.83,9.97,8.88
1,Death Overs,A Badoni,10,13,2,1.67,7.78,5.00
2,Death Overs,A Chandila,6,6,0,1.00,6.00,NaN
3,Death Overs,A Choudhary,24,37,1,4.00,9.25,24.00
4,Death Overs,A Flintoff,18,52,1,3.00,17.33,18.00

In [119]:
fig = px.box(
    phase_summary,
    x="Phase",
    y="Economy",
    color="Phase",
    title="Economy Rate Across Match Phases"
)

fig.show()

##### <b>💡 Business Insight</b>

Powerplay specialists usually focus on early wickets.

Middle-over bowlers aim to control the scoring rate.

Death-over specialists balance wicket-taking with run prevention under high-pressure situations.

#### <b>🔥 Death Over Specialists</b>

##### Business Question

Which bowlers perform best during the final overs of an innings?

Death overs (16–20) are often the highest-scoring phase, making economical bowling especially valuable.

In [120]:
death_bowlers = (
    phase_summary[
        phase_summary["Phase"] == "Death Overs"
    ]
)

death_bowlers = death_bowlers[
    death_bowlers["Balls"] >= 120
]

death_bowlers.sort_values(
    "Economy",
    inplace=True
)

death_bowlers.head()

,Phase,bowler,Balls,Runs,Wickets,Overs,Economy,Strike Rate
105,Death Overs,DE Bollinger,210,261,21,35.00,7.46,10.00
390,Death Overs,SW Tait,126,161,12,21.00,7.67,10.50
372,Death Overs,SL Malinga,917,1188,90,152.83,7.77,10.19
379,Death Overs,SP Narine,769,1014,63,128.17,7.91,12.21
441,Death Overs,WD Parnell,189,252,15,31.50,8.00,12.60

In [121]:
fig = px.bar(
    death_bowlers.head(10),
    x="Economy",
    y="bowler",
    orientation="h",
    color="Economy",
    text="Economy",
    title="Best Death Over Bowlers"
)

fig.show()

##### <b>💡 Business Insight</b>

Death-over specialists are among the most valuable T20 bowlers because they consistently defend totals during the most challenging phase of an innings.

#### <b>📅 Season-wise Bowling Performance</b>

##### Business Question

How has a bowler performed across different IPL seasons?

Season-wise analysis helps identify:

- Career growth
- Peak seasons
- Consistency
- Declining performance

In [122]:
# player = input("Enter the player name: ")
player = "SL Malinga"

In [123]:
season_performance = (
    deliveries_df[
        deliveries_df["is_bowler_wicket"] == True
    ]
    .groupby(
        ["season", "bowler"],
        as_index=False
    )
    .size()
)

season_performance.rename(
    columns={"size": "Wickets"},
    inplace=True
)

player_stats = season_performance[
    season_performance["bowler"] == player
]

player_stats

      season      bowler  Wickets
163     2009  SL Malinga       18
266     2010  SL Malinga       15
367     2011  SL Malinga       28
468     2012  SL Malinga       22
575     2013  SL Malinga       20
665     2014  SL Malinga       16
747     2015  SL Malinga       24
920     2017  SL Malinga       11
1094    2019  SL Malinga       16

In [124]:
fig = px.line(
    player_stats,
    x="season",
    y="Wickets",
    markers=True,
    title=f"{player} - Season-wise Wickets"
)

fig.show()

##### <b>💡 Business Insight</b>

Season-wise analysis highlights a bowler's consistency and can reveal peak performance years, helping franchises make informed retention and auction decisions.

#### <b>⚔️ Bowler Comparison Dashboard</b>

##### Business Question

How do two bowlers compare across key bowling metrics?

Comparing multiple metrics together provides a more balanced evaluation than relying on a single statistic.

In [125]:
bowler_dashboard = (
    economy[
        [
            "bowler",
            "Runs Conceded",
            "Balls Bowled",
            "Economy"
        ]
    ]
    .merge(
        bowler_wickets,
        on="bowler",
        how="left"
    )
    .merge(
        bowling_average[
            ["bowler", "Bowling Average"]
        ],
        on="bowler",
        how="left"
    )
)

bowler_dashboard["Bowling Strike Rate"] = (
    bowler_dashboard["Balls Bowled"]
    /
    bowler_dashboard["Wickets"]
).round(2)

bowler_dashboard.head()

,bowler,Runs Conceded,Balls Bowled,Economy,Wickets,Bowling Average,Bowling Strike Rate
0,A Ashish Reddy,400,262,9.15,18.0,22.22,14.56
1,A Badoni,64,41,9.41,4.0,16.00,10.25
2,A Chandila,245,234,6.28,11.0,22.27,21.27
3,A Choudhary,144,101,8.57,5.0,28.80,20.20
4,A Dananjaya,47,24,11.75,NaN,NaN,NaN

In [126]:
# player1 = input("Enter the first player name: ")
# player2 = input("Enter the second player name: ")
player1 = "SL Malinga"
player2 = "JJ Bumrah"

comparison = bowler_dashboard[
    bowler_dashboard["bowler"].isin(
        [player1, player2]
    )
]

comparison

,bowler,Runs Conceded,Balls Bowled,Economy,Wickets,Bowling Average,Bowling Strike Rate
213,JJ Bumrah,4582,3653,7.53,190.0,24.12,19.23
472,SL Malinga,3486,2827,7.40,170.0,20.51,16.63

In [127]:
comparison_long = comparison.melt(
    id_vars="bowler",
    value_vars=[
        "Wickets",
        "Economy",
        "Bowling Average",
        "Bowling Strike Rate"
    ]
)

fig = px.bar(
    comparison_long,
    x="variable",
    y="value",
    color="bowler",
    barmode="group",
    title=f"{player1} vs {player2}"
)

fig.show()

##### <b>💡 Business Insight</b>

No single metric defines a great bowler.

For example:

- Low Economy → Excellent run control
- Low Bowling Average → Efficient wicket-taking
- Low Strike Rate → Frequent breakthroughs
- High Wickets → Long-term impact

A complete evaluation considers all these metrics together.

#### <b>📌 Bowling Analytics Summary</b>

This notebook provided a comprehensive evaluation of IPL bowlers using traditional and advanced metrics.

##### Performance Metrics
- Most Wickets
- Economy Rate
- Bowling Average
- Bowling Strike Rate

##### Pressure Metrics
- Dot Ball Percentage
- Boundary Concession Percentage
- Maiden Overs

##### Contextual Analysis
- Match Phase Performance
- Death Over Specialists
- Season-wise Performance
- Purple Cap Winners

##### Comparative Analysis
- Bowler Comparison Dashboard

These analyses demonstrate how different metrics complement each other to provide a complete picture of bowling performance in T20 cricket.

### <b>Section 6 – Fielding Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook evaluates fielding performance using ball-by-ball IPL data.

The analysis focuses on:

- Most catches
- Most run outs
- Most stumpings
- Fielding involvement
- Best fielders by season
- Player comparison dashboard

Fielding is often an underrated aspect of T20 cricket, but outstanding fielders save runs, create wicket opportunities, and influence match outcomes.

#### <b>🧤 Most Catches</b>

##### Business Question

Which fielders have taken the highest number of catches in IPL history?

Catches are one of the most common forms of dismissal and reflect a player's positioning, anticipation, and catching ability.

Only dismissals of type **caught** are included.

In [128]:
catches = (
    deliveries_df[
        deliveries_df["dismissal_kind"] == "caught"
    ]
    .groupby("fielder", as_index=False)
    .size()
)

catches.rename(
    columns={"size": "Catches"},
    inplace=True
)

catches.sort_values(
    "Catches",
    ascending=False,
    inplace=True
)

catches.head(10)

            fielder  Catches
368        MS Dhoni      158
274      KD Karthik      145
624         V Kohli      126
23   AB de Villiers      120
540        SK Raina      106
469       RA Jadeja      104
477       RG Sharma      101
510        S Dhawan      100
269      KA Pollard       97
646         WP Saha       93

In [129]:
fig = px.bar(
    catches.head(10),
    x="Catches",
    y="fielder",
    orientation="h",
    color="Catches",
    text="Catches",
    title="Top 10 Catch Takers in IPL"
)

fig.show()

##### <b>💡 Business Insight</b>

Reliable fielders reduce opposition scoring opportunities and convert difficult chances into wickets.

Teams often position their best catchers in high-impact fielding positions such as slips, long-on, long-off, and deep midwicket.

#### <b>🎯 Most Run Outs</b>

##### Business Question

Which fielders have been involved in the highest number of run-outs?

Run-outs often result from quick reflexes, accurate throws, and effective teamwork.

In [130]:
run_outs = (
    deliveries_df[
        deliveries_df["dismissal_kind"] == "run out"
    ]
    .groupby("fielder", as_index=False)
    .size()
)

run_outs.rename(
    columns={"size": "Run Outs"},
    inplace=True
)

run_outs.sort_values(
    "Run Outs",
    ascending=False,
    inplace=True
)

run_outs.head(10)

            fielder  Run Outs
169        MS Dhoni        27
218       RA Jadeja        20
302         V Kohli        18
270       SV Samson        18
120      KD Karthik        17
99     Ishan Kishan        14
251        SK Raina        13
161       MK Pandey        13
13   AB de Villiers        13
312         WP Saha        12

In [131]:
fig = px.bar(
    run_outs.head(10),
    x="Run Outs",
    y="fielder",
    orientation="h",
    color="Run Outs",
    text="Run Outs",
    title="Top Run Out Contributors"
)

fig.show()

##### <b>💡 Business Insight</b>

Players involved in many run-outs generally possess:

- Fast reactions
- Strong throwing arms
- Good anticipation
- Effective communication with teammates

#### <b>🥅 Most Stumpings</b>

##### Business Question

Which wicketkeepers have completed the most stumpings?

Stumpings demonstrate a wicketkeeper's speed, awareness, and coordination with spin bowlers.

In [132]:
stumpings = (
    deliveries_df[
        deliveries_df["dismissal_kind"] == "stumped"
    ]
    .groupby("fielder", as_index=False)
    .size()
)

stumpings.rename(
    columns={"size": "Stumpings"},
    inplace=True
)

stumpings.sort_values(
    "Stumpings",
    ascending=False,
    inplace=True
)

stumpings.head(10)

         fielder  Stumpings
27      MS Dhoni         47
19    KD Karthik         37
39    RV Uthappa         32
47       WP Saha         26
38       RR Pant         24
42     SV Samson         19
36     Q de Kock         17
34      PA Patel         16
2   AC Gilchrist         16
32       NV Ojha         10

In [133]:
fig = px.bar(
    stumpings.head(10),
    x="Stumpings",
    y="fielder",
    orientation="h",
    color="Stumpings",
    text="Stumpings",
    title="Top Wicketkeepers by Stumpings"
)

fig.show()

##### <b>💡 Business Insight</b>

Successful stumpings require exceptional coordination between the bowler and wicketkeeper.

Wicketkeepers with high stumping counts are often particularly effective against spin bowlers.

#### <b>⭐ Overall Fielding Involvement</b>

##### Business Question

Which players contribute the most through fielding?

A player's overall fielding contribution is measured by combining:

- Catches
- Run Outs
- Stumpings

In [134]:
fielding_summary = (
    catches
    .merge(run_outs, on="fielder", how="outer")
    .merge(stumpings, on="fielder", how="outer")
    .fillna(0)
)

fielding_summary["Total Involvement"] = (
    fielding_summary["Catches"] +
    fielding_summary["Run Outs"] +
    fielding_summary["Stumpings"]
)

fielding_summary.sort_values(
    "Total Involvement",
    ascending=False,
    inplace=True
)

fielding_summary.head(10)

            fielder  Catches  Run Outs  Stumpings  Total Involvement
370        MS Dhoni    158.0      27.0       47.0              232.0
275      KD Karthik    145.0      17.0       37.0              199.0
633         V Kohli    126.0      18.0        0.0              144.0
23   AB de Villiers    120.0      13.0        8.0              141.0
502      RV Uthappa     92.0       9.0       32.0              133.0
655         WP Saha     93.0      12.0       26.0              131.0
572       SV Samson     90.0      18.0       19.0              127.0
472       RA Jadeja    104.0      20.0        0.0              124.0
544        SK Raina    106.0      13.0        0.0              119.0
491         RR Pant     90.0       4.0       24.0              118.0

In [135]:
fig = px.bar(
    fielding_summary.head(10),
    x="Total Involvement",
    y="fielder",
    orientation="h",
    color="Total Involvement",
    text="Total Involvement",
    title="Top Overall Fielders"
)

fig.show()

##### <b>💡 Business Insight</b>

Evaluating multiple fielding contributions together provides a more balanced assessment than looking at catches alone.

Players with consistently high involvement are valuable defensive assets across different match situations.

#### <b>📅 Best Fielders by Season</b>

##### Business Question

Which fielders made the highest number of dismissals in each IPL season?

This analysis highlights season-wise defensive excellence.

In [136]:
season_fielding = (
    deliveries_df[
        deliveries_df["fielder"].notna()
    ]
    .groupby(
        ["season", "fielder"],
        as_index=False
    )
    .size()
)

season_fielding.rename(
    columns={"size": "Dismissal Involvement"},
    inplace=True
)

best_fielders = (
    season_fielding
    .sort_values(
        ["season", "Dismissal Involvement"],
        ascending=[True, False]
    )
    .groupby("season")
    .head(1)
)

best_fielders

      season         fielder  Dismissal Involvement
130     2008     YV Takawale                     13
143     2009    AC Gilchrist                     23
278     2010    AC Gilchrist                     14
468     2011   KC Sangakkara                     19
577     2012     BB McCullum                     18
792     2013        MS Dhoni                     19
869     2014       DA Miller                     14
1016    2015      KD Karthik                     21
1082    2016  AB de Villiers                     19
1247    2017      KA Pollard                     15
1376    2018      KD Karthik                     18
1529    2019         RR Pant                     24
1639    2020       Q de Kock                     22
1681    2021  AB de Villiers                     15
1940    2022       SV Samson                     19
2084    2023      RD Gaikwad                     17
2188    2024        KL Rahul                     17
2350    2025       JM Sharma                     20
2512    2026      JC Buttler                     27

In [137]:
fig = px.bar(
    best_fielders,
    x="season",
    y="Dismissal Involvement",
    color="fielder",
    text="Dismissal Involvement",
    title="Best Fielders by Season"
)

fig.show()

#### <b>📌 Fielding Analytics Summary</b>

This notebook evaluated IPL fielders using dismissal-based metrics.

##### Metrics Covered

- Most Catches
- Most Run Outs
- Most Stumpings
- Overall Fielding Involvement
- Season-wise Fielding Leaders

Fielding is an essential component of team performance, and these metrics help identify players who consistently contribute in the field.

### <b>Section 7 – Venue and Match Conditions Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook evaluates how venue and match conditions influence IPL results.

The analysis focuses on:

- Matches played at each venue
- Average first-innings score
- Highest first-innings totals
- Chasing versus defending success
- Toss impact by venue
- Highest successful run chases
- Team performance across venues
- Batter-friendly and bowler-friendly venues

Venue-level insights can support:

- Match strategy
- Playing-XI selection
- Toss decisions
- Auction planning
- Predictive modeling

#### <b>✅ Column Validation</b>

Before beginning venue analysis, the required columns are validated.

This helps prevent unexpected errors caused by missing or renamed fields in the processed datasets.

In [138]:
required_match_columns = [
    "match_id",
    "season",
    "venue",
    "team_1",
    "team_2",
    "toss_winner",
    "toss_decision",
    "winner"
]

required_delivery_columns = [
    "match_id",
    "innings",
    "batting_team",
    "total_runs"
]

missing_match_columns = [
    column
    for column in required_match_columns
    if column not in matches_df.columns
]

missing_delivery_columns = [
    column
    for column in required_delivery_columns
    if column not in deliveries_df.columns
]

print("Missing match columns:", missing_match_columns)
print("Missing delivery columns:", missing_delivery_columns)

Missing match columns: []
Missing delivery columns: []

#### <b>🏟️ Matches Played by Venue</b>

##### Business Question

Which venues have hosted the highest number of IPL matches?

Venue frequency helps identify:

- Major IPL grounds
- Frequently used home venues
- Locations with sufficient data for reliable comparison

In [139]:
venue_matches = (
    matches_df["venue"]
    .fillna("Unknown")
    .value_counts()
    .reset_index()
)

venue_matches.columns = [
    "Venue",
    "Matches"
]

venue_matches.head(10)

                                               Venue  Matches
0                           Wankhede Stadium, Mumbai      132
1                              Eden Gardens, Kolkata      107
2                   M Chinnaswamy Stadium, Bengaluru      104
3                        Arun Jaitley Stadium, Delhi      104
4           MA Chidambaram Stadium, Chepauk, Chennai       98
5  Rajiv Gandhi International Stadium, Uppal, Hyd...       90
6                     Sawai Mansingh Stadium, Jaipur       68
7  Punjab Cricket Association IS Bindra Stadium, ...       61
8                   Narendra Modi Stadium, Ahmedabad       53
9                Dubai International Cricket Stadium       46

In [140]:
fig = px.bar(
    venue_matches.head(15),
    x="Matches",
    y="Venue",
    orientation="h",
    text="Matches",
    color="Matches",
    title="Top IPL Venues by Matches Hosted"
)

fig.update_layout(
    xaxis_title="Number of Matches",
    yaxis_title="Venue",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Venues with a high number of matches provide larger and more reliable samples for performance analysis.

Smaller sample venues should be interpreted carefully because a few unusual matches can strongly influence their averages.

#### <b>📊 Innings-Level Dataset</b>

Ball-by-ball records are aggregated to create one row for every innings.

This dataset will be used to calculate:

- First-innings totals
- Second-innings totals
- Successful run chases
- Venue scoring averages

In [141]:
innings_summary = (
    deliveries_df
    .groupby(
        [
            "match_id",
            "innings",
            "batting_team"
        ],
        as_index=False
    )
    .agg(
        Innings_Runs=("total_runs", "sum")
    )
)

innings_summary.head()

   match_id  innings                 batting_team  Innings_Runs
0    335982        1        Kolkata Knight Riders           222
1    335982        2  Royal Challengers Bangalore            82
2    335983        1          Chennai Super Kings           240
3    335983        2              Kings XI Punjab           207
4    335984        1             Rajasthan Royals           129

In [142]:
innings_summary = innings_summary.merge(
    matches_df[
        [
            "match_id",
            "season",
            "venue",
            "winner",
            "team_1",
            "team_2"
        ]
    ],
    on="match_id",
    how="left"
)

innings_summary.head()

,match_id,innings,batting_team,Innings_Runs,season,venue,winner,team_1,team_2
0,335982,1,Kolkata Knight Riders,222,2008,"M Chinnaswamy Stadium, Bengaluru",Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders
1,335982,2,Royal Challengers Bangalore,82,2008,"M Chinnaswamy Stadium, Bengaluru",Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders
2,335983,1,Chennai Super Kings,240,2008,"Punjab Cricket Association IS Bindra Stadium, ...",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
3,335983,2,Kings XI Punjab,207,2008,"Punjab Cricket Association IS Bindra Stadium, ...",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
4,335984,1,Rajasthan Royals,129,2008,"Arun Jaitley Stadium, Delhi",Delhi Daredevils,Delhi Daredevils,Rajasthan Royals

#### <b>🏏 Average First-Innings Score</b>

##### Business Question

Which IPL venues produce the highest average first-innings totals?

A high average may indicate:

- Batter-friendly pitches
- Small boundaries
- Fast outfields
- Favourable weather conditions

A lower average may indicate more assistance for bowlers.

In [143]:
first_innings = innings_summary[
    innings_summary["innings"] == 1
].copy()

In [144]:
venue_first_innings = (
    first_innings
    .groupby("venue", as_index=False)
    .agg(
        Matches=("match_id", "nunique"),
        Average_First_Innings_Score=("Innings_Runs", "mean"),
        Highest_First_Innings_Score=("Innings_Runs", "max"),
        Lowest_First_Innings_Score=("Innings_Runs", "min")
    )
)

venue_first_innings[
    "Average_First_Innings_Score"
] = venue_first_innings[
    "Average_First_Innings_Score"
].round(2)

venue_first_innings.head()

,venue,Matches,Average_First_Innings_Score,Highest_First_Innings_Score,Lowest_First_Innings_Score
0,"Arun Jaitley Stadium, Delhi",104,171.76,278,56
1,Barabati Stadium,7,167.71,231,126
2,"Barsapara Cricket Stadium, Guwahati",8,168.88,201,127
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29,174.79,235,121
4,"Brabourne Stadium, Mumbai",27,178.52,217,68

In [145]:
qualified_venues = venue_first_innings[
    venue_first_innings["Matches"] >= 10
].copy()

In [146]:
highest_scoring_venues = qualified_venues.sort_values(
    "Average_First_Innings_Score",
    ascending=False
).head(10)

fig = px.bar(
    highest_scoring_venues,
    x="Average_First_Innings_Score",
    y="venue",
    orientation="h",
    color="Average_First_Innings_Score",
    text="Average_First_Innings_Score",
    title="Highest Average First-Innings Scores by Venue"
)

fig.update_layout(
    xaxis_title="Average First-Innings Score",
    yaxis_title="Venue",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Venues with higher first-innings averages generally favour aggressive batting and may require teams to target larger totals.

However, scoring conditions should also be evaluated alongside chase success and bowling performance.

#### <b>📈 First-Innings Score Distribution</b>

##### Business Question

What is the overall distribution of first-innings scores in IPL matches?

This analysis helps identify:

- Typical first-innings totals
- Low-scoring matches
- High-scoring matches
- Extreme match conditions

In [147]:
first_innings["Innings_Runs"].describe()

count    1243.000000
mean      168.569590
std        34.053296
min        25.000000
25%       148.000000
50%       168.000000
75%       190.000000
max       287.000000
Name: Innings_Runs, dtype: float64

In [148]:
fig = px.histogram(
    first_innings,
    x="Innings_Runs",
    nbins=30,
    marginal="box",
    title="Distribution of First-Innings Scores"
)

fig.update_layout(
    xaxis_title="First-Innings Score",
    yaxis_title="Number of Matches"
)

fig.show()

##### <B>💡 Business Insight</b>

The score distribution provides a benchmark for what constitutes a below-par, competitive, or above-par IPL total.

This benchmark can later be made venue-specific for match prediction and strategy.

#### <b>🔥 Highest First-Innings Totals</b>

##### Business Question

Which teams recorded the highest first-innings totals in IPL history?

These matches highlight exceptional batting performances and highly favourable scoring conditions.

In [149]:
highest_totals = (
    first_innings
    .sort_values(
        "Innings_Runs",
        ascending=False
    )
    [
        [
            "match_id",
            "season",
            "venue",
            "batting_team",
            "Innings_Runs",
            "winner"
        ]
    ]
    .head(10)
)

highest_totals

,match_id,season,venue,batting_team,Innings_Runs,winner
2133,1426268,2024,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,287,Sunrisers Hyderabad
2219,1473439,2025,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,286,Sunrisers Hyderabad
2349,1473505,2025,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,278,Sunrisers Hyderabad
2089,1422126,2024,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,277,Sunrisers Hyderabad
2105,1422134,2024,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Kolkata Knight Riders,272,Kolkata Knight Riders
2143,1426273,2024,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,266,Sunrisers Hyderabad
2432,1529278,2026,"Arun Jaitley Stadium, Delhi",Delhi Capitals,264,Punjab Kings
709,598027,2013,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore,263,Royal Challengers Bangalore
2157,1426280,2024,"Eden Gardens, Kolkata",Kolkata Knight Riders,261,Punjab Kings
2159,1426281,2024,"Arun Jaitley Stadium, Delhi",Delhi Capitals,257,Delhi Capitals

In [150]:
fig = px.bar(
    highest_totals,
    x="Innings_Runs",
    y="batting_team",
    orientation="h",
    color="venue",
    text="Innings_Runs",
    hover_data=[
        "season",
        "winner"
    ],
    title="Highest First-Innings Totals"
)

fig.update_layout(
    xaxis_title="First-Innings Score",
    yaxis_title="Batting Team",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

#### <b>🏃 Chasing Versus Defending Success</b>

##### Business Question

Do IPL teams win more frequently while chasing or while defending a target?

A match is classified as:

- `Chasing Win` when the second-innings batting team wins
- `Defending Win` when the first-innings batting team wins
- `No Result / Tie` when no standard winner is available

In [151]:
first_team = (
    innings_summary[
        innings_summary["innings"] == 1
    ][
        [
            "match_id",
            "batting_team",
            "Innings_Runs"
        ]
    ]
    .rename(
        columns={
            "batting_team": "First_Innings_Team",
            "Innings_Runs": "First_Innings_Runs"
        }
    )
)

second_team = (
    innings_summary[
        innings_summary["innings"] == 2
    ][
        [
            "match_id",
            "batting_team",
            "Innings_Runs"
        ]
    ]
    .rename(
        columns={
            "batting_team": "Second_Innings_Team",
            "Innings_Runs": "Second_Innings_Runs"
        }
    )
)

In [152]:
match_result_context = (
    matches_df[
        [
            "match_id",
            "season",
            "venue",
            "winner",
            "toss_winner",
            "toss_decision"
        ]
    ]
    .merge(
        first_team,
        on="match_id",
        how="left"
    )
    .merge(
        second_team,
        on="match_id",
        how="left"
    )
)

match_result_context.head()

,match_id,season,venue,winner,toss_winner,toss_decision,First_Innings_Team,First_Innings_Runs,Second_Innings_Team,Second_Innings_Runs
0,1082591,2017,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,Royal Challengers Bangalore,field,Sunrisers Hyderabad,207,Royal Challengers Bangalore,172.0
1,1082592,2017,"Maharashtra Cricket Association Stadium, Pune",Rising Pune Supergiants,Rising Pune Supergiants,field,Mumbai Indians,184,Rising Pune Supergiants,187.0
2,1082593,2017,Saurashtra Cricket Association Stadium,Kolkata Knight Riders,Kolkata Knight Riders,field,Gujarat Lions,183,Kolkata Knight Riders,184.0
3,1082594,2017,Holkar Cricket Stadium,Kings XI Punjab,Kings XI Punjab,field,Rising Pune Supergiants,163,Kings XI Punjab,164.0
4,1082595,2017,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,157,Delhi Daredevils,142.0

In [153]:
conditions = [
    (
        match_result_context["winner"]
        ==
        match_result_context["Second_Innings_Team"]
    ),
    (
        match_result_context["winner"]
        ==
        match_result_context["First_Innings_Team"]
    )
]

choices = [
    "Chasing Win",
    "Defending Win"
]

match_result_context["Winning_Method"] = np.select(
    conditions,
    choices,
    default="No Result / Tie"
)

In [154]:
winning_method_summary = (
    match_result_context["Winning_Method"]
    .value_counts()
    .reset_index()
)

winning_method_summary.columns = [
    "Winning Method",
    "Matches"
]

winning_method_summary

    Winning Method  Matches
0      Chasing Win      666
1    Defending Win      552
2  No Result / Tie       25

In [155]:
fig = px.pie(
    winning_method_summary,
    names="Winning Method",
    values="Matches",
    hole=0.4,
    title="Chasing Versus Defending Success"
)

fig.show()

##### <b>💡 Business Insight</b>

The chasing-versus-defending split indicates whether batting second provides a general advantage.

Possible explanations include:

- Dew
- Improved knowledge of the target
- Changing pitch conditions
- Pressure while defending

#### <b>🏟️ Chasing Success by Venue</b>

##### Business Question

At which venues is chasing most successful?

Venue-specific chase success can guide toss decisions and match strategy.

In [156]:
venue_results = (
    match_result_context[
        match_result_context["Winning_Method"].isin(
            [
                "Chasing Win",
                "Defending Win"
            ]
        )
    ]
    .groupby(
        [
            "venue",
            "Winning_Method"
        ]
    )
    .size()
    .unstack(fill_value=0)
    .reset_index()
)

venue_results.head()

Winning_Method,venue,Chasing Win,Defending Win
0,"Arun Jaitley Stadium, Delhi",54,47
1,Barabati Stadium,3,4
2,"Barsapara Cricket Stadium, Guwahati",4,4
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,16,11
4,"Brabourne Stadium, Mumbai",13,14

In [157]:
if "Chasing Win" not in venue_results.columns:
    venue_results["Chasing Win"] = 0

if "Defending Win" not in venue_results.columns:
    venue_results["Defending Win"] = 0

venue_results["Completed Matches"] = (
    venue_results["Chasing Win"]
    +
    venue_results["Defending Win"]
)

venue_results["Chasing Win %"] = (
    venue_results["Chasing Win"]
    /
    venue_results["Completed Matches"]
    * 100
).round(2)

In [158]:
qualified_venue_results = venue_results[
    venue_results["Completed Matches"] >= 10
].sort_values(
    "Chasing Win %",
    ascending=False
)

qualified_venue_results.head(10)

Winning_Method,venue,Chasing Win,Defending Win,Completed Matches,Chasing Win %
34,SuperSport Park,8,4,12,66.67
28,"Sawai Mansingh Stadium, Jaipur",44,24,68,64.71
30,Sharjah Cricket Stadium,18,10,28,64.29
31,Sheikh Zayed Stadium,16,11,27,59.26
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,16,11,27,59.26
10,"Eden Gardens, Kolkata",60,45,105,57.14
16,"M Chinnaswamy Stadium, Bengaluru",56,44,100,56.00
25,"Punjab Cricket Association IS Bindra Stadium, ...",34,27,61,55.74
36,"Wankhede Stadium, Mumbai",72,59,131,54.96
26,"Rajiv Gandhi International Stadium, Uppal, Hyd...",48,40,88,54.55

In [159]:
fig = px.bar(
    qualified_venue_results.head(10),
    x="Chasing Win %",
    y="venue",
    orientation="h",
    color="Chasing Win %",
    text="Chasing Win %",
    title="Venues with Highest Chasing Win Percentage"
)

fig.update_layout(
    xaxis_title="Chasing Win Percentage",
    yaxis_title="Venue",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

A high chasing-win percentage may indicate that batting conditions improve later in the match or that dew makes bowling more difficult.

Teams may prefer to field first at such venues after winning the toss.

#### <b>🪙 Toss Impact by Venue</b>

##### Business Question

At which venues does winning the toss provide the greatest match-winning advantage?

Toss impact can vary because of:

- Dew
- Pitch deterioration
- Day-night conditions
- Boundary dimensions
- Chasing difficulty

In [160]:
match_result_context["Toss_Winner_Won"] = (
    match_result_context["toss_winner"]
    ==
    match_result_context["winner"]
)

In [161]:
toss_impact_venue = (
    match_result_context
    .groupby("venue", as_index=False)
    .agg(
        Matches=("match_id", "nunique"),
        Toss_Winner_Match_Wins=("Toss_Winner_Won", "sum")
    )
)

toss_impact_venue["Toss Winner Win %"] = (
    toss_impact_venue["Toss_Winner_Match_Wins"]
    /
    toss_impact_venue["Matches"]
    * 100
).round(2)

In [162]:
qualified_toss_venues = toss_impact_venue[
    toss_impact_venue["Matches"] >= 10
].sort_values(
    "Toss Winner Win %",
    ascending=False
)

qualified_toss_venues.head(10)

,venue,Matches,Toss_Winner_Match_Wins,Toss Winner Win %
34,SuperSport Park,12,8,66.67
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29,18,62.07
15,Kingsmead,15,9,60.00
18,Maharaja Yadavindra Singh International Cricke...,17,10,58.82
30,Sharjah Cricket Stadium,28,16,57.14
33,Subrata Roy Sahara Stadium,16,9,56.25
28,"Sawai Mansingh Stadium, Jaipur",68,38,55.88
19,"Maharashtra Cricket Association Stadium, Pune",35,19,54.29
7,"Dr DY Patil Sports Academy, Mumbai",37,20,54.05
8,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,17,9,52.94

In [163]:
fig = px.bar(
    qualified_toss_venues.head(10),
    x="Toss Winner Win %",
    y="venue",
    orientation="h",
    color="Toss Winner Win %",
    text="Toss Winner Win %",
    title="Venues Where Toss Winners Win Most Often"
)

fig.update_layout(
    xaxis_title="Toss Winner Match Win Percentage",
    yaxis_title="Venue",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

A high toss-winner success percentage suggests that match conditions make the toss strategically important.

However, toss impact does not automatically prove causation because stronger teams may also win both the toss and the match.

#### <b>🎯 Toss Decision Success</b>

##### Business Question

Which toss decision has produced better results: batting first or fielding first?

This evaluates whether toss-winning captains made successful decisions.

In [164]:
toss_decision_success = (
    match_result_context
    .groupby("toss_decision")
    .agg(
        Matches=("match_id", "nunique"),
        Wins_After_Toss=("Toss_Winner_Won", "sum")
    )
    .reset_index()
)

toss_decision_success["Success %"] = (
    toss_decision_success["Wins_After_Toss"]
    /
    toss_decision_success["Matches"]
    * 100
).round(2)

toss_decision_success

  toss_decision  Matches  Wins_After_Toss  Success %
0           bat      418              185      44.26
1         field      825              443      53.70

In [165]:
fig = px.bar(
    toss_decision_success,
    x="toss_decision",
    y="Success %",
    color="toss_decision",
    text="Success %",
    title="Success Rate by Toss Decision"
)

fig.update_layout(
    xaxis_title="Toss Decision",
    yaxis_title="Match Win Percentage"
)

fig.show()

#### <b>🔥 Highest Successful Run Chases</b>

##### Business Question

Which teams successfully chased the highest targets in IPL history?

Successful high chases demonstrate:

- Batting depth
- Pressure-handling ability
- Strong finishing
- Favourable match conditions

In [166]:
successful_chases = match_result_context[
    match_result_context["Winning_Method"] == "Chasing Win"
].copy()

In [167]:
successful_chases["Target"] = (
    successful_chases["First_Innings_Runs"] + 1
)

successful_chases["Runs_Chased"] = (
    successful_chases["Second_Innings_Runs"]
)

In [168]:
highest_successful_chases = (
    successful_chases
    .sort_values(
        "Target",
        ascending=False
    )
    [
        [
            "match_id",
            "season",
            "venue",
            "Second_Innings_Team",
            "Target",
            "Runs_Chased",
            "winner"
        ]
    ]
    .head(10)
)

highest_successful_chases

,match_id,season,venue,Second_Innings_Team,Target,Runs_Chased,winner
626,1529278,2026,"Arun Jaitley Stadium, Delhi",Punjab Kings,265,265.0,Punjab Kings
488,1426280,2024,"Eden Gardens, Kolkata",Punjab Kings,262,262.0,Punjab Kings
544,1473464,2025,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Sunrisers Hyderabad,246,247.0,Sunrisers Hyderabad
632,1529284,2026,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,244,249.0,Sunrisers Hyderabad
627,1529279,2026,"Sawai Mansingh Stadium, Jaipur",Sunrisers Hyderabad,229,229.0,Sunrisers Hyderabad
638,1529290,2026,"Wankhede Stadium, Mumbai",Mumbai Indians,229,229.0,Mumbai Indians
586,1473507,2025,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Royal Challengers Bangalore,228,230.0,Royal Challengers Bangalore
634,1529286,2026,"Sawai Mansingh Stadium, Jaipur",Delhi Capitals,226,226.0,Delhi Capitals
214,1216527,2020,Sharjah Cricket Stadium,Rajasthan Royals,224,226.0,Rajasthan Royals
477,1426269,2024,"Eden Gardens, Kolkata",Rajasthan Royals,224,224.0,Rajasthan Royals

In [169]:
fig = px.bar(
    highest_successful_chases,
    x="Target",
    y="Second_Innings_Team",
    orientation="h",
    color="venue",
    text="Target",
    hover_data=[
        "season",
        "Runs_Chased"
    ],
    title="Highest Successful Run Chases"
)

fig.update_layout(
    xaxis_title="Target",
    yaxis_title="Chasing Team",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

The highest successful chases highlight teams and venues where large targets were still achievable.

This information is useful for evaluating batting depth and venue-specific target safety.

#### <b>⚔️ Team Performance by Venue</b>

##### Business Question

Which teams perform best at specific venues?

Venue-specific performance may reveal:

- Home-ground advantage
- Tactical suitability
- Familiarity with conditions
- Strong historical matchups

In [170]:
team_1_venue = matches_df[
    [
        "match_id",
        "venue",
        "team_1",
        "winner"
    ]
].rename(
    columns={
        "team_1": "team"
    }
)

team_2_venue = matches_df[
    [
        "match_id",
        "venue",
        "team_2",
        "winner"
    ]
].rename(
    columns={
        "team_2": "team"
    }
)

team_venue_matches = pd.concat(
    [
        team_1_venue,
        team_2_venue
    ],
    ignore_index=True
)

In [171]:
team_venue_matches["Win"] = (
    team_venue_matches["team"]
    ==
    team_venue_matches["winner"]
).astype(int)

In [172]:
team_venue_summary = (
    team_venue_matches
    .groupby(
        [
            "venue",
            "team"
        ],
        as_index=False
    )
    .agg(
        Matches=("match_id", "nunique"),
        Wins=("Win", "sum")
    )
)

team_venue_summary["Win %"] = (
    team_venue_summary["Wins"]
    /
    team_venue_summary["Matches"]
    * 100
).round(2)

team_venue_summary.head()

                         venue                 team  Matches  Wins  Win %
0  Arun Jaitley Stadium, Delhi  Chennai Super Kings       13     9  69.23
1  Arun Jaitley Stadium, Delhi      Deccan Chargers        4     2  50.00
2  Arun Jaitley Stadium, Delhi       Delhi Capitals       31    11  35.48
3  Arun Jaitley Stadium, Delhi     Delhi Daredevils       63    27  42.86
4  Arun Jaitley Stadium, Delhi        Gujarat Lions        3     1  33.33

In [173]:
selected_venue = "Wankhede Stadium, Mumbai"

In [174]:
selected_venue_performance = (
    team_venue_summary[
        team_venue_summary["venue"] == selected_venue
    ]
    .query("Matches >= 5")
    .sort_values(
        "Win %",
        ascending=False
    )
)

selected_venue_performance

,venue,team,Matches,Wins,Win %
362,"Wankhede Stadium, Mumbai",Gujarat Titans,6,4,66.67
367,"Wankhede Stadium, Mumbai",Mumbai Indians,99,58,58.59
369,"Wankhede Stadium, Mumbai",Punjab Kings,9,5,55.56
370,"Wankhede Stadium, Mumbai",Rajasthan Royals,21,11,52.38
357,"Wankhede Stadium, Mumbai",Chennai Super Kings,27,14,51.85
372,"Wankhede Stadium, Mumbai",Royal Challengers Bangalore,20,10,50.00
363,"Wankhede Stadium, Mumbai",Kings XI Punjab,11,5,45.45
366,"Wankhede Stadium, Mumbai",Lucknow Super Giants,7,3,42.86
359,"Wankhede Stadium, Mumbai",Delhi Capitals,11,4,36.36
365,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,19,5,26.32
360,"Wankhede Stadium, Mumbai",Delhi Daredevils,8,2,25.00
373,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,15,3,20.00

In [175]:
fig = px.bar(
    selected_venue_performance,
    x="Win %",
    y="team",
    orientation="h",
    color="Win %",
    text="Win %",
    hover_data=[
        "Matches",
        "Wins"
    ],
    title=f"Team Performance at {selected_venue}"
)

fig.update_layout(
    xaxis_title="Win Percentage",
    yaxis_title="Team",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Venue-specific win percentages can reveal teams that are well suited to particular pitch and ground conditions.

A minimum match threshold is necessary to avoid misleading conclusions from small samples.

#### <b>⚖️ Batter-Friendly and Bowler-Friendly Venues</b>

##### Business Question

Which venues are generally favourable to batters, and which are more supportive of bowlers?

This simplified classification uses the average first-innings score.

- Higher average scores suggest batter-friendly conditions
- Lower average scores suggest bowler-friendly conditions

This is a preliminary classification and should later be combined with wicket rates, boundary rates, and match-phase metrics.

In [176]:
overall_average_score = (
    qualified_venues[
        "Average_First_Innings_Score"
    ]
    .mean()
)

overall_average_score

np.float64(168.47478260869565)

In [177]:
qualified_venues["Venue Type"] = np.where(
    qualified_venues[
        "Average_First_Innings_Score"
    ] >= overall_average_score,
    "Batter-Friendly",
    "Bowler-Friendly"
)

qualified_venues[
    [
        "venue",
        "Matches",
        "Average_First_Innings_Score",
        "Venue Type"
    ]
].sort_values(
    "Average_First_Innings_Score",
    ascending=False
)

,venue,Matches,Average_First_Innings_Score,Venue Type
12,"Himachal Pradesh Cricket Association Stadium, ...",19,191.21,Batter-Friendly
18,Maharaja Yadavindra Singh International Cricke...,17,186.59,Batter-Friendly
20,"Narendra Modi Stadium, Ahmedabad",53,180.68,Batter-Friendly
4,"Brabourne Stadium, Mumbai",27,178.52,Batter-Friendly
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29,174.79,Batter-Friendly
16,"M Chinnaswamy Stadium, Bengaluru",104,174.06,Batter-Friendly
36,"Wankhede Stadium, Mumbai",132,173.13,Batter-Friendly
0,"Arun Jaitley Stadium, Delhi",104,171.76,Batter-Friendly
8,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,17,169.53,Batter-Friendly
28,"Sawai Mansingh Stadium, Jaipur",68,169.06,Batter-Friendly
27,Saurashtra Cricket Association Stadium,10,168.90,Batter-Friendly
10,"Eden Gardens, Kolkata",107,168.64,Batter-Friendly
26,"Rajiv Gandhi International Stadium, Uppal, Hyd...",90,168.34,Bowler-Friendly
19,"Maharashtra Cricket Association Stadium, Pune",35,168.29,Bowler-Friendly
25,"Punjab Cricket Association IS Bindra Stadium, ...",61,168.28,Bowler-Friendly
17,"MA Chidambaram Stadium, Chepauk, Chennai",98,165.56,Bowler-Friendly
9,Dubai International Cricket Stadium,46,163.76,Bowler-Friendly
7,"Dr DY Patil Sports Academy, Mumbai",37,159.65,Bowler-Friendly
30,Sharjah Cricket Stadium,28,159.04,Bowler-Friendly
31,Sheikh Zayed Stadium,29,158.86,Bowler-Friendly
34,SuperSport Park,12,154.83,Bowler-Friendly
15,Kingsmead,15,152.00,Bowler-Friendly
33,Subrata Roy Sahara Stadium,16,149.44,Bowler-Friendly

In [178]:
fig = px.scatter(
    qualified_venues,
    x="Matches",
    y="Average_First_Innings_Score",
    color="Venue Type",
    size="Matches",
    hover_name="venue",
    title="Venue Classification by Average First-Innings Score"
)

fig.update_layout(
    xaxis_title="Matches Hosted",
    yaxis_title="Average First-Innings Score"
)

fig.show()

#### <b>📌 Venue and Match Conditions Analytics Summary</b>

This notebook evaluated how venue and match context influence IPL outcomes.

##### Venue Profile

- Matches hosted by venue
- Average first-innings score
- First-innings score distribution
- Highest innings totals
- Batter-friendly and bowler-friendly venue classification

##### Match Strategy

- Chasing versus defending success
- Venue-specific chasing success
- Toss impact by venue
- Toss decision success

##### High-Pressure Performance

- Highest successful run chases
- Team performance by venue

##### <b>Key Conclusion</b>

Venue conditions have a significant relationship with scoring patterns, toss decisions, chasing success, and team strategy.

These contextual features will be valuable during later stages of the project, particularly for:

- Match winner prediction
- Score prediction
- Team strategy dashboards
- Venue recommendation systems

### <b>Section 8 – Partnership & Player Combination Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook analyzes batting partnerships and player combinations using ball-by-ball IPL data.

The analysis focuses on:

- Highest run partnerships
- Most successful batting pairs
- Partnership consistency
- Boundary contribution by partnerships
- Team-wise partnership analysis
- Player combination dashboard

Partnership analysis provides valuable insights into team stability, batting depth, and player chemistry.

#### <b>🤝 Partnership Identification</b>

##### Business Question

How can we uniquely identify a batting partnership?

A batting partnership consists of two players batting together.

Since striker and non-striker frequently switch after runs, we create an order-independent partnership identifier by sorting both player names alphabetically.

In [179]:
partnership_df = deliveries_df.copy()

In [180]:
partnership_df["Partnership"] = (
    partnership_df[
        ["batter", "non_striker"]
    ]
    .apply(
        lambda players: " & ".join(sorted(players)),
        axis=1
    )
)

partnership_df.head()

,match_id,season,match_date,innings,batting_team,bowling_team,target_runs,target_overs,over,delivery_number,...,is_six,is_boundary,is_wicket,is_bowler_wicket,wickets_on_delivery,player_dismissed,dismissal_kind,fielder,source_file,Partnership
0,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,1,...,0,0,0,0,0,NaN,NaN,NaN,1082591.json,DA Warner & S Dhawan
1,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,2,...,0,0,0,0,0,NaN,NaN,NaN,1082591.json,DA Warner & S Dhawan
2,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,3,...,0,1,0,0,0,NaN,NaN,NaN,1082591.json,DA Warner & S Dhawan
3,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,4,...,0,0,0,0,0,NaN,NaN,NaN,1082591.json,DA Warner & S Dhawan
4,1082591,2017,05-04-2017,1,Sunrisers Hyderabad,Royal Challengers Bangalore,NaN,NaN,0,5,...,0,0,0,0,0,NaN,NaN,NaN,1082591.json,DA Warner & S Dhawan

##### <b>💡 Business Insight</b>

Sorting player names ensures that:

Virat Kohli + AB de Villiers

and

AB de Villiers + Virat Kohli

are treated as the same partnership.

#### <b>🏏 Highest Run Partnerships</b>

##### Business Question

Which batting pairs have scored the most runs together in IPL history?

In [181]:
partnership_runs = (
    partnership_df
    .groupby(
        "Partnership",
        as_index=False
    )["total_runs"]
    .sum()
)

partnership_runs.rename(
    columns={
        "total_runs":"Runs"
    },
    inplace=True
)

partnership_runs.sort_values(
    "Runs",
    ascending=False,
    inplace=True
)

partnership_runs.head(10)

                         Partnership  Runs
381         AB de Villiers & V Kohli  3134
1297  B Sai Sudharsan & Shubman Gill  2966
1619              CH Gayle & V Kohli  2802
1929            DA Warner & S Dhawan  2357
2416          F du Plessis & V Kohli  2032
1817            D Padikkal & V Kohli  2024
2452          G Gambhir & RV Uthappa  1906
1007       Abhishek Sharma & TM Head  1892
2869        Ishan Kishan & RG Sharma  1868
3520           KL Rahul & MA Agarwal  1731

In [182]:
fig = px.bar(
    partnership_runs.head(10),
    x="Runs",
    y="Partnership",
    orientation="h",
    color="Runs",
    text="Runs",
    title="Highest Run Partnerships"
)

fig.show()

##### 💡 Business Insight

High-scoring partnerships indicate strong player chemistry and stability in the batting lineup.

Teams often retain successful batting combinations across multiple seasons.

#### <b>🔄 Partnership Frequency</b>

##### Business Question

Which batting pairs have batted together most often?

Frequent partnerships generally indicate long-term team combinations.

In [183]:
partnership_frequency = (
    partnership_df
    .groupby("Partnership")
    .agg(
        Balls=("ball","count")
    )
    .reset_index()
)

partnership_frequency.sort_values(
    "Balls",
    ascending=False,
    inplace=True
)

partnership_frequency.head(10)

                         Partnership  Balls
381         AB de Villiers & V Kohli   2059
1619              CH Gayle & V Kohli   1973
1297  B Sai Sudharsan & Shubman Gill   1912
1929            DA Warner & S Dhawan   1725
2452          G Gambhir & RV Uthappa   1425
1817            D Padikkal & V Kohli   1389
2416          F du Plessis & V Kohli   1381
2869        Ishan Kishan & RG Sharma   1319
3520           KL Rahul & MA Agarwal   1211
1596             CH Gayle & KL Rahul   1208

In [184]:
fig = px.bar(
    partnership_frequency.head(10),
    x="Balls",
    y="Partnership",
    orientation="h",
    color="Balls",
    text="Balls",
    title="Most Frequent Partnerships"
)

fig.show()

#### <b>⚡ Partnership Strike Rate</b>

##### Business Question

Which partnerships score the fastest?

Strike Rate = Runs ÷ Balls × 100

In [185]:
partnership_stats = (
    partnership_runs.merge(
        partnership_frequency,
        on="Partnership"
    )
)

partnership_stats["Strike Rate"] = (
    partnership_stats["Runs"]
    /
    partnership_stats["Balls"]
    *100
).round(2)

partnership_stats.head()

                      Partnership  Runs  Balls  Strike Rate
0        AB de Villiers & V Kohli  3134   2059       152.21
1  B Sai Sudharsan & Shubman Gill  2966   1912       155.13
2              CH Gayle & V Kohli  2802   1973       142.02
3            DA Warner & S Dhawan  2357   1725       136.64
4          F du Plessis & V Kohli  2032   1381       147.14

In [186]:
qualified_pairs = partnership_stats[
    partnership_stats["Balls"] >= 150
]

qualified_pairs.sort_values(
    "Strike Rate",
    ascending=False,
    inplace=True
)

qualified_pairs.head(10)

                         Partnership  Runs  Balls  Strike Rate
240  Abishek Porel & J Fraser-McGurk   339    151       224.50
231             JP Inglis & MR Marsh   350    172       203.49
187                KL Rahul & N Rana   401    202       198.51
180      Dhruv Jurel & V Suryavanshi   408    207       197.10
7          Abhishek Sharma & TM Head  1892    968       195.45
24       V Suryavanshi & YBK Jaiswal  1171    601       194.84
291             GJ Maxwell & HM Amla   293    151       194.04
102              PD Salt & SP Narine   559    289       193.43
230               C Green & SA Yadav   350    192       182.29
55          H Klaasen & Ishan Kishan   817    451       181.15

In [187]:
fig = px.bar(
    qualified_pairs.head(10),
    x="Strike Rate",
    y="Partnership",
    orientation="h",
    color="Strike Rate",
    text="Strike Rate",
    title="Fastest Scoring Partnerships"
)

fig.show()

##### <b>💡 Business Insight</b>

Fast-scoring partnerships can rapidly shift match momentum and are particularly valuable during Powerplay and Death Overs.

#### <b>💥 Boundary Contribution</b>

##### Business Question

Which partnerships rely most on boundaries?

Boundary Percentage = Boundary Balls ÷ Balls Faced × 100

In [188]:
boundary_pairs = (
    partnership_df[
        partnership_df["is_boundary"] == True
    ]
    .groupby("Partnership")
    .size()
    .reset_index(name="Boundary Balls")
)

boundary_pairs.head()

                     Partnership  Boundary Balls
0      A Ashish Reddy & A Mishra               3
1      A Ashish Reddy & CL White               1
2  A Ashish Reddy & DB Ravi Teja               1
3     A Ashish Reddy & DJG Sammy               4
4  A Ashish Reddy & DT Christian               2

In [189]:
boundary_analysis = (
    partnership_frequency.merge(
        boundary_pairs,
        on="Partnership",
        how="left"
    )
)

boundary_analysis["Boundary Balls"] = (
    boundary_analysis["Boundary Balls"]
    .fillna(0)
)

boundary_analysis["Boundary %"] = (
    boundary_analysis["Boundary Balls"]
    /
    boundary_analysis["Balls"]
    *100
).round(2)

boundary_analysis.head()

                      Partnership  Balls  Boundary Balls  Boundary %
0        AB de Villiers & V Kohli   2059           385.0       18.70
1              CH Gayle & V Kohli   1973           385.0       19.51
2  B Sai Sudharsan & Shubman Gill   1912           393.0       20.55
3            DA Warner & S Dhawan   1725           324.0       18.78
4          G Gambhir & RV Uthappa   1425           254.0       17.82

In [190]:
qualified_boundary = boundary_analysis[
    boundary_analysis["Balls"] >= 150
].sort_values(
    "Boundary %",
    ascending=False
)

fig = px.bar(
    qualified_boundary.head(10),
    x="Boundary %",
    y="Partnership",
    orientation="h",
    color="Boundary %",
    text="Boundary %",
    title="Partnerships with Highest Boundary Percentage"
)

fig.show()

##### <b>💡 Business Insight</b>

Some batting pairs rely heavily on boundary scoring, while others build innings through strike rotation.

Understanding this balance helps teams optimize batting order based on match situations.

#### <b>🤝 Match-Level Partnership Performance</b>

##### Business Question

What were the highest individual partnerships recorded in IPL matches?

Career-level partnership totals show long-term chemistry, but they do not reveal the largest partnership produced in a single innings.

Therefore, partnership runs are aggregated separately for every:

- Match
- Innings
- Batting team
- Partnership pair

In [191]:
match_partnerships = (
    partnership_df
    .groupby(
        [
            "match_id",
            "season",
            "innings",
            "batting_team",
            "Partnership"
        ],
        as_index=False
    )
    .agg(
        Partnership_Runs=("total_runs", "sum"),
        Balls_Together=(
            "is_legal_delivery",
            "sum"
        ),
        Boundaries=(
            "is_boundary",
            "sum"
        )
    )
)

match_partnerships.head()

,match_id,season,innings,batting_team,Partnership,Partnership_Runs,Balls_Together,Boundaries
0,335982,2008,1,Kolkata Knight Riders,BB McCullum & DJ Hussey,60,30,7
1,335982,2008,1,Kolkata Knight Riders,BB McCullum & Mohammad Hafeez,50,17,8
2,335982,2008,1,Kolkata Knight Riders,BB McCullum & RT Ponting,51,41,4
3,335982,2008,1,Kolkata Knight Riders,BB McCullum & SC Ganguly,61,32,10
4,335982,2008,2,Royal Challengers Bangalore,AA Noffke & CL White,5,4,0

In [192]:
highest_match_partnerships = (
    match_partnerships
    .sort_values(
        "Partnership_Runs",
        ascending=False
    )
    .head(10)
)

highest_match_partnerships

,match_id,season,innings,batting_team,Partnership,Partnership_Runs,Balls_Together,Boundaries
7433,980987,2016,1,Royal Challengers Bangalore,AB de Villiers & V Kohli,229,96,34
16168,1529278,2026,1,Delhi Capitals,KL Rahul & N Rana,220,95,35
6698,829795,2015,1,Royal Challengers Bangalore,AB de Villiers & V Kohli,215,101,32
12575,1304112,2022,1,Lucknow Super Giants,KL Rahul & Q de Kock,210,120,27
14517,1426297,2024,1,Gujarat Titans,B Sai Sudharsan & Shubman Gill,210,104,28
3183,501260,2011,1,Kings XI Punjab,AC Gilchrist & SE Marsh,206,96,29
15502,1473498,2025,2,Gujarat Titans,B Sai Sudharsan & Shubman Gill,205,114,26
4166,548372,2012,1,Royal Challengers Bangalore,CH Gayle & V Kohli,204,106,30
3656,548329,2012,2,Delhi Daredevils,DA Warner & NV Ojha,189,98,24
9401,1175366,2019,1,Sunrisers Hyderabad,DA Warner & JM Bairstow,185,98,25

In [193]:
fig = px.bar(
    highest_match_partnerships,
    x="Partnership_Runs",
    y="Partnership",
    orientation="h",
    color="batting_team",
    text="Partnership_Runs",
    hover_data=[
        "season",
        "match_id",
        "innings",
        "Balls_Together"
    ],
    title="Highest Partnerships in a Single IPL Innings"
)

fig.update_layout(
    xaxis_title="Partnership Runs",
    yaxis_title="Batting Partnership",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Large individual partnerships often determine match outcomes because they:

- Stabilise the innings after early wickets
- Create momentum during a run chase
- Allow teams to accelerate in the final overs
- Reduce pressure on the remaining batting lineup

Match-level partnership analysis is more useful than career totals when studying exceptional innings.

#### <b>🏏 Highest Partnerships by Wicket Number</b>

##### Business Question

What is the highest partnership recorded for each wicket?

Partnership roles differ according to the wicket number:

- First-wicket partnerships provide strong starts
- Middle-order partnerships rebuild the innings
- Lower-order partnerships add valuable finishing runs

The wicket number is determined from the number of wickets that had fallen before each delivery.

In [194]:
partnership_sequence = partnership_df.sort_values(
    [
        "match_id",
        "innings",
        "over",
        "ball"
    ]
).copy()

In [195]:
partnership_sequence["Wicket_Event"] = (
    partnership_sequence["is_wicket"]
    .fillna(False)
    .astype(int)
)

In [196]:
partnership_sequence["Wickets_Before_Ball"] = (
    partnership_sequence
    .groupby(
        [
            "match_id",
            "innings"
        ]
    )["Wicket_Event"]
    .cumsum()
    -
    partnership_sequence["Wicket_Event"]
)

In [197]:
partnership_sequence["Wicket_Number"] = (
    partnership_sequence["Wickets_Before_Ball"] + 1
)

partnership_sequence[
    [
        "match_id",
        "innings",
        "over",
        "ball",
        "Partnership",
        "Wicket_Number"
    ]
].head()

        match_id  innings  over  ball               Partnership  Wicket_Number
159134    335982        1     0   0.1  BB McCullum & SC Ganguly              1
159135    335982        1     0   0.2  BB McCullum & SC Ganguly              1
159136    335982        1     0   0.3  BB McCullum & SC Ganguly              1
159137    335982        1     0   0.4  BB McCullum & SC Ganguly              1
159138    335982        1     0   0.5  BB McCullum & SC Ganguly              1

> **Important:** This calculation assumes that `is_wicket` correctly identifies all wickets that end a batting partnership. Review special dismissal types such as retired hurt, retired out, and obstructing the field according to the rules used by your parser.

In [198]:
wicket_partnerships = (
    partnership_sequence
    .groupby(
        [
            "match_id",
            "season",
            "innings",
            "batting_team",
            "Wicket_Number",
            "Partnership"
        ],
        as_index=False
    )
    .agg(
        Partnership_Runs=("total_runs", "sum"),
        Balls_Together=(
            "is_legal_delivery",
            "sum"
        )
    )
)

wicket_partnerships.head()

,match_id,season,innings,batting_team,Wicket_Number,Partnership,Partnership_Runs,Balls_Together
0,335982,2008,1,Kolkata Knight Riders,1,BB McCullum & SC Ganguly,61,32
1,335982,2008,1,Kolkata Knight Riders,2,BB McCullum & RT Ponting,51,41
2,335982,2008,1,Kolkata Knight Riders,3,BB McCullum & DJ Hussey,60,30
3,335982,2008,1,Kolkata Knight Riders,4,BB McCullum & Mohammad Hafeez,50,17
4,335982,2008,2,Royal Challengers Bangalore,1,R Dravid & W Jaffer,4,7

In [199]:
highest_by_wicket = (
    wicket_partnerships
    .sort_values(
        [
            "Wicket_Number",
            "Partnership_Runs"
        ],
        ascending=[
            True,
            False
        ]
    )
    .groupby(
        "Wicket_Number",
        as_index=False
    )
    .head(1)
)

highest_by_wicket[
    [
        "Wicket_Number",
        "Partnership",
        "batting_team",
        "Partnership_Runs",
        "Balls_Together",
        "season"
    ]
]

,Wicket_Number,Partnership,batting_team,Partnership_Runs,Balls_Together,season
12579,1,KL Rahul & Q de Kock,Lucknow Super Giants,210,120,2022
7434,2,AB de Villiers & V Kohli,Royal Challengers Bangalore,229,96,2016
11946,3,RV Uthappa & S Dube,Chennai Super Kings,165,73,2022
9980,4,Gurkeerat Singh & SO Hetmyer,Royal Challengers Bangalore,144,89,2019
7362,5,Shakib Al Hasan & YK Pathan,Kolkata Knight Riders,134,85,2016
4105,6,AT Rayudu & KA Pollard,Mumbai Indians,122,65,2012
6204,7,Harbhajan Singh & J Suchith,Mumbai Indians,100,37,2015
14074,8,A Badoni & Arshad Khan,Lucknow Super Giants,73,42,2024
13494,9,AS Joseph & Rashid Khan,Gujarat Titans,88,40,2023
12887,10,Mohit Rathee & S Dhawan,Punjab Kings,55,30,2023

In [200]:
fig = px.bar(
    highest_by_wicket,
    x="Wicket_Number",
    y="Partnership_Runs",
    color="batting_team",
    text="Partnership_Runs",
    hover_data=[
        "Partnership",
        "season",
        "Balls_Together"
    ],
    title="Highest IPL Partnership by Wicket Number"
)

fig.update_layout(
    xaxis_title="Wicket Number",
    yaxis_title="Partnership Runs"
)

fig.show()

##### <b>💡 Business Insight</b>

Different wicket partnerships serve different tactical purposes.

A strong opening partnership establishes momentum, while high-value middle-order partnerships demonstrate recovery ability under pressure.

Lower-order partnerships can also decide close matches by adding unexpected runs near the end of an innings.

#### <b>⭐ Partnership Consistency</b>

##### Business Question

Which batting pairs regularly produce meaningful partnerships?

A pair should not be considered reliable because of only one exceptional innings.

For this analysis, a meaningful partnership is defined as one that scores at least 30 runs.

##### Consistency Index

Consistency Index = 30+ Partnerships ÷ Innings Together × 100

In [201]:
partnership_consistency = (
    match_partnerships
    .groupby(
        "Partnership",
        as_index=False
    )
    .agg(
        Innings_Together=(
            "match_id",
            "count"
        ),
        Total_Runs=(
            "Partnership_Runs",
            "sum"
        ),
        Average_Partnership=(
            "Partnership_Runs",
            "mean"
        ),
        Thirty_Plus=(
            "Partnership_Runs",
            lambda scores: (
                scores >= 30
            ).sum()
        ),
        Fifty_Plus=(
            "Partnership_Runs",
            lambda scores: (
                scores >= 50
            ).sum()
        ),
        Hundred_Plus=(
            "Partnership_Runs",
            lambda scores: (
                scores >= 100
            ).sum()
        )
    )
)

In [202]:
partnership_consistency["Consistency Index"] = (
    partnership_consistency["Thirty_Plus"]
    /
    partnership_consistency["Innings_Together"]
    * 100
).round(2)

partnership_consistency[
    "Average_Partnership"
] = partnership_consistency[
    "Average_Partnership"
].round(2)

In [203]:
qualified_consistency = (
    partnership_consistency[
        partnership_consistency[
            "Innings_Together"
        ] >= 10
    ]
    .sort_values(
        "Consistency Index",
        ascending=False
    )
)

qualified_consistency.head(10)

,Partnership,Innings_Together,Total_Runs,Average_Partnership,Thirty_Plus,Fifty_Plus,Hundred_Plus,Consistency Index
4459,N Wadhera & SS Iyer,11,553,50.27,8,7,0,72.73
4447,N Rana & VR Iyer,11,495,45.00,8,3,1,72.73
1286,B Sai Sudharsan & JC Buttler,14,691,49.36,10,8,0,71.43
2593,H Klaasen & Ishan Kishan,14,817,58.36,10,7,1,71.43
1913,DA Warner & MK Pandey,17,884,52.00,12,8,2,70.59
3520,KL Rahul & MA Agarwal,33,1731,52.45,23,15,5,69.70
5399,V Suryavanshi & YBK Jaiswal,23,1171,50.91,16,11,2,69.57
3003,JC Buttler & Shubman Gill,16,739,46.19,11,7,1,68.75
1297,B Sai Sudharsan & Shubman Gill,49,2966,60.53,33,22,11,67.35
3524,KL Rahul & MP Stoinis,18,660,36.67,12,5,0,66.67

In [204]:
fig = px.bar(
    qualified_consistency.head(10),
    x="Consistency Index",
    y="Partnership",
    orientation="h",
    color="Consistency Index",
    text="Consistency Index",
    hover_data=[
        "Innings_Together",
        "Average_Partnership",
        "Thirty_Plus",
        "Fifty_Plus"
    ],
    title="Most Consistent IPL Batting Partnerships"
)

fig.update_layout(
    xaxis_title="Consistency Index (%)",
    yaxis_title="Partnership",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

The Consistency Index separates regularly productive partnerships from pairs whose career totals are driven by only a few exceptional innings.

A reliable partnership provides stability and reduces dependency on individual performances.

#### <b>📈 Partnership Conversion Rate</b>

##### Business Question

How frequently do partnerships convert good starts into major contributions?

Two conversion measures are used:

- 30-to-50 Conversion Rate
- 50-to-100 Conversion Rate

These metrics help distinguish partnerships that merely start well from those that produce match-defining stands.

In [205]:
conversion_analysis = (
    partnership_consistency.copy()
)

In [206]:
conversion_analysis[
    "30-to-50 Conversion %"
] = np.where(
    conversion_analysis["Thirty_Plus"] > 0,
    (
        conversion_analysis["Fifty_Plus"]
        /
        conversion_analysis["Thirty_Plus"]
        * 100
    ),
    np.nan
).round(2)

In [207]:
conversion_analysis[
    "50-to-100 Conversion %"
] = np.where(
    conversion_analysis["Fifty_Plus"] > 0,
    (
        conversion_analysis["Hundred_Plus"]
        /
        conversion_analysis["Fifty_Plus"]
        * 100
    ),
    np.nan
).round(2)

In [208]:
qualified_conversion = (
    conversion_analysis[
        conversion_analysis[
            "Innings_Together"
        ] >= 10
    ]
    .sort_values(
        "30-to-50 Conversion %",
        ascending=False
    )
)

qualified_conversion.head(10)

,Partnership,Innings_Together,Total_Runs,Average_Partnership,Thirty_Plus,Fifty_Plus,Hundred_Plus,Consistency Index,30-to-50 Conversion %,50-to-100 Conversion %
4999,RM Patidar & TH David,11,202,18.36,1,1,0,9.09,100.0,0.00
4934,RD Gaikwad & RV Uthappa,10,223,22.30,1,1,1,10.00,100.0,100.00
4620,PD Salt & SP Narine,12,559,46.58,6,6,1,50.00,100.0,16.67
518,AD Russell & Shubman Gill,10,343,34.30,5,5,0,50.00,100.0,0.00
4689,PP Shaw & RR Pant,14,279,19.93,3,3,0,21.43,100.0,0.00
753,AM Rahane & STR Binny,12,205,17.08,1,1,0,8.33,100.0,0.00
4512,Naman Dhir & Tilak Varma,10,322,32.20,4,4,0,40.00,100.0,0.00
3164,JM Sharma & SM Curran,10,272,27.20,3,3,0,30.00,100.0,0.00
3789,LRPL Taylor & RV Uthappa,10,118,11.80,1,1,0,10.00,100.0,0.00
4585,P Simran Singh & S Dhawan,15,312,20.80,3,3,0,20.00,100.0,0.00

In [209]:
fig = px.scatter(
    qualified_conversion,
    x="30-to-50 Conversion %",
    y="50-to-100 Conversion %",
    size="Innings_Together",
    color="Average_Partnership",
    hover_name="Partnership",
    title="Partnership Conversion Performance"
)

fig.update_layout(
    xaxis_title="30-to-50 Conversion Rate (%)",
    yaxis_title="50-to-100 Conversion Rate (%)"
)

fig.show()

##### <b>💡 Business Insight</b>

High conversion rates indicate partnerships that remain together after establishing a good start.

Such pairs are valuable because they protect the middle and lower order while creating opportunities for late-innings acceleration.

#### <b>📅 Best Partnerships by Season</b>

##### Business Question

Which batting pair scored the most partnership runs in each IPL season?

Season-wise analysis identifies:

- Successful combinations in a particular season
- New or emerging partnerships
- Changes caused by team transfers
- Partnerships that contributed to team success

In [210]:
season_partnerships = (
    match_partnerships
    .groupby(
        [
            "season",
            "Partnership",
            "batting_team"
        ],
        as_index=False
    )
    .agg(
        Runs=("Partnership_Runs", "sum"),
        Innings=("match_id", "count"),
        Average_Partnership=(
            "Partnership_Runs",
            "mean"
        )
    )
)

season_partnerships[
    "Average_Partnership"
] = season_partnerships[
    "Average_Partnership"
].round(2)

In [211]:
best_season_partnerships = (
    season_partnerships
    .sort_values(
        [
            "season",
            "Runs"
        ],
        ascending=[
            True,
            False
        ]
    )
    .groupby(
        "season",
        as_index=False
    )
    .head(1)
)

best_season_partnerships

,season,Partnership,batting_team,Runs,Innings,Average_Partnership
157,2008,G Gambhir & V Sehwag,Delhi Daredevils,529,14,37.79
459,2009,AC Gilchrist & HH Gibbs,Deccan Chargers,473,14,33.79
1036,2010,JH Kallis & MK Pandey,Royal Challengers Bangalore,447,12,37.25
1296,2011,AT Rayudu & SR Tendulkar,Mumbai Indians,528,12,44.00
1803,2012,CH Gayle & V Kohli,Royal Challengers Bangalore,593,9,65.89
2180,2013,AJ Finch & RV Uthappa,Pune Warriors,606,14,43.29
2639,2014,BB McCullum & DR Smith,Chennai Super Kings,513,12,42.75
3042,2015,DA Warner & S Dhawan,Sunrisers Hyderabad,622,14,44.43
3258,2016,AB de Villiers & V Kohli,Royal Challengers Bangalore,939,13,72.23
3734,2017,DA Warner & S Dhawan,Sunrisers Hyderabad,646,14,46.14
4225,2018,KS Williamson & S Dhawan,Sunrisers Hyderabad,598,11,54.36
4453,2019,DA Warner & JM Bairstow,Sunrisers Hyderabad,791,10,79.10
4899,2020,KL Rahul & MA Agarwal,Kings XI Punjab,671,11,61.00
5173,2021,F du Plessis & RD Gaikwad,Chennai Super Kings,756,16,47.25
5676,2022,KL Rahul & Q de Kock,Lucknow Super Giants,585,15,39.00
6038,2023,F du Plessis & V Kohli,Royal Challengers Bangalore,939,14,67.07
6446,2024,F du Plessis & V Kohli,Royal Challengers Bangalore,707,15,47.13
6810,2025,B Sai Sudharsan & Shubman Gill,Gujarat Titans,912,15,60.80
7191,2026,B Sai Sudharsan & Shubman Gill,Gujarat Titans,908,16,56.75

In [212]:
fig = px.bar(
    best_season_partnerships,
    x="season",
    y="Runs",
    color="batting_team",
    text="Runs",
    hover_data=[
        "Partnership",
        "Innings",
        "Average_Partnership"
    ],
    title="Leading Batting Partnership by IPL Season"
)

fig.update_layout(
    xaxis_title="Season",
    yaxis_title="Partnership Runs"
)

fig.show()

##### <b>💡 Business Insight</b>

Season-wise partnership leaders often represent the most stable section of a team's batting order.

Franchises can use this information when making decisions about player retention, auction strategy, and batting-order continuity.

#### <b>🏏 Team-Wise Partnership Analysis</b>

##### Business Question

Which partnership has contributed the most runs for each IPL team?

This analysis identifies the strongest historical batting combination associated with every franchise.

In [213]:
team_partnerships = (
    match_partnerships
    .groupby(
        [
            "batting_team",
            "Partnership"
        ],
        as_index=False
    )
    .agg(
        Runs=("Partnership_Runs", "sum"),
        Innings=("match_id", "count"),
        Average_Partnership=(
            "Partnership_Runs",
            "mean"
        ),
        Highest_Partnership=(
            "Partnership_Runs",
            "max"
        )
    )
)

team_partnerships[
    "Average_Partnership"
] = team_partnerships[
    "Average_Partnership"
].round(2)

In [214]:
best_pair_by_team = (
    team_partnerships
    .sort_values(
        [
            "batting_team",
            "Runs"
        ],
        ascending=[
            True,
            False
        ]
    )
    .groupby(
        "batting_team",
        as_index=False
    )
    .head(1)
)

best_pair_by_team

,batting_team,Partnership,Runs,Innings,Average_Partnership,Highest_Partnership
301,Chennai Super Kings,MS Dhoni & RA Jadeja,1708,68,25.12,72
445,Deccan Chargers,AC Gilchrist & HH Gibbs,921,26,35.42,101
864,Delhi Capitals,PP Shaw & S Dhawan,1461,44,33.20,138
1098,Delhi Daredevils,G Gambhir & V Sehwag,933,28,33.32,115
1415,Gujarat Lions,KD Karthik & SK Raina,579,17,34.06,133
1455,Gujarat Titans,B Sai Sudharsan & Shubman Gill,2966,49,60.53,210
1674,Kings XI Punjab,CH Gayle & KL Rahul,1343,29,46.31,120
2020,Kochi Tuskers Kerala,BB McCullum & DPMD Jayawardene,348,7,49.71,128
2334,Kolkata Knight Riders,G Gambhir & RV Uthappa,1906,48,39.71,158
2781,Lucknow Super Giants,KL Rahul & Q de Kock,892,26,34.31,210
3122,Mumbai Indians,Ishan Kishan & RG Sharma,1868,54,34.59,101
3449,Pune Warriors,AJ Finch & RV Uthappa,606,14,43.29,97
3770,Punjab Kings,P Simran Singh & Priyansh Arya,1149,31,37.06,126
4138,Rajasthan Royals,JC Buttler & SV Samson,1637,46,35.59,150
4406,Rising Pune Supergiants,AM Rahane & SPD Smith,440,10,44.00,111
4556,Royal Challengers Bangalore,AB de Villiers & V Kohli,3134,77,40.70,229
5339,Sunrisers Hyderabad,DA Warner & S Dhawan,2357,50,47.14,139

In [215]:
fig = px.bar(
    best_pair_by_team,
    x="Runs",
    y="batting_team",
    orientation="h",
    color="Runs",
    text="Partnership",
    hover_data=[
        "Innings",
        "Average_Partnership",
        "Highest_Partnership"
    ],
    title="Most Productive Partnership for Each Team"
)

fig.update_layout(
    xaxis_title="Total Partnership Runs",
    yaxis_title="Team",
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

A team's most productive pair often forms the foundation of its batting strategy.

Retaining successful combinations can preserve continuity, role clarity, and chemistry within the batting order.

#### <b>📊 Team Partnership Dashboard</b>

##### Business Question

What are the most successful batting combinations for a selected IPL team?

This dashboard compares partnerships using:

- Total runs
- Innings together
- Average partnership
- Highest partnership

In [216]:
sorted(
    team_partnerships[
        "batting_team"
    ].dropna().unique()
)

['Chennai Super Kings',
 'Deccan Chargers',
 'Delhi Capitals',
 'Delhi Daredevils',
 'Gujarat Lions',
 'Gujarat Titans',
 'Kings XI Punjab',
 'Kochi Tuskers Kerala',
 'Kolkata Knight Riders',
 'Lucknow Super Giants',
 'Mumbai Indians',
 'Pune Warriors',
 'Punjab Kings',
 'Rajasthan Royals',
 'Rising Pune Supergiants',
 'Royal Challengers Bangalore',
 'Sunrisers Hyderabad']

In [217]:
selected_team = "Royal Challengers Bangalore"

In [218]:
selected_team_pairs = (
    team_partnerships[
        team_partnerships["batting_team"]
        ==
        selected_team
    ]
    .sort_values(
        "Runs",
        ascending=False
    )
    .head(10)
)

selected_team_pairs

,batting_team,Partnership,Runs,Innings,Average_Partnership,Highest_Partnership
4556,Royal Challengers Bangalore,AB de Villiers & V Kohli,3134,77,40.70,229
4665,Royal Challengers Bangalore,CH Gayle & V Kohli,2802,60,46.70,204
4754,Royal Challengers Bangalore,F du Plessis & V Kohli,2032,41,49.56,172
4702,Royal Challengers Bangalore,D Padikkal & V Kohli,2024,43,47.07,181
5074,Royal Challengers Bangalore,RM Patidar & V Kohli,913,26,35.12,99
4663,Royal Challengers Bangalore,CH Gayle & TM Dilshan,909,20,45.45,167
5042,Royal Challengers Bangalore,PD Salt & V Kohli,792,19,41.68,120
4746,Royal Challengers Bangalore,F du Plessis & GJ Maxwell,661,11,60.09,127
5037,Royal Challengers Bangalore,PA Patel & V Kohli,609,24,25.38,92
4887,Royal Challengers Bangalore,KL Rahul & V Kohli,574,9,63.78,121

In [219]:
fig = px.scatter(
    selected_team_pairs,
    x="Average_Partnership",
    y="Runs",
    size="Innings",
    color="Highest_Partnership",
    hover_name="Partnership",
    title=(
        f"Partnership Performance – "
        f"{selected_team}"
    )
)

fig.update_layout(
    xaxis_title="Average Partnership",
    yaxis_title="Total Partnership Runs"
)

fig.show()

##### <b>💡 Business Insight</b>

The dashboard separates long-serving combinations from highly efficient combinations.

For example:

- High total runs and many innings indicate longevity
- High average with fewer innings may indicate emerging potential
- A high maximum partnership shows match-winning capability

#### <b>⚔️ Player Combination Dashboard</b>

##### Business Question

How do selected batting partnerships compare across major performance indicators?

A multidimensional comparison helps analysts avoid evaluating pairs using total runs alone.

In [220]:
partnership_dashboard = (
    partnership_stats
    .merge(
        partnership_consistency[
            [
                "Partnership",
                "Innings_Together",
                "Average_Partnership",
                "Thirty_Plus",
                "Fifty_Plus",
                "Hundred_Plus",
                "Consistency Index"
            ]
        ],
        on="Partnership",
        how="left"
    )
    .merge(
        boundary_analysis[
            [
                "Partnership",
                "Boundary %"
            ]
        ],
        on="Partnership",
        how="left"
    )
)

partnership_dashboard.head()

,Partnership,Runs,Balls,Strike Rate,Innings_Together,Average_Partnership,Thirty_Plus,Fifty_Plus,Hundred_Plus,Consistency Index,Boundary %
0,AB de Villiers & V Kohli,3134,2059,152.21,77,40.70,32,21,10,41.56,18.70
1,B Sai Sudharsan & Shubman Gill,2966,1912,155.13,49,60.53,33,22,11,67.35,20.55
2,CH Gayle & V Kohli,2802,1973,142.02,60,46.70,33,21,9,55.00,19.51
3,DA Warner & S Dhawan,2357,1725,136.64,50,47.14,27,20,6,54.00,18.78
4,F du Plessis & V Kohli,2032,1381,147.14,41,49.56,24,15,6,58.54,19.84

In [221]:
partnership_dashboard[
    "Partnership"
].head(20).tolist()

['AB de Villiers & V Kohli',
 'B Sai Sudharsan & Shubman Gill',
 'CH Gayle & V Kohli',
 'DA Warner & S Dhawan',
 'F du Plessis & V Kohli',
 'D Padikkal & V Kohli',
 'G Gambhir & RV Uthappa',
 'Abhishek Sharma & TM Head',
 'Ishan Kishan & RG Sharma',
 'KL Rahul & MA Agarwal',
 'MS Dhoni & RA Jadeja',
 'JC Buttler & SV Samson',
 'CH Gayle & KL Rahul',
 'MS Dhoni & SK Raina',
 'PP Shaw & S Dhawan',
 'DA Warner & JM Bairstow',
 'RR Pant & SS Iyer',
 'M Vijay & MEK Hussey',
 'BB McCullum & DR Smith',
 'KA Pollard & RG Sharma']

In [222]:
selected_pairs = [
    "AB de Villiers & V Kohli",
    "DA Warner & S Dhawan"
]

In [223]:
pair_comparison = (
    partnership_dashboard[
        partnership_dashboard[
            "Partnership"
        ].isin(selected_pairs)
    ]
)

pair_comparison

,Partnership,Runs,Balls,Strike Rate,Innings_Together,Average_Partnership,Thirty_Plus,Fifty_Plus,Hundred_Plus,Consistency Index,Boundary %
0,AB de Villiers & V Kohli,3134,2059,152.21,77,40.70,32,21,10,41.56,18.70
3,DA Warner & S Dhawan,2357,1725,136.64,50,47.14,27,20,6,54.00,18.78

In [224]:
comparison_metrics = [
    "Runs",
    "Strike Rate",
    "Average_Partnership",
    "Consistency Index",
    "Boundary %"
]

In [225]:
normalised_comparison = (
    pair_comparison[
        [
            "Partnership",
            *comparison_metrics
        ]
    ]
    .copy()
)

In [226]:
for metric in comparison_metrics:
    metric_min = normalised_comparison[
        metric
    ].min()

    metric_max = normalised_comparison[
        metric
    ].max()

    if metric_max == metric_min:
        normalised_comparison[
            metric
        ] = 100
    else:
        normalised_comparison[
            metric
        ] = (
            (
                normalised_comparison[metric]
                -
                metric_min
            )
            /
            (
                metric_max
                -
                metric_min
            )
            * 100
        ).round(2)

In [227]:
comparison_long = normalised_comparison.melt(
    id_vars="Partnership",
    value_vars=comparison_metrics,
    var_name="Metric",
    value_name="Normalised Score"
)

In [228]:
fig = px.bar(
    comparison_long,
    x="Metric",
    y="Normalised Score",
    color="Partnership",
    barmode="group",
    text="Normalised Score",
    title="Batting Partnership Comparison Dashboard"
)

fig.update_layout(
    yaxis_title="Normalised Score (0–100)"
)

fig.show()

> Normalisation is used only to make metrics with different units visually comparable. The original values should still be used when making cricket-related conclusions.

#### <b>🕸️ Partnership Network Analysis</b>

##### Business Question

How are batters connected through successful partnerships?

In this network:

- Each node represents a batter
- Each edge represents a batting partnership
- Edge thickness represents total partnership runs
- Larger nodes represent greater partnership involvement

Network analysis helps identify central players who build productive combinations with multiple teammates.

In [229]:
network_data = partnership_runs.copy()

network_data[
    [
        "Player_1",
        "Player_2"
    ]
] = network_data[
    "Partnership"
].str.split(
    " & ",
    n=1,
    expand=True
)

In [230]:
network_data = network_data[
    network_data["Runs"] >= 500
].copy()

In [231]:
partnership_graph = nx.Graph()

In [232]:
for _, row in network_data.iterrows():
    partnership_graph.add_edge(
        row["Player_1"],
        row["Player_2"],
        weight=row["Runs"]
    )

In [233]:
positions = nx.spring_layout(
    partnership_graph,
    seed=42,
    k=0.8
)

In [234]:
edge_x = []
edge_y = []

for player_1, player_2 in (
    partnership_graph.edges()
):
    x0, y0 = positions[player_1]
    x1, y1 = positions[player_2]

    edge_x.extend(
        [
            x0,
            x1,
            None
        ]
    )

    edge_y.extend(
        [
            y0,
            y1,
            None
        ]
    )

In [235]:
edge_trace = go.Scatter(
    x=edge_x,
    y=edge_y,
    mode="lines",
    hoverinfo="none",
    line={
        "width": 1
    }
)

In [236]:
node_x = []
node_y = []
node_text = []
node_connections = []

for player in partnership_graph.nodes():
    x, y = positions[player]

    node_x.append(x)
    node_y.append(y)
    node_text.append(player)

    node_connections.append(
        partnership_graph.degree(player)
    )

In [237]:
node_trace = go.Scatter(
    x=node_x,
    y=node_y,
    mode="markers+text",
    text=node_text,
    textposition="top center",
    hovertemplate=(
        "<b>%{text}</b>"
        "<br>Partnership connections: "
        "%{marker.size}<extra></extra>"
    ),
    marker={
        "size": [
            12 + connection * 3
            for connection
            in node_connections
        ],
        "showscale": True,
        "color": node_connections,
        "colorbar": {
            "title": "Connections"
        },
        "line": {
            "width": 1
        }
    }
)

In [238]:
fig = go.Figure(
    data=[
        edge_trace,
        node_trace
    ]
)

fig.update_layout(
    title="IPL Batting Partnership Network",
    showlegend=False,
    hovermode="closest",
    margin={
        "b": 20,
        "l": 20,
        "r": 20,
        "t": 60
    },
    xaxis={
        "showgrid": False,
        "zeroline": False,
        "showticklabels": False
    },
    yaxis={
        "showgrid": False,
        "zeroline": False,
        "showticklabels": False
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Highly connected players have produced substantial partnerships with several teammates.

These players may provide:

- Batting-order flexibility
- Adaptability across team combinations
- Greater stability during squad changes
- Strong long-term value to a franchise

However, network connections measure partnership history, not necessarily individual batting quality.

#### <b>⚠️ Partnership Analysis Limitations</b>

The analysis has several important limitations:

1. Partnership runs include extras because all runs scored while the pair was together contribute to the partnership total.

2. Ball-by-ball data records outcomes but does not measure communication, running quality, or tactical decision-making directly.

3. Players with longer IPL careers naturally have more opportunities to build large cumulative partnerships.

4. Team-name changes and player transfers can divide the history of otherwise related combinations.

5. Strike rate should use legal deliveries only. Wides should not increase the number of balls faced by a partnership.

6. Match situations differ. A 40-run partnership in a difficult chase may be more valuable than a 70-run partnership in favourable conditions.

Future analysis can introduce a context-adjusted partnership impact score.

#### <b>📌 Partnership and Player Combination Analytics Summary</b>

This notebook evaluated IPL batting partnerships using career-level, match-level, season-level, and team-level metrics.

##### Partnership Volume

- Total partnership runs
- Balls together
- Innings together
- Highest match partnership

##### Partnership Efficiency

- Strike rate
- Boundary percentage
- Average partnership

##### Partnership Reliability

- 30+ partnerships
- 50+ partnerships
- 100+ partnerships
- Consistency Index
- Conversion rate

##### Contextual Analysis

- Highest partnership by wicket number
- Best pair by season
- Best pair by team
- Selected team dashboard

##### Relationship Analysis

- Partnership comparison dashboard
- Player partnership network graph

##### <b>Key Conclusion</b>

A successful batting partnership should not be evaluated using total runs alone.

The strongest combinations combine:

- Longevity
- Scoring speed
- Consistency
- Conversion ability
- Match-level impact

### <b>Section 9 – Match Phase & Pressure Analytics</b>

---

#### <b>🎯 Objective</b>

This notebook evaluates team and player performance during different phases of an IPL match.

The analysis includes:

- Powerplay performance
- Middle-over scoring
- Death-over acceleration
- Required run-rate pressure
- Chase pressure
- Close-match analysis
- Clutch players
- Phase comparison dashboard

Understanding phase-wise performance helps teams optimize strategy and player roles.

#### <b>⏱️ Match Phase Classification</b>

##### Business Question

How can every delivery be assigned to a match phase?

An innings is divided into three strategic phases:

- Powerplay (Overs 1–6)
- Middle Overs (Overs 7–15)
- Death Overs (Overs 16–20)

This classification enables phase-wise analysis of batting and bowling performance.

In [239]:
phase_df = deliveries_df.copy()

In [240]:
phase_df["Phase"] = np.select(

    [
        phase_df["over"] < 6,
        phase_df["over"].between(6,14),
        phase_df["over"] >=15
    ],

    [
        "Powerplay",
        "Middle Overs",
        "Death Overs"
    ],

    default="Unknown"

)

In [241]:
phase_df[
    [
        "over",
        "Phase"
    ]
].head()

   over      Phase
0     0  Powerplay
1     0  Powerplay
2     0  Powerplay
3     0  Powerplay
4     0  Powerplay

##### <b>💡 Business Insight</b>

Dividing an innings into phases allows analysts to compare player and team performance under different tactical situations rather than using only match totals.

#### <b>📊 Team Run Rate by Match Phase</b>

##### Business Question

Which teams score the fastest during different phases of the innings?

Run Rate = Runs ÷ Overs

In [242]:
team_phase = (

    phase_df

    .groupby(
        [
            "batting_team",
            "Phase"
        ],
        as_index=False
    )

    .agg(

        Runs=("total_runs","sum"),

        Balls=("is_legal_delivery","sum")

    )

)

team_phase.head()

          batting_team         Phase   Runs  Balls
0  Chennai Super Kings   Death Overs  12392   7145
1  Chennai Super Kings  Middle Overs  18646  14208
2  Chennai Super Kings     Powerplay  12562   9545
3      Deccan Chargers   Death Overs   3133   2032
4      Deccan Chargers  Middle Overs   4913   4020

In [243]:
team_phase["Overs"] = (
    team_phase["Balls"]/6
)

team_phase["Run Rate"] = (
    team_phase["Runs"]/
    team_phase["Overs"]
).round(2)

In [244]:
fig = px.bar(
    team_phase,
    x="batting_team",
    y="Run Rate",
    color="Phase",
    barmode="group",
    title="Run Rate Across Match Phases"
)

fig.show()

##### <b>💡 Business Insight</b>

Some teams prioritize explosive starts during the Powerplay, while others preserve wickets and accelerate during the Death Overs.

Comparing run rates across phases reveals each team's batting strategy.

#### <b>📈 Average Runs Scored Per Over</b>

##### Business Question

Which overs produce the highest scoring?

This helps identify natural acceleration points during an innings.

In [245]:
over_summary = (

    phase_df

    .groupby(
        "over",
        as_index=False
    )

    .agg(

        Runs=("total_runs","sum"),

        Balls=("is_legal_delivery","sum")

    )

)

In [246]:
over_summary["Overs"] = (
    over_summary["Balls"]/6
)

over_summary["Run Rate"] = (
    over_summary["Runs"]/
    over_summary["Overs"]
).round(2)

In [247]:
fig = px.line(
    over_summary,
    x="over",
    y="Run Rate",
    markers=True,
    title="Average Run Rate by Over"
)

fig.show()

##### <b>💡 Business Insight</b>

Run rates typically increase significantly during the final overs because batting teams become more aggressive while attempting to maximize their total.

#### <b>🎯 Wickets Lost by Match Phase</b>

##### Business Question

During which phase do teams lose the most wickets?

In [248]:
phase_wickets = (

    phase_df[
        phase_df["is_bowler_wicket"]==True
    ]

    .groupby(
        "Phase",
        as_index=False
    )

    .size()

)

phase_wickets.rename(
    columns={
        "size":"Wickets"
    },
    inplace=True
)

In [249]:
fig = px.pie(

    phase_wickets,

    names="Phase",

    values="Wickets",

    hole=.4,

    title="Distribution of Wickets by Match Phase"

)

fig.show()

##### <b>💡 Business Insight</b>

Death overs usually contain more wickets because batters play aggressively in pursuit of boundaries, increasing dismissal risk.

#### <b>⚡ Powerplay Specialists</b>

##### Business Question

Which batters score the most runs during the Powerplay?

In [250]:
powerplay = phase_df[
    phase_df["Phase"]=="Powerplay"
]

In [251]:
powerplay_batters = (

    powerplay

    .groupby(
        "batter",
        as_index=False
    )["batter_runs"]

    .sum()

)

powerplay_batters.rename(
    columns={
        "batter_runs":"Runs"
    },
    inplace=True
)

powerplay_batters.sort_values(
    "Runs",
    ascending=False,
    inplace=True
)

powerplay_batters.head(10)

           batter  Runs
365       V Kohli  3487
294      S Dhawan  3415
81      DA Warner  3318
31      AM Rahane  2759
275     RG Sharma  2566
159      KL Rahul  2437
71       CH Gayle  2405
107  F du Plessis  2281
110     G Gambhir  2277
343  Shubman Gill  2044

In [252]:
fig = px.bar(

    powerplay_batters.head(10),

    x="Runs",

    y="batter",

    orientation="h",

    color="Runs",

    text="Runs",

    title="Top Powerplay Batters"

)

fig.show()

##### <b>💡 Business Insight</b>

Powerplay specialists maximize fielding restrictions and provide fast starts, creating momentum for the rest of the innings.

#### <b>🏏 Middle Over Anchors</b>

##### Business Question

Which batters consistently score during the middle overs?

Middle-over batters rotate strike, stabilize innings, and prepare for the final acceleration.

In [253]:
middle = phase_df[
    phase_df["Phase"]=="Middle Overs"
]

In [254]:
middle_batters = (

    middle

    .groupby(
        "batter",
        as_index=False
    )["batter_runs"]

    .sum()

)

middle_batters.rename(
    columns={
        "batter_runs":"Runs"
    },
    inplace=True
)

middle_batters.sort_values(
    "Runs",
    ascending=False,
    inplace=True
)

middle_batters.head(10)

             batter  Runs
540         V Kohli  4286
410       RG Sharma  3238
464        SK Raina  3077
452        SA Yadav  2730
489       SV Samson  2710
440        S Dhawan  2686
124       DA Warner  2621
24   AB de Villiers  2572
236      KD Karthik  2542
242        KL Rahul  2484

In [255]:
fig = px.bar(

    middle_batters.head(10),

    x="Runs",

    y="batter",

    orientation="h",

    color="Runs",

    text="Runs",

    title="Top Middle Over Batters"

)

fig.show()

#### <b>🔥 Death-Over Batting Specialists</b>

##### Business Question

Which batters are most effective during the Death Overs?

Death-over batting requires:

- Boundary-hitting ability
- Fast scoring
- Ability to handle yorkers and slower balls
- Strong performance under scoreboard pressure

Batters are compared using:

- Runs
- Balls faced
- Strike rate
- Boundary percentage
- Dot-ball percentage

In [256]:
death_batting_df = phase_df[
    phase_df["Phase"] == "Death Overs"
].copy()

In [257]:
death_batting_df["Batter_Ball"] = (
    death_batting_df["is_legal_delivery"]
    .fillna(False)
    .astype(int)
)

In [258]:
death_batter_stats = (
    death_batting_df
    .groupby(
        "batter",
        as_index=False
    )
    .agg(
        Runs=("batter_runs", "sum"),
        Balls=("Batter_Ball", "sum"),
        Boundaries=("is_boundary", "sum"),
        Dot_Balls=(
            "batter_runs",
            lambda runs: (runs == 0).sum()
        )
    )
)

In [259]:
death_batter_stats["Strike Rate"] = np.where(
    death_batter_stats["Balls"] > 0,
    (
        death_batter_stats["Runs"]
        /
        death_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

death_batter_stats["Boundary %"] = np.where(
    death_batter_stats["Balls"] > 0,
    (
        death_batter_stats["Boundaries"]
        /
        death_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

death_batter_stats["Dot Ball %"] = np.where(
    death_batter_stats["Balls"] > 0,
    (
        death_batter_stats["Dot_Balls"]
        /
        death_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

In [260]:
qualified_death_batters = (
    death_batter_stats[
        death_batter_stats["Balls"] >= 120
    ]
    .sort_values(
        "Strike Rate",
        ascending=False
    )
)

qualified_death_batters.head(10)

,batter,Runs,Balls,Boundaries,Dot_Balls,Strike Rate,Boundary %,Dot Ball %
28,AB de Villiers,1868,829,275,204,225.33,33.17,24.61
314,LS Livingstone,345,156,52,59,221.15,33.33,37.82
478,RM Patidar,267,124,42,47,215.32,33.87,37.90
92,B Sai Sudharsan,308,146,45,34,210.96,30.82,23.29
118,CH Gayle,581,280,89,99,207.50,31.79,35.36
333,MA Agarwal,252,122,36,23,206.56,29.51,18.85
483,RR Pant,1095,537,171,187,203.91,31.84,34.82
607,Tilak Varma,543,272,81,91,199.63,29.78,33.46
592,T Stubbs,546,274,76,57,199.27,27.74,20.80
597,TH David,843,426,119,159,197.89,27.93,37.32

In [261]:
fig = px.scatter(
    qualified_death_batters,
    x="Strike Rate",
    y="Runs",
    size="Balls",
    color="Boundary %",
    hover_name="batter",
    hover_data=[
        "Dot Ball %",
        "Boundaries"
    ],
    title="Death-Over Batting Specialists"
)

fig.update_layout(
    xaxis_title="Death-Over Strike Rate",
    yaxis_title="Death-Over Runs"
)

fig.show()

##### <b>💡 Business Insight</b>

An effective finisher should combine scoring speed with sufficient volume.

A batter with an extremely high strike rate from only a few deliveries may not be as reliable as one who has maintained a strong strike rate across many innings.

#### <b>⭐ Death-Over Finisher Score</b>

##### Business Question

How can multiple death-over batting metrics be combined into one score?

The Finisher Score combines:

- Strike rate
- Boundary percentage
- Low dot-ball percentage
- Run volume

The score is designed for comparative analysis, not as an official cricket statistic.

In [262]:
finisher_df = qualified_death_batters.copy()

In [263]:
def min_max_scale(series):
    minimum = series.min()
    maximum = series.max()

    if maximum == minimum:
        return pd.Series(
            100,
            index=series.index
        )

    return (
        (series - minimum)
        /
        (maximum - minimum)
        * 100
    )

In [264]:
finisher_df["SR_Score"] = min_max_scale(
    finisher_df["Strike Rate"]
)

finisher_df["Boundary_Score"] = min_max_scale(
    finisher_df["Boundary %"]
)

finisher_df["Run_Score"] = min_max_scale(
    finisher_df["Runs"]
)

finisher_df["Dot_Control_Score"] = (
    100
    -
    min_max_scale(
        finisher_df["Dot Ball %"]
    )
)

In [265]:
finisher_df["Finisher Score"] = (
    finisher_df["SR_Score"] * 0.35
    +
    finisher_df["Boundary_Score"] * 0.25
    +
    finisher_df["Dot_Control_Score"] * 0.20
    +
    finisher_df["Run_Score"] * 0.20
).round(2)

In [266]:
top_finishers = (
    finisher_df
    .sort_values(
        "Finisher Score",
        ascending=False
    )
    .head(10)
)

top_finishers[
    [
        "batter",
        "Runs",
        "Balls",
        "Strike Rate",
        "Boundary %",
        "Dot Ball %",
        "Finisher Score"
    ]
]

,batter,Runs,Balls,Strike Rate,Boundary %,Dot Ball %,Finisher Score
28,AB de Villiers,1868,829,225.33,33.17,24.61,87.05
92,B Sai Sudharsan,308,146,210.96,30.82,23.29,72.34
333,MA Agarwal,252,122,206.56,29.51,18.85,71.65
314,LS Livingstone,345,156,221.15,33.33,37.82,70.86
483,RR Pant,1095,537,203.91,31.84,34.82,70.84
363,MS Dhoni,3468,1965,176.49,23.41,32.57,70.54
478,RM Patidar,267,124,215.32,33.87,37.90,69.42
592,T Stubbs,546,274,199.27,27.74,20.80,68.83
118,CH Gayle,581,280,207.50,31.79,35.36,68.39
613,V Kohli,1573,830,189.52,25.54,27.95,66.89

In [267]:
fig = px.bar(
    top_finishers,
    x="Finisher Score",
    y="batter",
    orientation="h",
    color="Finisher Score",
    text="Finisher Score",
    hover_data=[
        "Runs",
        "Balls",
        "Strike Rate",
        "Boundary %",
        "Dot Ball %"
    ],
    title="Top IPL Finishers"
)

fig.update_layout(
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

> The metric weights are business assumptions. They should be documented and tested using sensitivity analysis before being used for selection decisions.

#### <b>🎯 Death-Over Bowling Specialists</b>

##### Business Question

Which bowlers control scoring most effectively during the Death Overs?

Death-over bowlers are evaluated using:

- Balls bowled
- Runs conceded
- Wickets
- Economy rate
- Bowling strike rate
- Dot-ball percentage
- Boundary concession percentage

In [268]:
death_bowling_df = phase_df[
    phase_df["Phase"] == "Death Overs"
].copy()

In [269]:
death_bowling_stats = (
    death_bowling_df
    .groupby(
        "bowler",
        as_index=False
    )
    .agg(
        Balls=("is_legal_delivery", "sum"),
        Runs_Conceded=("total_runs", "sum"),
        Wickets=("is_bowler_wicket", "sum"),
        Dot_Balls=(
            "total_runs",
            lambda runs: (runs == 0).sum()
        ),
        Boundaries_Conceded=("is_boundary", "sum")
    )
)

In [270]:
death_bowling_stats["Overs"] = (
    death_bowling_stats["Balls"] / 6
)

death_bowling_stats["Economy"] = np.where(
    death_bowling_stats["Overs"] > 0,
    (
        death_bowling_stats["Runs_Conceded"]
        /
        death_bowling_stats["Overs"]
    ),
    np.nan
).round(2)

death_bowling_stats["Bowling Strike Rate"] = np.where(
    death_bowling_stats["Wickets"] > 0,
    (
        death_bowling_stats["Balls"]
        /
        death_bowling_stats["Wickets"]
    ),
    np.nan
).round(2)

death_bowling_stats["Dot Ball %"] = np.where(
    death_bowling_stats["Balls"] > 0,
    (
        death_bowling_stats["Dot_Balls"]
        /
        death_bowling_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

death_bowling_stats["Boundary Concession %"] = np.where(
    death_bowling_stats["Balls"] > 0,
    (
        death_bowling_stats["Boundaries_Conceded"]
        /
        death_bowling_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

In [271]:
qualified_death_bowlers = (
    death_bowling_stats[
        death_bowling_stats["Balls"] >= 120
    ]
    .sort_values(
        "Economy",
        ascending=True
    )
)

qualified_death_bowlers.head(10)

,bowler,Balls,Runs_Conceded,Wickets,Dot_Balls,Boundaries_Conceded,Overs,Economy,Bowling Strike Rate,Dot Ball %,Boundary Concession %
405,SP Narine,1105,1365,84,413,141,184.166667,7.41,13.15,37.38,12.76
111,DE Bollinger,234,297,23,88,30,39.000000,7.62,10.17,37.61,12.82
6,A Kumble,167,217,17,58,23,27.833333,7.80,9.82,34.73,13.77
239,M Kartik,154,207,6,29,18,25.666667,8.06,25.67,18.83,11.69
121,DL Vettori,165,223,7,49,25,27.500000,8.11,23.57,29.70,15.15
397,SL Malinga,1117,1526,108,350,154,186.166667,8.20,10.34,31.33,13.79
151,Harmeet Singh,129,178,10,46,20,21.500000,8.28,12.90,35.66,15.50
243,M Muralitharan,275,380,22,103,43,45.833333,8.29,12.50,37.45,15.64
327,R Ashwin,601,834,36,178,76,100.166667,8.33,16.69,29.62,12.65
344,RD Chahar,170,237,14,55,24,28.333333,8.36,12.14,32.35,14.12

In [272]:
fig = px.scatter(
    qualified_death_bowlers,
    x="Economy",
    y="Wickets",
    size="Balls",
    color="Dot Ball %",
    hover_name="bowler",
    hover_data=[
        "Bowling Strike Rate",
        "Boundary Concession %"
    ],
    title="Death-Over Bowling Specialists"
)

fig.update_layout(
    xaxis_title="Death-Over Economy Rate",
    yaxis_title="Death-Over Wickets"
)

fig.show()

##### <b>💡 Business Insight</b>

The best death-over bowlers combine wicket-taking ability with scoring control.

Economy alone may be misleading because a bowler may concede runs while still taking strategically important wickets.

#### <b>📊 Create Innings Context</b>

Required-run-rate analysis requires match-level target information.

For each innings, we calculate:

- Total innings runs
- Target for the second innings
- Runs required before each delivery
- Balls remaining
- Required run rate
- Current run rate

In [273]:
innings_totals = (
    phase_df
    .groupby(
        [
            "match_id",
            "innings",
            "batting_team"
        ],
        as_index=False
    )
    .agg(
        Innings_Runs=("total_runs", "sum")
    )
)

innings_totals.head()

   match_id  innings                 batting_team  Innings_Runs
0    335982        1        Kolkata Knight Riders           222
1    335982        2  Royal Challengers Bangalore            82
2    335983        1          Chennai Super Kings           240
3    335983        2              Kings XI Punjab           207
4    335984        1             Rajasthan Royals           129

In [274]:
first_innings_targets = (
    innings_totals[
        innings_totals["innings"] == 1
    ][
        [
            "match_id",
            "Innings_Runs"
        ]
    ]
    .rename(
        columns={
            "Innings_Runs": "First_Innings_Runs"
        }
    )
)

first_innings_targets["Target"] = (
    first_innings_targets["First_Innings_Runs"]
    + 1
)

In [275]:
pressure_df = (
    phase_df
    .merge(
        first_innings_targets[
            [
                "match_id",
                "Target"
            ]
        ],
        on="match_id",
        how="left"
    )
    .sort_values(
        [
            "match_id",
            "innings",
            "over",
            "ball"
        ]
    )
    .copy()
)

#### <b>📈 Required Run Rate Analysis</b>

##### Business Question

How does chase pressure change during the second innings?

Required Run Rate is calculated as:

Required Run Rate = Runs Required ÷ Overs Remaining

This metric shows how quickly the chasing team must score to reach the target.

In [276]:
chase_df = pressure_df[
    pressure_df["innings"] == 2
].copy()

In [277]:
chase_df["Runs_Before_Ball"] = (
    chase_df
    .groupby("match_id")["total_runs"]
    .cumsum()
    -
    chase_df["total_runs"]
)

In [278]:
chase_df["Legal_Balls_Before"] = (
    chase_df
    .groupby("match_id")["is_legal_delivery"]
    .cumsum()
    -
    chase_df["is_legal_delivery"]
)

In [279]:
chase_df["Runs_Required"] = (
    chase_df["Target"]
    -
    chase_df["Runs_Before_Ball"]
)

chase_df["Balls_Remaining"] = (
    120
    -
    chase_df["Legal_Balls_Before"]
)

In [280]:
chase_df["Required Run Rate"] = np.where(
    chase_df["Balls_Remaining"] > 0,
    (
        chase_df["Runs_Required"]
        /
        chase_df["Balls_Remaining"]
        * 6
    ),
    np.nan
).round(2)

In [281]:
chase_df["Current Run Rate"] = np.where(
    chase_df["Legal_Balls_Before"] > 0,
    (
        chase_df["Runs_Before_Ball"]
        /
        chase_df["Legal_Balls_Before"]
        * 6
    ),
    0
).round(2)

In [282]:
chase_df["Run Rate Pressure"] = (
    chase_df["Required Run Rate"]
    -
    chase_df["Current Run Rate"]
).round(2)

> The calculation assumes a normal 20-over innings. Rain-reduced matches and revised targets require the actual innings-ball limit and official revised target.

#### <b>🚨 Chase Pressure Classification</b>

##### Business Question

How can different levels of chase pressure be classified?

For this project, pressure is classified using required run rate:

- Low Pressure: below 7 runs per over
- Moderate Pressure: 7 to below 10
- High Pressure: 10 to below 13
- Extreme Pressure: 13 or more

These boundaries are analytical assumptions and may be adjusted.

In [283]:
chase_df["Pressure Level"] = pd.cut(
    chase_df["Required Run Rate"],
    bins=[
        -np.inf,
        7,
        10,
        13,
        np.inf
    ],
    labels=[
        "Low Pressure",
        "Moderate Pressure",
        "High Pressure",
        "Extreme Pressure"
    ],
    right=False
)

In [284]:
chase_df[
    [
        "match_id",
        "over",
        "ball",
        "batting_team",
        "Target",
        "Runs_Before_Ball",
        "Runs_Required",
        "Balls_Remaining",
        "Current Run Rate",
        "Required Run Rate",
        "Pressure Level"
    ]
].head(20)

,match_id,over,ball,batting_team,Target,Runs_Before_Ball,Runs_Required,Balls_Remaining,Current Run Rate,Required Run Rate,Pressure Level
159258,335982,0,0.1,Royal Challengers Bangalore,223,0,223,120,0.00,11.15,High Pressure
159259,335982,0,0.2,Royal Challengers Bangalore,223,1,222,119,6.00,11.19,High Pressure
159260,335982,0,0.3,Royal Challengers Bangalore,223,2,221,119,12.00,11.14,High Pressure
159261,335982,0,0.4,Royal Challengers Bangalore,223,2,221,118,6.00,11.24,High Pressure
159262,335982,0,0.5,Royal Challengers Bangalore,223,3,220,117,6.00,11.28,High Pressure
159263,335982,0,0.6,Royal Challengers Bangalore,223,4,219,116,6.00,11.33,High Pressure
159264,335982,0,0.7,Royal Challengers Bangalore,223,4,219,115,4.80,11.43,High Pressure
159265,335982,1,1.1,Royal Challengers Bangalore,223,4,219,114,4.00,11.53,High Pressure
159266,335982,1,1.2,Royal Challengers Bangalore,223,4,219,113,3.43,11.63,High Pressure
159267,335982,1,1.3,Royal Challengers Bangalore,223,4,219,112,3.00,11.73,High Pressure
159268,335982,1,1.4,Royal Challengers Bangalore,223,8,215,111,5.33,11.62,High Pressure
159269,335982,1,1.5,Royal Challengers Bangalore,223,9,214,110,5.40,11.67,High Pressure
159270,335982,1,1.6,Royal Challengers Bangalore,223,9,214,109,4.91,11.78,High Pressure
159271,335982,2,2.1,Royal Challengers Bangalore,223,9,214,108,4.50,11.89,High Pressure
159272,335982,2,2.2,Royal Challengers Bangalore,223,9,214,107,4.15,12.00,High Pressure
159273,335982,2,2.3,Royal Challengers Bangalore,223,9,214,106,3.86,12.11,High Pressure
159274,335982,2,2.4,Royal Challengers Bangalore,223,10,213,105,4.00,12.17,High Pressure
159275,335982,2,2.5,Royal Challengers Bangalore,223,10,213,104,3.75,12.29,High Pressure
159276,335982,2,2.6,Royal Challengers Bangalore,223,11,212,104,4.12,12.23,High Pressure
159277,335982,2,2.7,Royal Challengers Bangalore,223,11,212,103,3.88,12.35,High Pressure

In [285]:
pressure_distribution = (
    chase_df["Pressure Level"]
    .value_counts()
    .reset_index()
)

pressure_distribution.columns = [
    "Pressure Level",
    "Deliveries"
]

fig = px.bar(
    pressure_distribution,
    x="Pressure Level",
    y="Deliveries",
    color="Pressure Level",
    text="Deliveries",
    title="Distribution of Chase Pressure"
)

fig.show()

#### <b>⚔️ Team Performance Under High Pressure</b>

##### Business Question

Which teams score most efficiently when the required run rate is high?

High-pressure situations are defined as deliveries where the required run rate is at least 10 runs per over.

In [286]:
high_pressure_df = chase_df[
    chase_df["Required Run Rate"] >= 10
].copy()

In [287]:
team_pressure_batting = (
    high_pressure_df
    .groupby(
        "batting_team",
        as_index=False
    )
    .agg(
        Runs=("total_runs", "sum"),
        Balls=("is_legal_delivery", "sum"),
        Wickets_Lost=("is_wicket", "sum")
    )
)

In [288]:
team_pressure_batting["Run Rate"] = np.where(
    team_pressure_batting["Balls"] > 0,
    (
        team_pressure_batting["Runs"]
        /
        team_pressure_batting["Balls"]
        * 6
    ),
    np.nan
).round(2)

team_pressure_batting["Runs per Wicket"] = np.where(
    team_pressure_batting["Wickets_Lost"] > 0,
    (
        team_pressure_batting["Runs"]
        /
        team_pressure_batting["Wickets_Lost"]
    ),
    np.nan
).round(2)

In [289]:
qualified_pressure_teams = (
    team_pressure_batting[
        team_pressure_batting["Balls"] >= 300
    ]
    .sort_values(
        "Run Rate",
        ascending=False
    )
)

qualified_pressure_teams

,batting_team,Runs,Balls,Wickets_Lost,Run Rate,Runs per Wicket
12,Punjab Kings,3530,2018,113,10.50,31.24
5,Gujarat Titans,3625,2190,127,9.93,28.54
14,Rising Pune Supergiants,783,495,32,9.49,24.47
0,Chennai Super Kings,7463,4738,286,9.45,26.09
9,Lucknow Super Giants,3020,1922,129,9.43,23.41
10,Mumbai Indians,9522,6094,410,9.38,23.22
13,Rajasthan Royals,8785,5735,393,9.19,22.35
8,Kolkata Knight Riders,7470,4897,347,9.15,21.53
2,Delhi Capitals,5118,3392,233,9.05,21.97
16,Sunrisers Hyderabad,6333,4250,291,8.94,21.76
15,Royal Challengers Bangalore,8747,5949,398,8.82,21.98
6,Kings XI Punjab,5861,4068,273,8.64,21.47
3,Delhi Daredevils,4591,3257,235,8.46,19.54
4,Gujarat Lions,567,411,26,8.28,21.81
1,Deccan Chargers,1604,1190,99,8.09,16.20
11,Pune Warriors,1410,1104,80,7.66,17.62

In [290]:
fig = px.scatter(
    qualified_pressure_teams,
    x="Run Rate",
    y="Runs per Wicket",
    size="Balls",
    hover_name="batting_team",
    title="Team Batting Performance Under High Chase Pressure"
)

fig.update_layout(
    xaxis_title="Scoring Rate Under Pressure",
    yaxis_title="Runs per Wicket Under Pressure"
)

fig.show()

##### <b>💡 Business Insight</b>

A strong pressure team should score quickly without losing wickets excessively.

Run rate and wicket preservation should therefore be evaluated together.

#### <b>🏃 Batter Performance Under Chase Pressure</b>

##### Business Question

Which batters perform best when the required run rate is at least 10?

These players are evaluated through:

- Pressure runs
- Balls faced
- Strike rate
- Boundary percentage
- Dot-ball percentage

In [291]:
high_pressure_df["Batter_Ball"] = (
    high_pressure_df["is_legal_delivery"]
    .fillna(False)
    .astype(int)
)

In [292]:
pressure_batter_stats = (
    high_pressure_df
    .groupby(
        "batter",
        as_index=False
    )
    .agg(
        Runs=("batter_runs", "sum"),
        Balls=("Batter_Ball", "sum"),
        Boundaries=("is_boundary", "sum"),
        Dot_Balls=(
            "batter_runs",
            lambda runs: (runs == 0).sum()
        )
    )
)

In [293]:
pressure_batter_stats["Strike Rate"] = np.where(
    pressure_batter_stats["Balls"] > 0,
    (
        pressure_batter_stats["Runs"]
        /
        pressure_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

pressure_batter_stats["Boundary %"] = np.where(
    pressure_batter_stats["Balls"] > 0,
    (
        pressure_batter_stats["Boundaries"]
        /
        pressure_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

pressure_batter_stats["Dot Ball %"] = np.where(
    pressure_batter_stats["Balls"] > 0,
    (
        pressure_batter_stats["Dot_Balls"]
        /
        pressure_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

In [294]:
qualified_pressure_batters = (
    pressure_batter_stats[
        pressure_batter_stats["Balls"] >= 100
    ]
    .sort_values(
        "Strike Rate",
        ascending=False
    )
)

qualified_pressure_batters.head(10)

,batter,Runs,Balls,Boundaries,Dot_Balls,Strike Rate,Boundary %,Dot Ball %
447,RD Rickelton,247,120,42,43,205.83,35.00,35.83
573,TH David,360,184,49,63,195.65,26.63,34.24
218,JA Morkel,343,185,45,49,185.41,24.32,26.49
300,LS Livingstone,205,111,29,40,184.68,26.13,36.04
110,C Connolly,197,109,29,38,180.73,26.61,34.86
615,YK Pathan,686,380,96,120,180.53,25.26,31.58
81,Ashutosh Sharma,284,158,41,59,179.75,25.95,37.34
455,RK Singh,431,240,63,85,179.58,26.25,35.42
471,Rashid Khan,360,201,54,95,179.10,26.87,47.26
368,N Pooran,683,383,98,152,178.33,25.59,39.69

In [295]:
fig = px.scatter(
    qualified_pressure_batters,
    x="Strike Rate",
    y="Runs",
    size="Balls",
    color="Boundary %",
    hover_name="batter",
    hover_data=[
        "Dot Ball %"
    ],
    title="Batters Under High Required-Run-Rate Pressure"
)

fig.show()

##### <b>💡 Business Insight</b>

Batters who maintain high strike rates across a substantial number of pressure deliveries are valuable chase specialists.

However, this metric should eventually be adjusted for venue, bowling quality, wickets remaining, and target difficulty.

#### <b>🔍 Close-Match Identification</b>

##### Business Question

Which matches can be classified as close contests?

For this analysis:

- A runs victory is close when the winning margin is 10 runs or fewer
- A wickets victory is close when the winning margin is 3 wickets or fewer

These thresholds are analytical assumptions.

In [296]:
matches_df[
    [
        "match_id",
        "winner",
        "win_by_runs",
        "win_by_wickets"
    ]
].head()

   match_id                       winner  win_by_runs  win_by_wickets
0   1082591          Sunrisers Hyderabad           35               0
1   1082592      Rising Pune Supergiants            0               7
2   1082593        Kolkata Knight Riders            0              10
3   1082594              Kings XI Punjab            0               6
4   1082595  Royal Challengers Bangalore           15               0

In [297]:
matches_df["Is_Close_Match"] = (
    (
        matches_df["win_by_runs"].between(1, 10)
    )
    |
    (
        matches_df["win_by_wickets"].between(1, 3)
    )
)

In [298]:
close_matches = matches_df[
    matches_df["Is_Close_Match"]
].copy()

print(
    "Number of close matches:",
    close_matches.shape[0]
)

Number of close matches: 184

In [299]:
matches_df["Is_Close_Match"].value_counts()

Is_Close_Match
False    1059
True      184
Name: count, dtype: int64

In [300]:
close_matches = matches_df[
    matches_df["Is_Close_Match"]
].copy()

print(f"Total Close Matches: {close_matches.shape[0]}")

Total Close Matches: 184

In [301]:
close_matches[
    [
        "season",
        "team_1",
        "team_2",
        "winner",
        "win_by_runs",
        "win_by_wickets"
    ]
].head(20)

,season,team_1,team_2,winner,win_by_runs,win_by_wickets
18,2017,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,5,0
27,2017,Mumbai Indians,Rising Pune Supergiants,Rising Pune Supergiants,3,0
48,2017,Gujarat Lions,Delhi Daredevils,Delhi Daredevils,0,2
49,2017,Mumbai Indians,Kings XI Punjab,Kings XI Punjab,7,0
50,2017,Delhi Daredevils,Rising Pune Supergiants,Delhi Daredevils,7,0
52,2017,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,9,0
54,2017,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,10,0
58,2017,Mumbai Indians,Rising Pune Supergiants,Mumbai Indians,1,0
59,2018,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,0,1
64,2018,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals,10,0
65,2018,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,0,1
70,2018,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,4,0
78,2018,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,4,0
79,2018,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,0,3
80,2018,Kings XI Punjab,Delhi Daredevils,Kings XI Punjab,4,0
90,2018,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils,4,0
97,2018,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,5,0
108,2018,Mumbai Indians,Kings XI Punjab,Mumbai Indians,3,0
115,2018,Sunrisers Hyderabad,Chennai Super Kings,Chennai Super Kings,0,2
125,2019,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,6,0

In [302]:
close_match_summary = (
    matches_df["Is_Close_Match"]
    .value_counts()
    .rename_axis("Close Match")
    .reset_index(name="Matches")
)

fig = px.pie(
    close_match_summary,
    names="Close Match",
    values="Matches",
    hole=0.4,
    title="Distribution of Close vs Non-Close IPL Matches"
)

fig.show()

##### <b>💡 Business Insight</b>

Close matches highlight teams' ability to perform under pressure.

Success in these matches often depends on:

- Death-over batting
- Death-over bowling
- Captaincy decisions
- Fielding under pressure
- Finishing ability

These matches provide valuable data for identifying clutch performers and high-pressure strategies.

#### <b>🏆 Team Performance in Close Matches</b>

##### Business Question

Which teams win most frequently in close contests?

Close-match performance can indicate:

- Decision-making under pressure
- Quality of finishers
- Death-bowling strength
- Captaincy and tactical execution

In [303]:
team_1_close = close_matches[
    [
        "match_id",
        "team_1",
        "winner"
    ]
].rename(
    columns={
        "team_1": "team"
    }
)

team_2_close = close_matches[
    [
        "match_id",
        "team_2",
        "winner"
    ]
].rename(
    columns={
        "team_2": "team"
    }
)

close_team_records = pd.concat(
    [
        team_1_close,
        team_2_close
    ],
    ignore_index=True
)

In [304]:
close_team_records["Win"] = (
    close_team_records["team"]
    ==
    close_team_records["winner"]
).astype(int)

In [305]:
close_team_summary = (
    close_team_records
    .groupby(
        "team",
        as_index=False
    )
    .agg(
        Close_Matches=("match_id", "nunique"),
        Close_Wins=("Win", "sum")
    )
)

close_team_summary["Close Match Win %"] = (
    close_team_summary["Close_Wins"]
    /
    close_team_summary["Close_Matches"]
    * 100
).round(2)

In [306]:
qualified_close_teams = (
    close_team_summary[
        close_team_summary["Close_Matches"] >= 10
    ]
    .sort_values(
        "Close Match Win %",
        ascending=False
    )
)

qualified_close_teams

                           team  Close_Matches  Close_Wins  Close Match Win %
9          Lucknow Super Giants             14          10              71.43
16          Sunrisers Hyderabad             28          17              60.71
13             Rajasthan Royals             40          24              60.00
15  Royal Challengers Bangalore             35          21              60.00
2                Delhi Capitals             15           8              53.33
6               Kings XI Punjab             27          14              51.85
12                 Punjab Kings             16           8              50.00
5                Gujarat Titans             16           8              50.00
10               Mumbai Indians             39          18              46.15
0           Chennai Super Kings             36          16              44.44
8         Kolkata Knight Riders             48          20              41.67
1               Deccan Chargers             13           5              38.46
3              Delhi Daredevils             26           9              34.62

In [307]:
fig = px.bar(
    qualified_close_teams,
    x="Close Match Win %",
    y="team",
    orientation="h",
    color="Close Match Win %",
    text="Close Match Win %",
    hover_data=[
        "Close_Matches",
        "Close_Wins"
    ],
    title="Team Success in Close IPL Matches"
)

fig.update_layout(
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Teams with strong close-match records may possess superior finishing, death bowling, and tactical execution.

Nevertheless, close-match win percentage can be volatile, so sample size must be considered.

#### <b>⭐ Clutch Batting in Close Matches</b>

##### Business Question

Which batters score effectively during the final five overs of close matches?

For this analysis, clutch batting is defined as batting:

- In a match classified as close
- During the Death Overs

This is a practical proxy for pressure performance.

In [308]:
close_match_ids = close_matches[
    "match_id"
].unique()

In [309]:
clutch_batting_df = phase_df[
    phase_df["match_id"].isin(close_match_ids)
    &
    phase_df["Phase"].eq("Death Overs")
].copy()

In [310]:
clutch_batting_df["Batter_Ball"] = (
    clutch_batting_df["is_legal_delivery"]
    .fillna(False)
    .astype(int)
)

In [311]:
clutch_batter_stats = (
    clutch_batting_df
    .groupby(
        "batter",
        as_index=False
    )
    .agg(
        Clutch_Runs=("batter_runs", "sum"),
        Balls=("Batter_Ball", "sum"),
        Boundaries=("is_boundary", "sum")
    )
)

clutch_batter_stats["Clutch Strike Rate"] = np.where(
    clutch_batter_stats["Balls"] > 0,
    (
        clutch_batter_stats["Clutch_Runs"]
        /
        clutch_batter_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

In [312]:
qualified_clutch_batters = (
    clutch_batter_stats[
        clutch_batter_stats["Balls"] >= 60
    ]
    .sort_values(
        "Clutch Strike Rate",
        ascending=False
    )
)

qualified_clutch_batters.head(10)

              batter  Clutch_Runs  Balls  Boundaries  Clutch Strike Rate
47   Ashutosh Sharma          176     71          27              247.89
289         RK Singh          252    109          40              231.19
379          V Kohli          137     60          21              228.33
123        H Klaasen          160     71          21              225.35
20    AB de Villiers          338    150          48              225.33
293          RR Pant          185     86          28              215.12
345        SV Samson          130     63          19              206.35
152        JP Duminy          179     89          21              201.12
74         CH Morris          158     79          19              200.00
368         TH David          173     87          25              198.85

In [313]:
fig = px.scatter(
    qualified_clutch_batters,
    x="Clutch Strike Rate",
    y="Clutch_Runs",
    size="Balls",
    color="Boundaries",
    hover_name="batter",
    title="Clutch Batting in Close Matches"
)

fig.show()

#### <b>🧠 Clutch Bowling in Close Matches</b>

##### Business Question

Which bowlers perform best during the Death Overs of close matches?

Clutch bowling is evaluated through:

- Economy
- Wickets
- Dot-ball percentage
- Boundary concession percentage

In [314]:
clutch_bowling_stats = (
    clutch_batting_df
    .groupby(
        "bowler",
        as_index=False
    )
    .agg(
        Balls=("is_legal_delivery", "sum"),
        Runs_Conceded=("total_runs", "sum"),
        Wickets=("is_bowler_wicket", "sum"),
        Dot_Balls=(
            "total_runs",
            lambda runs: (runs == 0).sum()
        ),
        Boundaries_Conceded=("is_boundary", "sum")
    )
)

In [315]:
clutch_bowling_stats["Economy"] = np.where(
    clutch_bowling_stats["Balls"] > 0,
    (
        clutch_bowling_stats["Runs_Conceded"]
        /
        clutch_bowling_stats["Balls"]
        * 6
    ),
    np.nan
).round(2)

clutch_bowling_stats["Dot Ball %"] = np.where(
    clutch_bowling_stats["Balls"] > 0,
    (
        clutch_bowling_stats["Dot_Balls"]
        /
        clutch_bowling_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

clutch_bowling_stats[
    "Boundary Concession %"
] = np.where(
    clutch_bowling_stats["Balls"] > 0,
    (
        clutch_bowling_stats[
            "Boundaries_Conceded"
        ]
        /
        clutch_bowling_stats["Balls"]
        * 100
    ),
    np.nan
).round(2)

In [316]:
qualified_clutch_bowlers = (
    clutch_bowling_stats[
        clutch_bowling_stats["Balls"] >= 60
    ]
    .sort_values(
        [
            "Economy",
            "Wickets"
        ],
        ascending=[
            True,
            False
        ]
    )
)

qualified_clutch_bowlers.head(10)

,bowler,Balls,Runs_Conceded,Wickets,Dot_Balls,Boundaries_Conceded,Economy,Dot Ball %,Boundary Concession %
235,Rashid Khan,126,168,10,51,20,8.00,40.48,15.87
64,CV Varun,96,128,4,35,13,8.00,36.46,13.54
120,JJ Bumrah,234,318,21,75,34,8.15,32.05,14.53
213,R Ashwin,100,137,8,33,13,8.22,33.00,13.00
254,SL Malinga,156,214,13,48,20,8.23,30.77,12.82
105,Imran Tahir,72,102,8,19,9,8.50,26.39,12.50
104,IK Pathan,96,136,6,29,12,8.50,30.21,12.50
84,DW Steyn,82,117,8,26,13,8.56,31.71,15.85
160,M Pathirana,66,97,6,23,11,8.82,34.85,16.67
6,A Nehra,78,115,8,24,13,8.85,30.77,16.67

In [317]:
fig = px.scatter(
    qualified_clutch_bowlers,
    x="Economy",
    y="Wickets",
    size="Balls",
    color="Dot Ball %",
    hover_name="bowler",
    hover_data=[
        "Boundary Concession %"
    ],
    title="Clutch Death Bowling in Close Matches"
)

fig.show()

#### <b>📈 Match Momentum Analysis</b>

##### Business Question

How does scoring momentum change throughout an innings?

Momentum is approximated using over-by-over:

- Runs
- Wickets
- Cumulative score
- Run rate

This allows analysts to identify acceleration, collapses, and turning points.

In [318]:
over_momentum = (
    phase_df
    .groupby(
        [
            "match_id",
            "innings",
            "batting_team",
            "over"
        ],
        as_index=False
    )
    .agg(
        Over_Runs=("total_runs", "sum"),
        Wickets=("is_wicket", "sum"),
        Legal_Balls=("is_legal_delivery", "sum")
    )
)

In [319]:
over_momentum = over_momentum.sort_values(
    [
        "match_id",
        "innings",
        "over"
    ]
)

over_momentum["Cumulative_Runs"] = (
    over_momentum
    .groupby(
        [
            "match_id",
            "innings"
        ]
    )["Over_Runs"]
    .cumsum()
)

over_momentum["Cumulative_Wickets"] = (
    over_momentum
    .groupby(
        [
            "match_id",
            "innings"
        ]
    )["Wickets"]
    .cumsum()
)

In [320]:
over_momentum["Cumulative_Balls"] = (
    over_momentum
    .groupby(
        [
            "match_id",
            "innings"
        ]
    )["Legal_Balls"]
    .cumsum()
)

over_momentum["Cumulative Run Rate"] = np.where(
    over_momentum["Cumulative_Balls"] > 0,
    (
        over_momentum["Cumulative_Runs"]
        /
        over_momentum["Cumulative_Balls"]
        * 6
    ),
    np.nan
).round(2)

#### <b>📊 Selected Match Momentum Dashboard</b>

Select one match to compare the scoring progression of both innings.

The dashboard shows:

- Runs scored in each over
- Cumulative score
- Wickets lost
- Acceleration and collapse periods

In [321]:
available_match_ids = (
    over_momentum["match_id"]
    .dropna()
    .unique()
)

available_match_ids[:10]

array([335982, 335983, 335984, 335985, 335986, 335987, 335988, 335989,
       335990, 335991])

In [322]:
selected_match_id = available_match_ids[0]

In [323]:
selected_match_momentum = over_momentum[
    over_momentum["match_id"]
    ==
    selected_match_id
].copy()

selected_match_momentum

,match_id,innings,batting_team,over,Over_Runs,Wickets,Legal_Balls,Cumulative_Runs,Cumulative_Wickets,Cumulative_Balls,Cumulative Run Rate
0,335982,1,Kolkata Knight Riders,0,3,0,6,3,0,6,3.00
1,335982,1,Kolkata Knight Riders,1,18,0,6,21,0,12,10.50
2,335982,1,Kolkata Knight Riders,2,6,0,6,27,0,18,9.00
3,335982,1,Kolkata Knight Riders,3,23,0,6,50,0,24,12.50
4,335982,1,Kolkata Knight Riders,4,10,0,6,60,0,30,12.00
5,335982,1,Kolkata Knight Riders,5,1,1,6,61,1,36,10.17
6,335982,1,Kolkata Knight Riders,6,7,0,6,68,1,42,9.71
7,335982,1,Kolkata Knight Riders,7,5,0,6,73,1,48,9.12
8,335982,1,Kolkata Knight Riders,8,4,0,6,77,1,54,8.56
9,335982,1,Kolkata Knight Riders,9,10,0,6,87,1,60,8.70
10,335982,1,Kolkata Knight Riders,10,15,0,6,102,1,66,9.27
11,335982,1,Kolkata Knight Riders,11,10,0,6,112,1,72,9.33
12,335982,1,Kolkata Knight Riders,12,12,1,6,124,2,78,9.54
13,335982,1,Kolkata Knight Riders,13,6,0,6,130,2,84,9.29
14,335982,1,Kolkata Knight Riders,14,24,0,6,154,2,90,10.27
15,335982,1,Kolkata Knight Riders,15,4,0,6,158,2,96,9.88
16,335982,1,Kolkata Knight Riders,16,14,0,6,172,2,102,10.12
17,335982,1,Kolkata Knight Riders,17,7,1,6,179,3,108,9.94
18,335982,1,Kolkata Knight Riders,18,21,0,6,200,3,114,10.53
19,335982,1,Kolkata Knight Riders,19,22,0,6,222,3,120,11.10
20,335982,2,Royal Challengers Bangalore,0,4,0,6,4,0,6,4.00
21,335982,2,Royal Challengers Bangalore,1,5,1,6,9,1,12,4.50
22,335982,2,Royal Challengers Bangalore,2,3,1,6,12,2,18,4.00
23,335982,2,Royal Challengers Bangalore,3,4,0,6,16,2,24,4.00
24,335982,2,Royal Challengers Bangalore,4,8,1,6,24,3,30,4.80
25,335982,2,Royal Challengers Bangalore,5,2,1,6,26,4,36,4.33
26,335982,2,Royal Challengers Bangalore,6,7,0,6,33,4,42,4.71
27,335982,2,Royal Challengers Bangalore,7,5,1,6,38,5,48,4.75
28,335982,2,Royal Challengers Bangalore,8,5,2,6,43,7,54,4.78
29,335982,2,Royal Challengers Bangalore,9,8,0,6,51,7,60,5.10
30,335982,2,Royal Challengers Bangalore,10,5,0,6,56,7,66,5.09
31,335982,2,Royal Challengers Bangalore,11,3,1,6,59,8,72,4.92
32,335982,2,Royal Challengers Bangalore,12,11,0,6,70,8,78,5.38
33,335982,2,Royal Challengers Bangalore,13,7,1,6,77,9,84,5.50
34,335982,2,Royal Challengers Bangalore,14,4,0,6,81,9,90,5.40
35,335982,2,Royal Challengers Bangalore,15,1,1,1,82,10,91,5.41

In [324]:
fig = px.line(
    selected_match_momentum,
    x="over",
    y="Cumulative_Runs",
    color="batting_team",
    line_dash="innings",
    markers=True,
    hover_data=[
        "Over_Runs",
        "Wickets",
        "Cumulative_Wickets",
        "Cumulative Run Rate"
    ],
    title=(
        f"Match Momentum – "
        f"Match {selected_match_id}"
    )
)

fig.update_layout(
    xaxis_title="Over",
    yaxis_title="Cumulative Runs"
)

fig.show()

In [325]:
fig = px.bar(
    selected_match_momentum,
    x="over",
    y="Over_Runs",
    color="batting_team",
    facet_row="innings",
    text="Over_Runs",
    title=(
        f"Over-by-Over Scoring – "
        f"Match {selected_match_id}"
    )
)

fig.show()

##### <b>💡 Business Insight</b>

Momentum charts reveal when a team accelerated, stagnated, or suffered a collapse.

They are particularly useful for identifying tactical turning points that are not visible from the final score alone.

#### <b>⚠️ Limitations of Pressure Analytics</b>

This analysis uses practical proxies for pressure, but pressure cannot be measured perfectly from scorecards alone.

Important limitations include:

1. Required run rate does not capture wickets remaining by itself.

2. Match pressure differs based on batter quality, bowling quality, venue, pitch, and tournament stage.

3. Rain-reduced matches require revised targets and revised ball limits.

4. A high required run rate early in an innings may be less critical than the same rate in the final two overs.

5. Close-match thresholds are subjective.

6. Career totals favour players with longer careers.

7. Death-over performance may be influenced by the quality of the opposing team.

8. A batter may score quickly after the match outcome is already nearly certain.

Future modeling should create a ball-level win probability and measure how each delivery changes the probability of victory.

#### <b>📌 Match Phase and Pressure Analytics Summary</b>

This notebook analyzed IPL performance across match phases and high-pressure situations.

##### Phase-Based Analysis

- Powerplay run rates
- Middle-over batting
- Death-over acceleration
- Phase-wise wicket patterns
- Over-by-over scoring

##### Finishing Performance

- Death-over batter statistics
- Finisher Score
- Death-over bowling statistics
- Scoring control and wicket-taking

##### Chase Pressure

- Target calculation
- Runs required
- Balls remaining
- Current run rate
- Required run rate
- Pressure-level classification

##### Clutch Analysis

- Team performance under high required run rates
- Batters under chase pressure
- Close-match team records
- Clutch batting
- Clutch bowling

##### Match Momentum

- Over-wise runs
- Cumulative scoring
- Wicket progression
- Match momentum dashboard

##### <b>Key Conclusion</b>

Phase and pressure analytics provide more useful strategic insight than aggregate career totals alone.

The strongest players and teams are those that perform effectively in the specific situations where matches are decided.

### <b>Section 10 – Business Insights and Executive Summary</b>

---

#### <b>🎯 Objective</b>

Sections 1–9 examined IPL data from multiple analytical perspectives:

- Data quality
- Match performance
- Team performance
- Batter performance
- Bowling performance
- Fielding performance
- Venue and match conditions
- Partnerships and player combinations
- Match phases and pressure situations

The purpose of this final EDA section is to consolidate those findings into a concise, decision-oriented executive summary.

Rather than introducing another independent analysis, this section translates the completed analytical work into:

- Executive KPIs
- Major findings
- Team-building insights
- Match-strategy recommendations
- Auction and retention recommendations
- Venue-specific recommendations
- Project limitations
- Future development opportunities

This section answers the stakeholder question:

> **What actions can an IPL franchise take based on the analysis?**

#### <b>📊 Executive KPI Overview</b>

Executive KPIs provide a high-level description of the dataset and the scope of the analysis.

The following indicators are calculated:

- Seasons covered
- Total matches
- Total deliveries
- Unique players
- Unique teams
- Unique venues
- Unique cities
- Total runs
- Total wickets
- Average first-innings score
- Overall chasing success rate

In [326]:
def safe_divide(numerator, denominator, multiplier=1):
    """
    Safely divide two numeric values.

    Returns NaN when the denominator is zero.
    """

    if denominator == 0:
        return np.nan

    return (numerator / denominator) * multiplier

In [327]:
# Number of seasons represented in the dataset
total_seasons = matches_df["season"].nunique()

# First and latest seasons
first_season = matches_df["season"].min()
latest_season = matches_df["season"].max()

# Dataset-level KPIs
total_matches = matches_df["match_id"].nunique()
total_deliveries = len(deliveries_df)

unique_players = players_df["player_registry_id"].nunique()
unique_player_names = players_df["player_name"].nunique()

unique_teams = pd.concat(
    [
        matches_df["team_1"],
        matches_df["team_2"]
    ]
).nunique()

unique_venues = matches_df["venue"].nunique()
unique_cities = matches_df["city"].nunique()

total_runs = deliveries_df["total_runs"].sum()
total_wickets = deliveries_df["is_wicket"].sum()
bowler_wickets = deliveries_df["is_bowler_wicket"].sum()

In [328]:
# First-innings score for every match
first_innings_scores = (
    deliveries_df[
        deliveries_df["innings"] == 1
    ]
    .groupby("match_id", as_index=False)
    .agg(
        First_Innings_Score=("total_runs", "sum")
    )
)

average_first_innings_score = (
    first_innings_scores["First_Innings_Score"]
    .mean()
)

In [329]:
# Identify the chasing team from the second innings
chasing_teams = (
    deliveries_df[
        deliveries_df["innings"] == 2
    ]
    .groupby("match_id", as_index=False)
    .agg(
        Chasing_Team=("batting_team", "first")
    )
)

chase_results = chasing_teams.merge(
    matches_df[
        [
            "match_id",
            "winner"
        ]
    ],
    on="match_id",
    how="left"
)

chase_results["Chase_Won"] = (
    chase_results["Chasing_Team"]
    ==
    chase_results["winner"]
).astype(int)

completed_chases = chase_results[
    chase_results["winner"].notna()
].copy()

chasing_success_rate = safe_divide(
    completed_chases["Chase_Won"].sum(),
    len(completed_chases),
    multiplier=100
)

In [330]:
executive_kpis = pd.DataFrame(
    {
        "KPI": [
            "Season Range",
            "Total Seasons",
            "Total Matches",
            "Total Deliveries",
            "Unique Registered Players",
            "Unique Player Names",
            "Unique Teams",
            "Unique Venues",
            "Unique Cities",
            "Total Runs",
            "Total Wickets",
            "Bowler-Credited Wickets",
            "Average First-Innings Score",
            "Overall Chasing Success Rate"
        ],
        "Value": [
            f"{first_season}–{latest_season}",
            total_seasons,
            f"{total_matches:,}",
            f"{total_deliveries:,}",
            f"{unique_players:,}",
            f"{unique_player_names:,}",
            unique_teams,
            unique_venues,
            unique_cities,
            f"{total_runs:,}",
            f"{total_wickets:,}",
            f"{bowler_wickets:,}",
            round(average_first_innings_score, 2),
            f"{chasing_success_rate:.2f}%"
        ]
    }
)

executive_kpis

                             KPI      Value
0                   Season Range  2008–2026
1                  Total Seasons         19
2                  Total Matches      1,243
3               Total Deliveries    295,732
4      Unique Registered Players        809
5            Unique Player Names        811
6                   Unique Teams         17
7                  Unique Venues         38
8                  Unique Cities         35
9                     Total Runs    401,738
10                 Total Wickets     14,705
11       Bowler-Credited Wickets     13,482
12   Average First-Innings Score     168.57
13  Overall Chasing Success Rate     54.68%

In [331]:
kpi_fig = go.Figure()

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_matches,
        title={"text": "Matches"},
        domain={
            "row": 0,
            "column": 0
        }
    )
)

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=total_deliveries,
        number={"valueformat": ","},
        title={"text": "Deliveries"},
        domain={
            "row": 0,
            "column": 1
        }
    )
)

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=unique_players,
        title={"text": "Players"},
        domain={
            "row": 0,
            "column": 2
        }
    )
)

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=unique_venues,
        title={"text": "Venues"},
        domain={
            "row": 1,
            "column": 0
        }
    )
)

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=average_first_innings_score,
        number={"valueformat": ".2f"},
        title={"text": "Average First-Innings Score"},
        domain={
            "row": 1,
            "column": 1
        }
    )
)

kpi_fig.add_trace(
    go.Indicator(
        mode="number",
        value=chasing_success_rate,
        number={
            "suffix": "%",
            "valueformat": ".2f"
        },
        title={"text": "Chasing Success"},
        domain={
            "row": 1,
            "column": 2
        }
    )
)

kpi_fig.update_layout(
    grid={
        "rows": 2,
        "columns": 3,
        "pattern": "independent"
    },
    height=500,
    title="IPL Analytics Executive KPI Dashboard"
)

kpi_fig.show()

##### <b>💡 Executive Insight</b>

The KPI dashboard confirms that the project covers a large historical dataset containing match-level, ball-level, and player-level information.

The combination of these three levels allows the analysis to answer both:

- Strategic questions, such as team and venue performance
- Tactical questions, such as phase-specific batting, bowling and pressure performance

The ball-by-ball dataset is the analytical foundation because it enables detailed reconstruction of innings, partnerships, player performance and match momentum.

#### <b>🏆 Team Performance Findings</b>

This subsection consolidates the principal team-level findings.

Teams are compared using:

- Matches played
- Wins
- Losses
- Win percentage
- Close-match wins
- Close-match win percentage

A minimum-match qualification is used so that teams with very small samples are not ranked unfairly.

In [332]:
team_1_records = matches_df[
    [
        "match_id",
        "team_1",
        "winner"
    ]
].rename(
    columns={
        "team_1": "team"
    }
)

team_2_records = matches_df[
    [
        "match_id",
        "team_2",
        "winner"
    ]
].rename(
    columns={
        "team_2": "team"
    }
)

team_match_records = pd.concat(
    [
        team_1_records,
        team_2_records
    ],
    ignore_index=True
)

team_match_records["Win"] = (
    team_match_records["team"]
    ==
    team_match_records["winner"]
).astype(int)

In [333]:
team_summary = (
    team_match_records
    .groupby("team", as_index=False)
    .agg(
        Matches=("match_id", "nunique"),
        Wins=("Win", "sum")
    )
)

team_summary["Losses_or_No_Result"] = (
    team_summary["Matches"]
    -
    team_summary["Wins"]
)

team_summary["Win Percentage"] = (
    team_summary["Wins"]
    /
    team_summary["Matches"]
    * 100
).round(2)

team_summary = team_summary.sort_values(
    [
        "Wins",
        "Win Percentage"
    ],
    ascending=[
        False,
        False
    ]
)

team_summary

,team,Matches,Wins,Losses_or_No_Result,Win Percentage
10,Mumbai Indians,291,155,136,53.26
0,Chennai Super Kings,266,148,118,55.64
15,Royal Challengers Bangalore,286,143,143,50.00
8,Kolkata Knight Riders,278,140,138,50.36
13,Rajasthan Royals,251,123,128,49.00
16,Sunrisers Hyderabad,211,102,109,48.34
6,Kings XI Punjab,190,85,105,44.74
3,Delhi Daredevils,161,67,94,41.61
2,Delhi Capitals,120,58,62,48.33
5,Gujarat Titans,77,47,30,61.04
12,Punjab Kings,88,41,47,46.59
9,Lucknow Super Giants,72,34,38,47.22
1,Deccan Chargers,75,29,46,38.67
14,Rising Pune Supergiants,30,15,15,50.00
4,Gujarat Lions,30,13,17,43.33
11,Pune Warriors,46,12,34,26.09
7,Kochi Tuskers Kerala,14,6,8,42.86

In [334]:
qualified_team_summary = (
    team_summary[
        team_summary["Matches"] >= 50
    ]
    .sort_values(
        "Win Percentage",
        ascending=False
    )
)

qualified_team_summary.head(10)

,team,Matches,Wins,Losses_or_No_Result,Win Percentage
5,Gujarat Titans,77,47,30,61.04
0,Chennai Super Kings,266,148,118,55.64
10,Mumbai Indians,291,155,136,53.26
8,Kolkata Knight Riders,278,140,138,50.36
15,Royal Challengers Bangalore,286,143,143,50.00
13,Rajasthan Royals,251,123,128,49.00
16,Sunrisers Hyderabad,211,102,109,48.34
2,Delhi Capitals,120,58,62,48.33
9,Lucknow Super Giants,72,34,38,47.22
12,Punjab Kings,88,41,47,46.59

In [335]:
fig = px.scatter(
    qualified_team_summary,
    x="Win Percentage",
    y="Wins",
    size="Matches",
    hover_name="team",
    hover_data=[
        "Losses_or_No_Result"
    ],
    title="Team Success: Win Volume vs Win Percentage"
)

fig.update_layout(
    xaxis_title="Win Percentage",
    yaxis_title="Total Wins"
)

fig.show()

In [336]:
most_successful_team_by_wins = (
    team_summary.iloc[0]
)

best_qualified_team_by_percentage = (
    qualified_team_summary.iloc[0]
)

print(
    "Most successful team by total wins:",
    most_successful_team_by_wins["team"]
)

print(
    "Total wins:",
    most_successful_team_by_wins["Wins"]
)

print(
    "\nBest qualified team by win percentage:",
    best_qualified_team_by_percentage["team"]
)

print(
    "Win percentage:",
    f"{best_qualified_team_by_percentage['Win Percentage']:.2f}%"
)

Most successful team by total wins: Mumbai Indians
Total wins: 155

Best qualified team by win percentage: Gujarat Titans
Win percentage: 61.04%

##### <b>💡 Business Insight</b>

Total wins and win percentage answer different questions.

- **Total wins** identify long-term franchise success and sustained participation.
- **Win percentage** measures performance efficiency.
- **Matches played** provide the sample-size context required to interpret both metrics.

A franchise should not evaluate competitive strength using one metric alone. A team with many wins may also have participated in substantially more matches, while a high percentage from a small sample may not represent stable performance.

#### <b>🏏 Batter Performance Findings</b>

Batters are evaluated through a combination of volume, efficiency and consistency.

The consolidated measures include:

- Total runs
- Balls faced
- Strike rate
- Fours
- Sixes
- Boundaries
- Dot-ball percentage
- Dismissals
- Batting average

In [337]:
batter_summary = (
    deliveries_df
    .groupby("batter", as_index=False)
    .agg(
        Runs=("batter_runs", "sum"),
        Balls=("is_legal_delivery", "sum"),
        Fours=("is_four", "sum"),
        Sixes=("is_six", "sum"),
        Boundaries=("is_boundary", "sum"),
        Dot_Balls=("is_dot_ball", "sum")
    )
)

In [338]:
batter_dismissals = (
    deliveries_df[
        deliveries_df["player_dismissed"].notna()
    ]
    .groupby(
        "player_dismissed",
        as_index=False
    )
    .size()
    .rename(
        columns={
            "player_dismissed": "batter",
            "size": "Dismissals"
        }
    )
)

batter_summary = batter_summary.merge(
    batter_dismissals,
    on="batter",
    how="left"
)

batter_summary["Dismissals"] = (
    batter_summary["Dismissals"]
    .fillna(0)
)

In [339]:
batter_summary["Strike Rate"] = np.where(
    batter_summary["Balls"] > 0,
    batter_summary["Runs"]
    /
    batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

batter_summary["Batting Average"] = np.where(
    batter_summary["Dismissals"] > 0,
    batter_summary["Runs"]
    /
    batter_summary["Dismissals"],
    np.nan
).round(2)

batter_summary["Dot Ball %"] = np.where(
    batter_summary["Balls"] > 0,
    batter_summary["Dot_Balls"]
    /
    batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

batter_summary["Boundary %"] = np.where(
    batter_summary["Balls"] > 0,
    batter_summary["Boundaries"]
    /
    batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

In [340]:
top_run_scorers = (
    batter_summary
    .sort_values(
        "Runs",
        ascending=False
    )
    .head(10)
)

top_run_scorers[
    [
        "batter",
        "Runs",
        "Balls",
        "Strike Rate",
        "Batting Average",
        "Fours",
        "Sixes",
        "Dot Ball %"
    ]
]

,batter,Runs,Balls,Strike Rate,Batting Average,Fours,Sixes,Dot Ball %
693,V Kohli,9346,6911,135.23,40.46,847,317,31.54
526,RG Sharma,7331,5496,133.39,29.80,661,324,36.79
563,S Dhawan,6769,5304,127.62,35.07,768,153,35.43
159,DA Warner,6567,4680,140.32,40.04,663,236,34.79
311,KL Rahul,5828,4175,139.59,45.53,509,239,31.66
597,SK Raina,5536,4025,137.54,32.37,506,204,31.70
409,MS Dhoni,5439,3935,138.22,38.30,375,264,31.72
52,AM Rahane,5367,4269,125.72,30.15,540,141,34.81
31,AB de Villiers,5181,3400,152.38,39.85,414,253,28.91
627,SV Samson,5181,3653,141.83,31.59,432,243,33.26

In [341]:
qualified_batters = (
    batter_summary[
        batter_summary["Balls"] >= 500
    ]
    .copy()
)

qualified_batters["Impact Score"] = (
    (
        qualified_batters["Strike Rate"].rank(
            pct=True
        )
        * 35
    )
    +
    (
        qualified_batters["Batting Average"].rank(
            pct=True
        )
        * 30
    )
    +
    (
        qualified_batters["Runs"].rank(
            pct=True
        )
        * 25
    )
    +
    (
        (
            1
            -
            qualified_batters["Dot Ball %"].rank(
                pct=True
            )
        )
        * 10
    )
).round(2)

top_impact_batters = (
    qualified_batters
    .sort_values(
        "Impact Score",
        ascending=False
    )
    .head(10)
)

top_impact_batters[
    [
        "batter",
        "Runs",
        "Batting Average",
        "Strike Rate",
        "Dot Ball %",
        "Impact Score"
    ]
]

,batter,Runs,Batting Average,Strike Rate,Dot Ball %,Impact Score
31,AB de Villiers,5181,39.85,152.38,28.91,91.62
225,H Klaasen,2104,42.08,167.92,23.94,88.04
103,B Sai Sudharsan,2515,48.37,150.24,27.96,86.96
262,JC Buttler,4647,39.38,150.19,34.36,84.61
651,Shubman Gill,4598,40.33,142.66,30.47,83.71
311,KL Rahul,5828,45.53,139.59,31.66,83.32
135,CH Gayle,4997,39.66,150.02,41.64,81.36
581,SA Yadav,4581,33.44,149.12,32.55,80.04
159,DA Warner,6567,40.04,140.32,34.79,79.57
693,V Kohli,9346,40.46,135.23,31.54,78.68

In [342]:
fig = px.scatter(
    qualified_batters,
    x="Batting Average",
    y="Strike Rate",
    size="Runs",
    color="Dot Ball %",
    hover_name="batter",
    hover_data=[
        "Fours",
        "Sixes",
        "Balls"
    ],
    title="Qualified Batter Performance Matrix"
)

fig.update_layout(
    xaxis_title="Batting Average",
    yaxis_title="Strike Rate"
)

fig.show()

##### <b>💡 Business Insight</b>

The best batter cannot be identified using only total runs.

A balanced batter assessment should distinguish among:

- **Run accumulation:** ability to score a large career volume
- **Scoring speed:** ability to score quickly
- **Wicket preservation:** ability to maintain a strong average
- **Pressure management:** ability to limit dot balls
- **Boundary production:** ability to accelerate the innings

This distinction is important during auctions because different batting roles require different combinations of these qualities.

#### <b>🎯 Bowling Performance Findings</b>

Bowlers are assessed using both wicket-taking and run-control measures.

The consolidated metrics include:

- Legal balls
- Overs
- Runs conceded
- Wickets
- Economy
- Bowling average
- Bowling strike rate
- Dot-ball percentage
- Boundary concession percentage

In [343]:
bowler_summary = (
    deliveries_df
    .groupby("bowler", as_index=False)
    .agg(
        Balls=("is_legal_delivery", "sum"),
        Runs_Conceded=("total_runs", "sum"),
        Wickets=("is_bowler_wicket", "sum"),
        Dot_Balls=("is_dot_ball", "sum"),
        Boundaries_Conceded=("is_boundary", "sum")
    )
)

In [344]:
bowler_summary["Overs"] = (
    bowler_summary["Balls"] / 6
)

bowler_summary["Economy"] = np.where(
    bowler_summary["Balls"] > 0,
    bowler_summary["Runs_Conceded"]
    /
    bowler_summary["Balls"]
    * 6,
    np.nan
).round(2)

bowler_summary["Bowling Average"] = np.where(
    bowler_summary["Wickets"] > 0,
    bowler_summary["Runs_Conceded"]
    /
    bowler_summary["Wickets"],
    np.nan
).round(2)

bowler_summary["Bowling Strike Rate"] = np.where(
    bowler_summary["Wickets"] > 0,
    bowler_summary["Balls"]
    /
    bowler_summary["Wickets"],
    np.nan
).round(2)

bowler_summary["Dot Ball %"] = np.where(
    bowler_summary["Balls"] > 0,
    bowler_summary["Dot_Balls"]
    /
    bowler_summary["Balls"]
    * 100,
    np.nan
).round(2)

bowler_summary["Boundary Concession %"] = np.where(
    bowler_summary["Balls"] > 0,
    bowler_summary["Boundaries_Conceded"]
    /
    bowler_summary["Balls"]
    * 100,
    np.nan
).round(2)

In [345]:
top_wicket_takers = (
    bowler_summary
    .sort_values(
        "Wickets",
        ascending=False
    )
    .head(10)
)

top_wicket_takers[
    [
        "bowler",
        "Wickets",
        "Economy",
        "Bowling Average",
        "Bowling Strike Rate",
        "Dot Ball %",
        "Boundary Concession %"
    ]
]

,bowler,Wickets,Economy,Bowling Average,Bowling Strike Rate,Dot Ball %,Boundary Concession %
569,YS Chahal,233,8.18,23.61,17.33,32.67,14.57
76,B Kumar,226,7.88,26.75,20.35,41.24,17.24
480,SP Narine,209,6.93,25.74,22.30,38.33,11.72
374,PP Chawla,192,8.07,26.97,20.05,34.42,15.48
213,JJ Bumrah,190,7.53,24.12,19.23,39.91,14.81
386,R Ashwin,187,7.29,30.59,25.19,34.10,11.78
131,DJ Bravo,183,8.53,24.24,17.05,31.99,16.15
405,RA Jadeja,180,7.79,30.69,23.63,31.55,13.26
432,Rashid Khan,179,7.43,24.53,19.79,35.48,13.24
8,A Mishra,174,7.46,24.10,19.37,35.15,12.55

In [346]:
qualified_bowlers = (
    bowler_summary[
        bowler_summary["Balls"] >= 600
    ]
    .copy()
)

qualified_bowlers["Bowling Impact Score"] = (
    (
        qualified_bowlers["Wickets"].rank(
            pct=True
        )
        * 35
    )
    +
    (
        (
            1
            -
            qualified_bowlers["Economy"].rank(
                pct=True
            )
        )
        * 25
    )
    +
    (
        (
            1
            -
            qualified_bowlers["Bowling Average"].rank(
                pct=True
            )
        )
        * 20
    )
    +
    (
        (
            1
            -
            qualified_bowlers["Bowling Strike Rate"].rank(
                pct=True
            )
        )
        * 10
    )
    +
    (
        qualified_bowlers["Dot Ball %"].rank(
            pct=True
        )
        * 10
    )
).round(2)

top_impact_bowlers = (
    qualified_bowlers
    .sort_values(
        "Bowling Impact Score",
        ascending=False
    )
    .head(10)
)

top_impact_bowlers[
    [
        "bowler",
        "Wickets",
        "Economy",
        "Bowling Average",
        "Bowling Strike Rate",
        "Dot Ball %",
        "Bowling Impact Score"
    ]
]

,bowler,Wickets,Economy,Bowling Average,Bowling Strike Rate,Dot Ball %,Bowling Impact Score
472,SL Malinga,170,7.40,20.51,16.63,40.47,92.14
213,JJ Bumrah,190,7.53,24.12,19.23,39.91,88.18
480,SP Narine,209,6.93,25.74,22.30,38.33,85.05
8,A Mishra,174,7.46,24.10,19.37,35.15,84.78
432,Rashid Khan,179,7.43,24.53,19.79,35.48,84.49
76,B Kumar,226,7.88,26.75,20.35,41.24,81.13
569,YS Chahal,233,8.18,23.61,17.33,32.67,79.93
10,A Nehra,106,7.98,23.93,18.00,41.82,79.78
151,DW Steyn,97,7.10,26.63,22.49,46.70,79.38
179,Harbhajan Singh,150,7.20,27.34,22.77,36.97,78.03

In [347]:
fig = px.scatter(
    qualified_bowlers,
    x="Economy",
    y="Wickets",
    size="Balls",
    color="Dot Ball %",
    hover_name="bowler",
    hover_data=[
        "Bowling Average",
        "Bowling Strike Rate",
        "Boundary Concession %"
    ],
    title="Qualified Bowler Performance Matrix"
)

fig.update_layout(
    xaxis_title="Economy Rate",
    yaxis_title="Total Wickets"
)

fig.show()

##### <b>💡 Business Insight</b>

Wicket-taking ability and scoring control must be evaluated together.

- A wicket-taking bowler may change the match despite conceding runs.
- An economical bowler may create pressure without taking many wickets.
- Dot balls are valuable because they increase pressure on the batter.
- Boundary concession shows whether a bowler can restrict rapid scoring.

A balanced bowling unit therefore requires multiple roles rather than several bowlers with identical profiles.

#### <b>🧤 Fielding Performance Findings</b>

Fielding is evaluated through recorded dismissal involvement.

The analysis identifies:

- Catch leaders
- Run-out leaders
- Stumping leaders
- Overall fielding involvement

These statistics represent recorded dismissals and do not capture runs saved or missed opportunities.

In [348]:
fielding_records = deliveries_df[
    deliveries_df["fielder"].notna()
].copy()

fielding_records["dismissal_kind_clean"] = (
    fielding_records["dismissal_kind"]
    .astype(str)
    .str.lower()
    .str.strip()
)

In [349]:
fielding_records["Catch"] = (
    fielding_records["dismissal_kind_clean"]
    .isin(
        [
            "caught",
            "caught and bowled"
        ]
    )
).astype(int)

fielding_records["Run_Out"] = (
    fielding_records["dismissal_kind_clean"]
    .eq("run out")
).astype(int)

fielding_records["Stumping"] = (
    fielding_records["dismissal_kind_clean"]
    .eq("stumped")
).astype(int)

In [350]:
fielder_summary = (
    fielding_records
    .groupby("fielder", as_index=False)
    .agg(
        Catches=("Catch", "sum"),
        Run_Outs=("Run_Out", "sum"),
        Stumpings=("Stumping", "sum")
    )
)

fielder_summary["Total Involvements"] = (
    fielder_summary["Catches"]
    +
    fielder_summary["Run_Outs"]
    +
    fielder_summary["Stumpings"]
)

top_fielders = (
    fielder_summary
    .sort_values(
        "Total Involvements",
        ascending=False
    )
    .head(10)
)

top_fielders

            fielder  Catches  Run_Outs  Stumpings  Total Involvements
370        MS Dhoni      158        27         47                 232
275      KD Karthik      145        17         37                 199
633         V Kohli      126        18          0                 144
23   AB de Villiers      120        13          8                 141
502      RV Uthappa       92         9         32                 133
655         WP Saha       93        12         26                 131
572       SV Samson       90        18         19                 127
472       RA Jadeja      104        20          0                 124
544        SK Raina      106        13          0                 119
491         RR Pant       90         4         24                 118

In [351]:
fig = px.bar(
    top_fielders,
    x="Total Involvements",
    y="fielder",
    orientation="h",
    color="Total Involvements",
    text="Total Involvements",
    hover_data=[
        "Catches",
        "Run_Outs",
        "Stumpings"
    ],
    title="Top Fielders by Recorded Dismissal Involvement"
)

fig.update_layout(
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

Fielding involvement provides evidence of direct wicket contributions, but it is not a complete fielding-quality metric.

The available scorecard data does not measure:

- Runs saved
- Dropped catches
- Missed run-outs
- Ground-fielding efficiency
- Throw accuracy
- Fielding difficulty

Therefore, fielding involvement should support player evaluation rather than act as the sole selection criterion.

#### <b>🏟️ Venue and Match-Condition Findings</b>

Venue analysis helps franchises understand how match conditions influence strategy.

The following measures are consolidated:

- Matches hosted
- Average first-innings score
- Highest first-innings score
- Chasing wins
- Defending wins
- Chasing success percentage

In [352]:
first_innings_by_venue = (
    deliveries_df[
        deliveries_df["innings"] == 1
    ]
    .groupby(
        [
            "match_id",
            "batting_team"
        ],
        as_index=False
    )
    .agg(
        First_Innings_Score=("total_runs", "sum")
    )
)

first_innings_by_venue = (
    first_innings_by_venue
    .merge(
        matches_df[
            [
                "match_id",
                "venue"
            ]
        ],
        on="match_id",
        how="left"
    )
)

In [353]:
venue_score_summary = (
    first_innings_by_venue
    .groupby("venue", as_index=False)
    .agg(
        Matches=("match_id", "nunique"),
        Average_First_Innings_Score=(
            "First_Innings_Score",
            "mean"
        ),
        Highest_First_Innings_Score=(
            "First_Innings_Score",
            "max"
        ),
        Lowest_First_Innings_Score=(
            "First_Innings_Score",
            "min"
        )
    )
)

venue_score_summary[
    "Average_First_Innings_Score"
] = venue_score_summary[
    "Average_First_Innings_Score"
].round(2)

In [354]:
venue_chase_summary = (
    chase_results
    .merge(
        matches_df[
            [
                "match_id",
                "venue"
            ]
        ],
        on="match_id",
        how="left"
    )
    .groupby("venue", as_index=False)
    .agg(
        Chases=("match_id", "nunique"),
        Successful_Chases=("Chase_Won", "sum")
    )
)

venue_chase_summary["Chasing Success %"] = np.where(
    venue_chase_summary["Chases"] > 0,
    venue_chase_summary["Successful_Chases"]
    /
    venue_chase_summary["Chases"]
    * 100,
    np.nan
).round(2)

In [355]:
venue_summary = venue_score_summary.merge(
    venue_chase_summary,
    on="venue",
    how="left"
)

qualified_venues = (
    venue_summary[
        venue_summary["Matches"] >= 10
    ]
    .sort_values(
        "Average_First_Innings_Score",
        ascending=False
    )
)

qualified_venues.head(15)

,venue,Matches,Average_First_Innings_Score,Highest_First_Innings_Score,Lowest_First_Innings_Score,Chases,Successful_Chases,Chasing Success %
12,"Himachal Pradesh Cricket Association Stadium, ...",19,191.21,254,120,18,7,38.89
18,Maharaja Yadavindra Singh International Cricke...,17,186.59,254,101,17,9,52.94
20,"Narendra Modi Stadium, Ahmedabad",53,180.68,243,89,53,26,49.06
4,"Brabourne Stadium, Mumbai",27,178.52,217,68,27,13,48.15
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29,174.79,235,121,28,16,57.14
16,"M Chinnaswamy Stadium, Bengaluru",104,174.06,287,62,103,56,54.37
36,"Wankhede Stadium, Mumbai",132,173.13,243,67,132,72,54.55
0,"Arun Jaitley Stadium, Delhi",104,171.76,278,56,103,54,52.43
8,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,17,169.53,272,121,17,9,52.94
28,"Sawai Mansingh Stadium, Jaipur",68,169.06,229,94,68,44,64.71
27,Saurashtra Cricket Association Stadium,10,168.90,213,135,10,6,60.00
10,"Eden Gardens, Kolkata",107,168.64,261,25,106,60,56.60
26,"Rajiv Gandhi International Stadium, Uppal, Hyd...",90,168.34,286,80,89,48,53.93
19,"Maharashtra Cricket Association Stadium, Pune",35,168.29,211,73,35,17,48.57
25,"Punjab Cricket Association IS Bindra Stadium, ...",61,168.28,257,67,61,34,55.74

In [356]:
fig = px.scatter(
    qualified_venues,
    x="Average_First_Innings_Score",
    y="Chasing Success %",
    size="Matches",
    color="Highest_First_Innings_Score",
    hover_name="venue",
    hover_data=[
        "Lowest_First_Innings_Score",
        "Successful_Chases"
    ],
    title="Venue Scoring and Chasing Conditions"
)

fig.update_layout(
    xaxis_title="Average First-Innings Score",
    yaxis_title="Chasing Success Percentage"
)

fig.show()

In [357]:
overall_average_score = (
    qualified_venues["Average_First_Innings_Score"]
    .mean()
)

overall_chase_rate = (
    qualified_venues["Chasing Success %"]
    .mean()
)

qualified_venues["Venue Strategy"] = np.select(
    [
        (
            qualified_venues["Average_First_Innings_Score"]
            >= overall_average_score
        )
        &
        (
            qualified_venues["Chasing Success %"]
            >= overall_chase_rate
        ),
        (
            qualified_venues["Average_First_Innings_Score"]
            >= overall_average_score
        )
        &
        (
            qualified_venues["Chasing Success %"]
            < overall_chase_rate
        ),
        (
            qualified_venues["Average_First_Innings_Score"]
            < overall_average_score
        )
        &
        (
            qualified_venues["Chasing Success %"]
            >= overall_chase_rate
        )
    ],
    [
        "High-Scoring and Chase-Friendly",
        "High-Scoring and Defence-Friendly",
        "Lower-Scoring and Chase-Friendly"
    ],
    default="Lower-Scoring and Defence-Friendly"
)

qualified_venues[
    [
        "venue",
        "Matches",
        "Average_First_Innings_Score",
        "Chasing Success %",
        "Venue Strategy"
    ]
].sort_values(
    "Matches",
    ascending=False
)

,venue,Matches,Average_First_Innings_Score,Chasing Success %,Venue Strategy
36,"Wankhede Stadium, Mumbai",132,173.13,54.55,High-Scoring and Chase-Friendly
10,"Eden Gardens, Kolkata",107,168.64,56.60,High-Scoring and Chase-Friendly
16,"M Chinnaswamy Stadium, Bengaluru",104,174.06,54.37,High-Scoring and Chase-Friendly
0,"Arun Jaitley Stadium, Delhi",104,171.76,52.43,High-Scoring and Defence-Friendly
17,"MA Chidambaram Stadium, Chepauk, Chennai",98,165.56,45.92,Lower-Scoring and Defence-Friendly
26,"Rajiv Gandhi International Stadium, Uppal, Hyd...",90,168.34,53.93,Lower-Scoring and Chase-Friendly
28,"Sawai Mansingh Stadium, Jaipur",68,169.06,64.71,High-Scoring and Chase-Friendly
25,"Punjab Cricket Association IS Bindra Stadium, ...",61,168.28,55.74,Lower-Scoring and Chase-Friendly
20,"Narendra Modi Stadium, Ahmedabad",53,180.68,49.06,High-Scoring and Defence-Friendly
9,Dubai International Cricket Stadium,46,163.76,47.83,Lower-Scoring and Defence-Friendly
7,"Dr DY Patil Sports Academy, Mumbai",37,159.65,54.05,Lower-Scoring and Chase-Friendly
19,"Maharashtra Cricket Association Stadium, Pune",35,168.29,48.57,Lower-Scoring and Defence-Friendly
31,Sheikh Zayed Stadium,29,158.86,55.17,Lower-Scoring and Chase-Friendly
3,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,29,174.79,57.14,High-Scoring and Chase-Friendly
30,Sharjah Cricket Stadium,28,159.04,64.29,Lower-Scoring and Chase-Friendly
4,"Brabourne Stadium, Mumbai",27,178.52,48.15,High-Scoring and Defence-Friendly
12,"Himachal Pradesh Cricket Association Stadium, ...",19,191.21,38.89,High-Scoring and Defence-Friendly
18,Maharaja Yadavindra Singh International Cricke...,17,186.59,52.94,High-Scoring and Defence-Friendly
8,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,17,169.53,52.94,High-Scoring and Defence-Friendly
33,Subrata Roy Sahara Stadium,16,149.44,37.50,Lower-Scoring and Defence-Friendly
15,Kingsmead,15,152.00,46.67,Lower-Scoring and Defence-Friendly
34,SuperSport Park,12,154.83,66.67,Lower-Scoring and Chase-Friendly
27,Saurashtra Cricket Association Stadium,10,168.90,60.00,High-Scoring and Chase-Friendly

##### <b>💡 Business Insight</b>

Venue conditions should influence tactical decisions rather than being treated as background information.

Examples of venue-driven decisions include:

- Whether to bat or field after winning the toss
- The appropriate first-innings target
- The number of specialist finishers required
- The balance between pace and spin
- The acceptable level of Powerplay risk
- The ideal bowling allocation at the death

Historical venue results are useful, but final decisions should also consider the current pitch, weather, dew and team composition.

#### <b>🤝 Partnership and Player-Combination Findings</b>

Partnership analysis evaluates how pairs of batters perform together.

The consolidated measures include:

- Partnership runs
- Balls
- Strike rate
- Boundary percentage
- Number of innings together
- Average runs per innings

Player combinations with larger samples are more reliable than pairs that appeared together only a few times.

In [358]:
partnership_summary_df = deliveries_df.copy()

partnership_summary_df["Player_1"] = (
    partnership_summary_df[
        [
            "batter",
            "non_striker"
        ]
    ]
    .min(axis=1)
)

partnership_summary_df["Player_2"] = (
    partnership_summary_df[
        [
            "batter",
            "non_striker"
        ]
    ]
    .max(axis=1)
)

partnership_summary_df["Partnership"] = (
    partnership_summary_df["Player_1"]
    +
    " & "
    +
    partnership_summary_df["Player_2"]
)

In [359]:
partnership_summary = (
    partnership_summary_df
    .groupby(
        [
            "Player_1",
            "Player_2",
            "Partnership"
        ],
        as_index=False
    )
    .agg(
        Runs=("total_runs", "sum"),
        Balls=("is_legal_delivery", "sum"),
        Innings=("match_id", "nunique"),
        Boundaries=("is_boundary", "sum")
    )
)

partnership_summary["Strike Rate"] = np.where(
    partnership_summary["Balls"] > 0,
    partnership_summary["Runs"]
    /
    partnership_summary["Balls"]
    * 100,
    np.nan
).round(2)

partnership_summary["Runs per Innings"] = np.where(
    partnership_summary["Innings"] > 0,
    partnership_summary["Runs"]
    /
    partnership_summary["Innings"],
    np.nan
).round(2)

partnership_summary["Boundary %"] = np.where(
    partnership_summary["Balls"] > 0,
    partnership_summary["Boundaries"]
    /
    partnership_summary["Balls"]
    * 100,
    np.nan
).round(2)

In [360]:
qualified_partnerships = (
    partnership_summary[
        partnership_summary["Innings"] >= 10
    ]
    .sort_values(
        "Runs",
        ascending=False
    )
)

qualified_partnerships.head(10)

,Player_1,Player_2,Partnership,Runs,Balls,Innings,Boundaries,Strike Rate,Runs per Innings,Boundary %
381,AB de Villiers,V Kohli,AB de Villiers & V Kohli,3134,2011,77,385,155.84,40.70,19.14
1297,B Sai Sudharsan,Shubman Gill,B Sai Sudharsan & Shubman Gill,2966,1823,49,393,162.70,60.53,21.56
1619,CH Gayle,V Kohli,CH Gayle & V Kohli,2802,1888,60,385,148.41,46.70,20.39
1929,DA Warner,S Dhawan,DA Warner & S Dhawan,2357,1668,50,324,141.31,47.14,19.42
2416,F du Plessis,V Kohli,F du Plessis & V Kohli,2032,1339,41,274,151.76,49.56,20.46
1817,D Padikkal,V Kohli,D Padikkal & V Kohli,2024,1329,43,265,152.29,47.07,19.94
2452,G Gambhir,RV Uthappa,G Gambhir & RV Uthappa,1906,1378,48,254,138.32,39.71,18.43
1007,Abhishek Sharma,TM Head,Abhishek Sharma & TM Head,1892,910,42,307,207.91,45.05,33.74
2869,Ishan Kishan,RG Sharma,Ishan Kishan & RG Sharma,1868,1269,54,279,147.20,34.59,21.99
3520,KL Rahul,MA Agarwal,KL Rahul & MA Agarwal,1731,1171,33,227,147.82,52.45,19.39

In [361]:
fig = px.scatter(
    qualified_partnerships.head(30),
    x="Runs per Innings",
    y="Strike Rate",
    size="Runs",
    color="Innings",
    hover_name="Partnership",
    hover_data=[
        "Boundary %",
        "Balls"
    ],
    title="Qualified Batting Partnership Matrix"
)

fig.update_layout(
    xaxis_title="Average Partnership Runs per Match",
    yaxis_title="Partnership Strike Rate"
)

fig.show()

##### <b>💡 Business Insight</b>

Partnership quality is not determined by cumulative runs alone.

A valuable combination should demonstrate:

- Sufficient time together
- Reliable run production
- Scoring efficiency
- Complementary batting roles
- Ability to perform across different conditions

Partnership findings can support batting-order planning, retention decisions and the selection of compatible player combinations.

#### <b>🔥 Match-Phase and Pressure Findings</b>

Cricket performance changes significantly according to match phase.

The innings is divided using the dataset's zero-based over numbering:

- Powerplay: Overs 0–5
- Middle Overs: Overs 6–14
- Death Overs: Overs 15–19

The analysis identifies phase-specific batters, finishers and bowlers.

In [362]:
executive_phase_df = deliveries_df.copy()

executive_phase_df["Phase"] = np.select(
    [
        executive_phase_df["over"].between(0, 5),
        executive_phase_df["over"].between(6, 14),
        executive_phase_df["over"].between(15, 19)
    ],
    [
        "Powerplay",
        "Middle Overs",
        "Death Overs"
    ],
    default="Other"
)

In [363]:
phase_summary = (
    executive_phase_df[
        executive_phase_df["Phase"] != "Other"
    ]
    .groupby("Phase", as_index=False)
    .agg(
        Runs=("total_runs", "sum"),
        Balls=("is_legal_delivery", "sum"),
        Wickets=("is_wicket", "sum"),
        Boundaries=("is_boundary", "sum"),
        Dot_Balls=("is_dot_ball", "sum")
    )
)

phase_summary["Run Rate"] = np.where(
    phase_summary["Balls"] > 0,
    phase_summary["Runs"]
    /
    phase_summary["Balls"]
    * 6,
    np.nan
).round(2)

phase_summary["Wickets per 100 Balls"] = np.where(
    phase_summary["Balls"] > 0,
    phase_summary["Wickets"]
    /
    phase_summary["Balls"]
    * 100,
    np.nan
).round(2)

phase_summary["Dot Ball %"] = np.where(
    phase_summary["Balls"] > 0,
    phase_summary["Dot_Balls"]
    /
    phase_summary["Balls"]
    * 100,
    np.nan
).round(2)

phase_summary

,Phase,Runs,Balls,Wickets,Boundaries,Dot_Balls,Run Rate,Wickets per 100 Balls,Dot Ball %
0,Death Overs,106952,63786,5383,13241,18145,10.06,8.44,28.45
1,Middle Overs,174283,131526,5708,18760,41777,7.95,4.34,31.76
2,Powerplay,120503,89318,3614,18225,41308,8.09,4.05,46.25

In [364]:
fig = px.bar(
    phase_summary,
    x="Phase",
    y="Run Rate",
    color="Phase",
    text="Run Rate",
    hover_data=[
        "Wickets",
        "Wickets per 100 Balls",
        "Dot Ball %"
    ],
    title="Scoring Rate Across Match Phases"
)

fig.show()

In [365]:
death_batting = executive_phase_df[
    executive_phase_df["Phase"] == "Death Overs"
].copy()

death_batter_summary = (
    death_batting
    .groupby("batter", as_index=False)
    .agg(
        Runs=("batter_runs", "sum"),
        Balls=("is_legal_delivery", "sum"),
        Boundaries=("is_boundary", "sum"),
        Dot_Balls=("is_dot_ball", "sum")
    )
)

death_batter_summary["Strike Rate"] = np.where(
    death_batter_summary["Balls"] > 0,
    death_batter_summary["Runs"]
    /
    death_batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

death_batter_summary["Boundary %"] = np.where(
    death_batter_summary["Balls"] > 0,
    death_batter_summary["Boundaries"]
    /
    death_batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

death_batter_summary["Dot Ball %"] = np.where(
    death_batter_summary["Balls"] > 0,
    death_batter_summary["Dot_Balls"]
    /
    death_batter_summary["Balls"]
    * 100,
    np.nan
).round(2)

In [366]:
qualified_finishers = (
    death_batter_summary[
        death_batter_summary["Balls"] >= 120
    ]
    .copy()
)

qualified_finishers["Finisher Score"] = (
    qualified_finishers["Strike Rate"].rank(
        pct=True
    )
    * 35
    +
    qualified_finishers["Boundary %"].rank(
        pct=True
    )
    * 25
    +
    (
        1
        -
        qualified_finishers["Dot Ball %"].rank(
            pct=True
        )
    )
    * 20
    +
    qualified_finishers["Runs"].rank(
        pct=True
    )
    * 20
).round(2)

top_finishers = (
    qualified_finishers
    .sort_values(
        "Finisher Score",
        ascending=False
    )
    .head(10)
)

top_finishers[
    [
        "batter",
        "Runs",
        "Balls",
        "Strike Rate",
        "Boundary %",
        "Dot Ball %",
        "Finisher Score"
    ]
]

,batter,Runs,Balls,Strike Rate,Boundary %,Dot Ball %,Finisher Score
28,AB de Villiers,1868,829,225.33,33.17,18.21,98.10
592,T Stubbs,546,274,199.27,27.74,16.42,88.59
613,V Kohli,1573,830,189.52,25.54,22.17,86.90
557,SV Samson,852,442,192.76,27.38,22.62,86.83
118,CH Gayle,581,280,207.50,31.79,24.64,85.49
198,H Klaasen,738,381,193.70,25.72,20.73,85.49
571,Shashank Singh,512,262,195.42,27.10,19.08,85.20
92,B Sai Sudharsan,308,146,210.96,30.82,19.86,84.35
233,JC Buttler,804,412,195.15,27.43,24.03,84.15
483,RR Pant,1095,537,203.91,31.84,28.12,83.89

In [367]:
death_bowler_summary = (
    death_batting
    .groupby("bowler", as_index=False)
    .agg(
        Balls=("is_legal_delivery", "sum"),
        Runs_Conceded=("total_runs", "sum"),
        Wickets=("is_bowler_wicket", "sum"),
        Dot_Balls=("is_dot_ball", "sum"),
        Boundaries_Conceded=("is_boundary", "sum")
    )
)

death_bowler_summary["Economy"] = np.where(
    death_bowler_summary["Balls"] > 0,
    death_bowler_summary["Runs_Conceded"]
    /
    death_bowler_summary["Balls"]
    * 6,
    np.nan
).round(2)

death_bowler_summary["Bowling Strike Rate"] = np.where(
    death_bowler_summary["Wickets"] > 0,
    death_bowler_summary["Balls"]
    /
    death_bowler_summary["Wickets"],
    np.nan
).round(2)

death_bowler_summary["Dot Ball %"] = np.where(
    death_bowler_summary["Balls"] > 0,
    death_bowler_summary["Dot_Balls"]
    /
    death_bowler_summary["Balls"]
    * 100,
    np.nan
).round(2)

In [368]:
qualified_death_bowlers = (
    death_bowler_summary[
        death_bowler_summary["Balls"] >= 120
    ]
    .sort_values(
        [
            "Economy",
            "Wickets"
        ],
        ascending=[
            True,
            False
        ]
    )
)

qualified_death_bowlers.head(10)

,bowler,Balls,Runs_Conceded,Wickets,Dot_Balls,Boundaries_Conceded,Economy,Bowling Strike Rate,Dot Ball %
405,SP Narine,1105,1365,84,413,141,7.41,13.15,37.38
111,DE Bollinger,234,297,23,88,30,7.62,10.17,37.61
6,A Kumble,167,217,17,58,23,7.80,9.82,34.73
239,M Kartik,154,207,6,29,18,8.06,25.67,18.83
121,DL Vettori,165,223,7,49,25,8.11,23.57,29.70
397,SL Malinga,1117,1526,108,350,154,8.20,10.34,31.33
151,Harmeet Singh,129,178,10,46,20,8.28,12.90,35.66
243,M Muralitharan,275,380,22,103,43,8.29,12.50,37.45
327,R Ashwin,601,834,36,178,76,8.33,16.69,29.62
344,RD Chahar,170,237,14,55,24,8.36,12.14,32.35

##### <b>💡 Business Insight</b>

Aggregate statistics may hide a player's actual tactical value.

For example:

- An opener should be evaluated heavily on Powerplay scoring.
- A middle-order anchor should be evaluated on stability and rotation.
- A finisher should be evaluated on death-over scoring efficiency.
- A death bowler should be evaluated on both economy and wickets in the final overs.

Role-specific analysis is therefore more useful for squad construction than comparing every player using the same career metric.

#### <b>⚔️ Close-Match and Clutch Findings</b>

Close matches reveal how teams and players respond when the margin for error is small.

A close match is defined as:

- A victory by 1–10 runs, or
- A victory by 1–3 wickets

The thresholds are analytical assumptions rather than official IPL classifications.

In [369]:
executive_matches_df = matches_df.copy()

executive_matches_df["Is_Close_Match"] = (
    executive_matches_df["win_by_runs"]
    .between(1, 10)
    |
    executive_matches_df["win_by_wickets"]
    .between(1, 3)
)

close_matches_summary = executive_matches_df[
    executive_matches_df["Is_Close_Match"]
].copy()

print(
    "Total close matches:",
    close_matches_summary["match_id"].nunique()
)

print(
    "Percentage of matches classified as close:",
    round(
        close_matches_summary["match_id"].nunique()
        /
        executive_matches_df["match_id"].nunique()
        * 100,
        2
    ),
    "%"
)

Total close matches: 184
Percentage of matches classified as close: 14.8 %

In [370]:
close_team_1 = close_matches_summary[
    [
        "match_id",
        "team_1",
        "winner"
    ]
].rename(
    columns={
        "team_1": "team"
    }
)

close_team_2 = close_matches_summary[
    [
        "match_id",
        "team_2",
        "winner"
    ]
].rename(
    columns={
        "team_2": "team"
    }
)

close_team_records = pd.concat(
    [
        close_team_1,
        close_team_2
    ],
    ignore_index=True
)

close_team_records["Win"] = (
    close_team_records["team"]
    ==
    close_team_records["winner"]
).astype(int)

In [371]:
close_team_performance = (
    close_team_records
    .groupby("team", as_index=False)
    .agg(
        Close_Matches=("match_id", "nunique"),
        Close_Wins=("Win", "sum")
    )
)

close_team_performance["Close Match Win %"] = (
    close_team_performance["Close_Wins"]
    /
    close_team_performance["Close_Matches"]
    * 100
).round(2)

qualified_close_teams = (
    close_team_performance[
        close_team_performance["Close_Matches"] >= 10
    ]
    .sort_values(
        "Close Match Win %",
        ascending=False
    )
)

qualified_close_teams

                           team  Close_Matches  Close_Wins  Close Match Win %
9          Lucknow Super Giants             14          10              71.43
16          Sunrisers Hyderabad             28          17              60.71
13             Rajasthan Royals             40          24              60.00
15  Royal Challengers Bangalore             35          21              60.00
2                Delhi Capitals             15           8              53.33
6               Kings XI Punjab             27          14              51.85
12                 Punjab Kings             16           8              50.00
5                Gujarat Titans             16           8              50.00
10               Mumbai Indians             39          18              46.15
0           Chennai Super Kings             36          16              44.44
8         Kolkata Knight Riders             48          20              41.67
1               Deccan Chargers             13           5              38.46
3              Delhi Daredevils             26           9              34.62

In [372]:
fig = px.bar(
    qualified_close_teams,
    x="Close Match Win %",
    y="team",
    orientation="h",
    color="Close Match Win %",
    text="Close Match Win %",
    hover_data=[
        "Close_Matches",
        "Close_Wins"
    ],
    title="Team Performance in Close Matches"
)

fig.update_layout(
    yaxis={
        "categoryorder": "total ascending"
    }
)

fig.show()

##### <b>💡 Business Insight</b>

A strong close-match record may indicate:

- Effective death-over execution
- Reliable finishers
- Better tactical decisions
- Stronger fielding under pressure
- More disciplined bowling plans

However, close-match percentages can be volatile. The number of close matches must always be shown alongside the win percentage.

#### <b>👑 Consolidated Performance Leaders</b>

The following tables identify the leading performers across the principal dimensions examined in Sections 1–9.

Qualification criteria are retained where required to reduce small-sample bias.

In [373]:
performance_leaders = pd.DataFrame(
    {
        "Category": [
            "Most Successful Team by Wins",
            "Best Qualified Team by Win Percentage",
            "Highest Career Run Scorer",
            "Highest-Ranked Qualified Impact Batter",
            "Highest Wicket Taker",
            "Highest-Ranked Qualified Impact Bowler",
            "Highest Fielding Involvement",
            "Highest-Ranked Qualified Finisher",
            "Best Qualified Death Bowler by Economy",
            "Best Qualified Close-Match Team"
        ],
        "Leader": [
            team_summary.iloc[0]["team"],
            qualified_team_summary.iloc[0]["team"],
            top_run_scorers.iloc[0]["batter"],
            top_impact_batters.iloc[0]["batter"],
            top_wicket_takers.iloc[0]["bowler"],
            top_impact_bowlers.iloc[0]["bowler"],
            top_fielders.iloc[0]["fielder"],
            top_finishers.iloc[0]["batter"],
            qualified_death_bowlers.iloc[0]["bowler"],
            qualified_close_teams.iloc[0]["team"]
        ],
        "Supporting Value": [
            f"{team_summary.iloc[0]['Wins']} wins",
            (
                f"{qualified_team_summary.iloc[0]['Win Percentage']:.2f}%"
                " win rate"
            ),
            f"{top_run_scorers.iloc[0]['Runs']} runs",
            (
                f"{top_impact_batters.iloc[0]['Impact Score']:.2f}"
                " impact score"
            ),
            f"{top_wicket_takers.iloc[0]['Wickets']} wickets",
            (
                f"{top_impact_bowlers.iloc[0]['Bowling Impact Score']:.2f}"
                " bowling impact score"
            ),
            (
                f"{top_fielders.iloc[0]['Total Involvements']}"
                " involvements"
            ),
            (
                f"{top_finishers.iloc[0]['Finisher Score']:.2f}"
                " finisher score"
            ),
            (
                f"{qualified_death_bowlers.iloc[0]['Economy']:.2f}"
                " death-over economy"
            ),
            (
                f"{qualified_close_teams.iloc[0]['Close Match Win %']:.2f}%"
                " close-match win rate"
            )
        ]
    }
)

performance_leaders

,Category,Leader,Supporting Value
0,Most Successful Team by Wins,Mumbai Indians,155 wins
1,Best Qualified Team by Win Percentage,Gujarat Titans,61.04% win rate
2,Highest Career Run Scorer,V Kohli,9346 runs
3,Highest-Ranked Qualified Impact Batter,AB de Villiers,91.62 impact score
4,Highest Wicket Taker,YS Chahal,233 wickets
5,Highest-Ranked Qualified Impact Bowler,SL Malinga,92.14 bowling impact score
6,Highest Fielding Involvement,MS Dhoni,232 involvements
7,Highest-Ranked Qualified Finisher,AB de Villiers,98.10 finisher score
8,Best Qualified Death Bowler by Economy,SP Narine,7.41 death-over economy
9,Best Qualified Close-Match Team,Lucknow Super Giants,71.43% close-match win rate

In [374]:
venue_leaders = pd.DataFrame(
    {
        "Category": [
            "Most Frequently Used Venue",
            "Highest Average First-Innings Score",
            "Highest Qualified Chasing Success Rate"
        ],
        "Venue": [
            (
                venue_summary
                .sort_values(
                    "Matches",
                    ascending=False
                )
                .iloc[0]["venue"]
            ),
            (
                qualified_venues
                .sort_values(
                    "Average_First_Innings_Score",
                    ascending=False
                )
                .iloc[0]["venue"]
            ),
            (
                qualified_venues
                .sort_values(
                    "Chasing Success %",
                    ascending=False
                )
                .iloc[0]["venue"]
            )
        ],
        "Value": [
            (
                venue_summary
                .sort_values(
                    "Matches",
                    ascending=False
                )
                .iloc[0]["Matches"]
            ),
            (
                qualified_venues
                .sort_values(
                    "Average_First_Innings_Score",
                    ascending=False
                )
                .iloc[0]["Average_First_Innings_Score"]
            ),
            (
                f"{qualified_venues.sort_values(
                    'Chasing Success %',
                    ascending=False
                ).iloc[0]['Chasing Success %']:.2f}%"
            )
        ]
    }
)

venue_leaders

,Category,Venue,Value
0,Most Frequently Used Venue,"Wankhede Stadium, Mumbai",132
1,Highest Average First-Innings Score,"Himachal Pradesh Cricket Association Stadium, ...",191.21
2,Highest Qualified Chasing Success Rate,SuperSport Park,66.67%

#### <b>🏏 Strategic Batting Recommendations</b>

Based on the completed batter, partnership, venue and phase analyses, a franchise should structure its batting strategy around clearly defined roles.

##### <b>1. Opening Strategy</b>

Opening batters should be selected using:

- Powerplay strike rate
- Boundary percentage
- Dot-ball control
- Performance against the new ball
- Partnership compatibility

The highest career run scorer is not automatically the best Powerplay opener.

##### <b>2. Middle-Over Strategy</b>

Middle-order batters should demonstrate:

- Wicket preservation
- Strike rotation
- Ability to score against spin
- Partnership stability
- Capacity to accelerate before the Death Overs

##### <b>3. Finishing Strategy</b>

Finishers should be selected using death-over statistics rather than overall career strike rate.

Important measures include:

- Death-over strike rate
- Boundary percentage
- Dot-ball percentage
- Runs scored in the final five overs
- Performance in close matches
- Sample size

##### <b>4. Batting-Order Flexibility</b>

A fixed batting order may not be optimal for every match.

The order can be adjusted according to:

- Venue
- Required run rate
- Match phase
- Bowling matchups
- Wickets remaining
- Player form

##### <b>5. Partnership Planning</b>

Historical partnership data can identify combinations that produce both stability and scoring efficiency.

Teams should consider preserving successful combinations while also accounting for left-right batting balance and opposition matchups.

#### <b>🎯 Strategic Bowling Recommendations</b>

Bowling resources should be allocated according to phase-specific strengths.

##### <b>1. Powerplay Bowling</b>

Powerplay bowlers should be evaluated using:

- New-ball wickets
- Dot-ball percentage
- Economy
- Boundary concession
- Ability to dismiss opening batters

##### <b>2. Middle-Over Bowling</b>

Middle-over specialists should provide:

- Wicket-taking ability
- Run-rate control
- Pressure through dot balls
- Effective performance against established batters

##### <b>3. Death-Over Bowling</b>

Death bowlers should be selected using death-over data rather than overall economy.

Important indicators include:

- Death-over economy
- Death-over wickets
- Bowling strike rate
- Dot-ball percentage
- Boundary concession percentage
- Close-match performance

##### <b>4. Bowling-Unit Balance</b>

A strong bowling unit should contain complementary profiles:

- New-ball wicket-taker
- Powerplay control bowler
- Middle-over wicket-taker
- Middle-over containment bowler
- Death-over specialist
- Flexible sixth-bowling option

##### <b>5. Matchup-Based Usage</b>

Bowling changes should consider batter-specific records, venue conditions and the current match state rather than following a fixed over allocation in every game.

#### <b>🏟️ Venue and Toss Recommendations</b>

Historical venue analysis can support toss and match-strategy decisions.

##### <b>At High-Scoring, Chase-Friendly Venues</b>

A franchise may:

- Prefer chasing
- Retain additional finishing depth
- Avoid depending only on a par score
- Protect death-over bowling resources
- Plan for a higher target

##### <b>At High-Scoring, Defence-Friendly Venues</b>

A franchise may:

- Consider batting first
- Maximise Powerplay scoring
- Build a score above the historical average
- Select bowlers capable of defending totals
- Plan matchups for the final five overs

##### <b>At Lower-Scoring Venues</b>

A franchise may:

- Prioritise wicket preservation
- Select high-control bowlers
- Avoid excessive early risk
- Treat every partnership as strategically important
- Value fielding more heavily

##### <b>Important Limitation</b>

Historical venue data should support—not replace—current information such as:

- Pitch report
- Weather
- Dew
- Boundary dimensions
- Surface preparation
- Recent venue behaviour

#### <b>💼 Auction and Retention Recommendations</b>

The analysis can support evidence-based squad planning.

##### <b>1. Avoid Evaluating Players Only Through Career Totals</b>

Career totals are influenced by the number of matches played. Efficiency, role and recent performance must also be considered.

##### <b>2. Prioritise Scarce Tactical Roles</b>

Specialists who can perform difficult roles may be more valuable than another general top-order batter.

Scarce roles can include:

- Reliable death-over finishers
- Death-over bowlers
- Powerplay wicket-takers
- Middle-over spin hitters
- Flexible all-rounders
- High-quality wicketkeepers

##### <b>3. Use Qualification Thresholds</b>

An exceptional metric from a very small sample should not be treated as proven performance.

Minimum matches, innings, balls or overs should be used before ranking players.

##### <b>4. Combine Performance and Role Fit</b>

A player may be statistically strong but still duplicate an existing role in the squad.

Auction decisions should consider:

- Performance
- Tactical role
- Squad balance
- Venue suitability
- Overseas-player restrictions
- Availability
- Age and development potential
- Expected acquisition cost

##### <b>5. Retain Complementary Player Combinations</b>

Strong partnerships and complementary player profiles can be retained together when the combination produces stable performance across multiple seasons.

##### <b>6. Avoid Overpaying for Unsustainable Performance</b>

A single successful season may not represent long-term quality.

Franchises should compare:

- Career performance
- Recent form
- Season-to-season consistency
- Role-specific performance
- Opposition strength
- Venue-adjusted performance

#### <b>📋 Franchise Decision Matrix</b>

The following matrix translates analytical findings into possible franchise actions.

In [375]:
franchise_decision_matrix = pd.DataFrame(
    {
        "Business Area": [
            "Opening Combination",
            "Middle-Order Stability",
            "Finishing",
            "Powerplay Bowling",
            "Middle-Over Bowling",
            "Death Bowling",
            "Fielding",
            "Venue Planning",
            "Toss Strategy",
            "Auction Planning",
            "Player Retention",
            "Opposition Analysis"
        ],
        "Primary Analytics": [
            "Powerplay runs, strike rate and partnerships",
            "Average, consistency and middle-over performance",
            "Death-over strike rate and Finisher Score",
            "Powerplay wickets, economy and dot-ball percentage",
            "Wickets, economy and phase performance",
            "Death economy, wickets and boundary concession",
            "Catches, run-outs and stumpings",
            "Average score and chasing success",
            "Venue history and innings results",
            "Role scarcity and performance efficiency",
            "Consistency, role fit and partnerships",
            "Team, phase, venue and matchup analytics"
        ],
        "Possible Action": [
            "Select compatible openers with controlled aggression",
            "Use reliable anchors and flexible middle-order roles",
            "Recruit proven death-over hitters",
            "Retain new-ball wicket-taking options",
            "Select wicket-taking and control specialists",
            "Prioritise proven death-over bowlers",
            "Improve selection and fielding development",
            "Adjust team composition to conditions",
            "Choose bat or field using venue-specific evidence",
            "Allocate budget to difficult-to-fill roles",
            "Retain reliable and complementary players",
            "Create opponent-specific match plans"
        ]
    }
)

franchise_decision_matrix

,Business Area,Primary Analytics,Possible Action
0,Opening Combination,"Powerplay runs, strike rate and partnerships",Select compatible openers with controlled aggr...
1,Middle-Order Stability,"Average, consistency and middle-over performance",Use reliable anchors and flexible middle-order...
2,Finishing,Death-over strike rate and Finisher Score,Recruit proven death-over hitters
3,Powerplay Bowling,"Powerplay wickets, economy and dot-ball percen...",Retain new-ball wicket-taking options
4,Middle-Over Bowling,"Wickets, economy and phase performance",Select wicket-taking and control specialists
5,Death Bowling,"Death economy, wickets and boundary concession",Prioritise proven death-over bowlers
6,Fielding,"Catches, run-outs and stumpings",Improve selection and fielding development
7,Venue Planning,Average score and chasing success,Adjust team composition to conditions
8,Toss Strategy,Venue history and innings results,Choose bat or field using venue-specific evidence
9,Auction Planning,Role scarcity and performance efficiency,Allocate budget to difficult-to-fill roles
10,Player Retention,"Consistency, role fit and partnerships",Retain reliable and complementary players
11,Opposition Analysis,"Team, phase, venue and matchup analytics",Create opponent-specific match plans

#### <b>🚀 Project Impact</b>

This IPL Analytics Platform demonstrates an end-to-end data analytics workflow.

##### <b>Data Engineering</b>

- Parsing raw JSON match files
- Extracting nested match information
- Transforming ball-by-ball records
- Creating match, delivery and player datasets
- Validating processed outputs

##### <b>Data Quality</b>

- Missing-value analysis
- Duplicate detection
- Data-type inspection
- Business-rule validation
- Memory analysis

##### <b>Exploratory Data Analysis</b>

- Match-level analysis
- Team-level analysis
- Batter analysis
- Bowling analysis
- Fielding analysis
- Venue analysis
- Partnership analysis
- Match-phase analysis
- Pressure and clutch analysis

##### <b>Business Analytics</b>

- Translating statistics into franchise decisions
- Comparing performance using qualification thresholds
- Identifying role-specific players
- Supporting venue and toss strategies
- Supporting auction and retention planning

##### <b>Data Visualisation</b>

- Interactive Plotly charts
- Performance matrices
- Trend charts
- Bubble charts
- Phase comparisons
- Network analysis
- Match-momentum visualisations

##### <b>Domain Knowledge</b>

The project applies cricket-specific rules and concepts such as:

- Legal deliveries
- Bowler-attributed wickets
- Match phases
- Strike rate
- Economy
- Required run rate
- Partnerships
- Close-match performance

#### <b>⚠️ Project Limitations</b>

Although the project provides extensive historical analysis, the following limitations should be recognised.

##### <b>1. Scorecard-Based Data</b>

The dataset primarily contains scorecard and ball-by-ball information. It does not include detailed tracking information.

##### <b>2. No Ball-Tracking Data</b>

The analysis cannot directly measure:

- Ball speed
- Ball trajectory
- Swing
- Seam movement
- Spin rate
- Release point
- Shot direction
- Bat speed

##### <b>3. Limited Fielding Measurement</b>

The dataset records dismissal involvement but not:

- Runs saved
- Dropped catches
- Missed chances
- Fielding difficulty
- Throw quality

##### <b>4. No Player Fitness Information</b>

Injuries, fatigue, workload and fitness status are not represented.

##### <b>5. No Salary or Auction-Price Data</b>

The analysis evaluates cricket performance but cannot directly calculate value for money.

##### <b>6. No Detailed Weather Data</b>

Temperature, humidity, rain probability and dew are not included.

##### <b>7. No Detailed Pitch Data</b>

The same venue may produce different surfaces across seasons and matches.

##### <b>8. Historical Team Names</b>

Franchise renaming and restructuring may create separate team categories unless names are standardised.

##### <b>9. Career Aggregation Bias</b>

Career totals favour players and teams with longer participation histories.

##### <b>10. Small-Sample Bias</b>

Some players may appear exceptional because they played only a small number of deliveries or matches.

##### <b>11. Subjective Composite Scores</b>

Finisher, consistency and impact-score weights are analytical assumptions rather than official cricket measures.

##### <b>12. Close-Match Definition</b>

The thresholds used to classify close matches are subjective.

##### <b>13. Rain-Reduced Matches</b>

Standard required-run-rate calculations may require special handling for revised targets and reduced innings.

##### <b>14. Correlation Is Not Causation</b>

Historical relationships do not prove that one factor directly caused the match result.

#### <b>🔮 Future Scope</b>

The completed EDA creates the foundation for dashboards and machine-learning models.

##### <b>Module 3 – Interactive Dashboards</b>

The next module will build:

- Executive overview dashboard
- Team dashboard
- Batter dashboard
- Bowler dashboard
- Venue dashboard
- Match dashboard

##### <b>Module 4 – Machine Learning</b>

Planned predictive solutions include:

1. First-innings score prediction
2. Pre-match winner prediction
3. Ball-by-ball win-probability prediction
4. Player-performance prediction
5. Team and player recommendation systems

##### <b>Additional Data Sources</b>

The platform can later be enriched with:

- Player auction prices
- Salaries
- Weather
- Pitch reports
- Player injuries
- Player age
- Batting position
- Bowling style
- Player availability
- Ball-tracking data

##### <b>Advanced Analytical Extensions</b>

Potential future analyses include:

- Batter-versus-bowler matchups
- Venue-adjusted player ratings
- Opponent-strength adjustment
- Elo team ratings
- Player form indexes
- Expected runs
- Expected wickets
- Win-probability-added
- Player similarity
- Optimal playing-XI recommendations
- Fantasy-team optimisation

#### <b>📌 Final Executive Summary</b>

The IPL Cricket Analytics Platform transforms raw match data into a structured decision-support system.

The analysis demonstrates that overall career totals alone are insufficient for evaluating players and teams. Performance must be interpreted according to:

- Role
- Match phase
- Venue
- Sample size
- Scoring efficiency
- Wicket preservation
- Pressure conditions
- Partnership compatibility

Team success is best evaluated using both total wins and win percentage. Batter evaluation should combine run volume, strike rate, batting average, dot-ball control and role-specific performance. Bowling evaluation should combine wickets, economy, average, strike rate, dot-ball production and boundary control.

Venue analysis shows why franchises should adapt their strategy to local scoring and chasing conditions. Partnership analysis provides evidence for batting-order planning, while phase analysis identifies specialist openers, anchors, finishers and death bowlers.

Close-match and pressure analytics provide an additional layer of tactical insight by showing which teams and players deliver when the margin for error is smallest.

From a franchise perspective, the principal recommendations are:

1. Build the squad around clearly defined tactical roles.
2. Evaluate players using role-specific statistics.
3. Apply minimum-sample qualifications before ranking performance.
4. Prioritise scarce skills such as finishing and death bowling.
5. Use venue history to inform team composition and toss strategy.
6. Preserve successful and complementary player combinations.
7. Combine descriptive analytics with current match conditions.
8. Use the completed EDA as the foundation for interactive dashboards and predictive modelling.

The project therefore moves beyond producing charts. It demonstrates how data engineering, exploratory analysis, domain knowledge and business reasoning can be combined to support professional cricket decisions.